webshit/index.html
Adds clickable thumbnails if more than 1 image is returned from SaveImage
=> Added preview of batches of images

web/scripts/app.js
Addresses #76
ctrl+enter -> queue
ctrl+shift+enter -> queue front
=> Queue prompt hotkey

web/scripts/app.js, web/scripts/ui.js
Allows user to specify the number of batches to queue instead of click spamming the queue button.
=> add batch count to the menu

web/scripts/app.js, web/scripts/widgets.js
Allows dragging of image files onto any node with the IMAGEUPLOAD widget 
#70
=> Drag drop image upload on node

.gitignore
Just want to keep it tidy so if someone uses this file it won't show as untracked
=> add extra_model_paths.yaml to .gitignore

web/scripts/widgets.js
=> ui: hide decimal fraction for int fields

web/scripts/widgets.js
This allows for multiple text areas on a single widget, allowing for things such as combining CLIPTextEncodes into a single node
To test, run in the console:
```
(async () => {
const {ComfyWidgets} = await import("/scripts/widgets.js")
class Test {
constructor() {
ComfyWidgets["STRING"](this, "b", ["STRING", { multiline: false }], app);
ComfyWidgets["STRING"](this, "a", ["STRING", { multiline: true }], app);
ComfyWidgets["STRING"](this, "a", ["STRING", { multiline: true }], app);
ComfyWidgets["STRING"](this, "b", ["STRING", { multiline: false }], app);
this.addCustomWidget({
type: "test",
computeSize() {
return [0, 100];
},
draw(ctx, _, w, y) {
ctx.fillStyle = "red";
ctx.fillRect(0, y, w, 100);
},
});
ComfyWidgets["STRING"](this, "b", ["STRING", { multiline: false }], app); …
```
=> Add support for multiple multiline text areas on the same widget

execution.py, web/scripts/app.js
I've seen multiple requests for people wanting to output the results of node execution to the UI, this PR provides a simple way to achieve this.
Currently if a node execution returns an object with `"ui"` it sends that to the client but there is no way for your node to have any other output, this allows for nodes to return `{ "ui": something, "result": (your node output) }`
Nodes can now handle an `onExecuted` event that will contain any outputs sent to the frontend for that node
For nodes where having a widget doesnt make sense, you can now specify `forceInput: True` on an input definition and it will create an input instead
---
An example of this for reference is a ShowText node that displays whatever input it is given (e.g. prompt generator, interrogator, wildcards)
```js
import { app …
```
=> Easier socket message handling

web/extensions/core/widgetInputs.js
This PR adds the feature converting *optional* widgets to inputs, enhancing #243.
=> allow converting optional widgets to inputs

web/scripts/ui.js
Really like the new draggable menu from #265 !
Add setting to save menu position
Add anchoring to side when resizing which feels more natural (e.g. I move between different resolution windows reguarly, but always want it to be docked in the bottom right)
Fix losing menu when resizing
Fix menu shifting off screen on small resolution
Formatted file
=> Add setting to save menu position + anchor to side

web/extensions/core/rerouteNode.js
Being able to reroute nodes vertically will make graphes a lot cleaner!
=> Adds orientation settings to reroute nodes, allowing for cleaner graphes.

web/scripts/ui.js
Uses the default browser popup to ask for confirmation before removing all nodes.
=> Ask for confirmation before clearing nodes

web/style.css
=> Fix .graphdialog style

web/scripts/ui.js
Extends #392 by adding a setting to enable/disable it.
Also adds a prompt to the "Load Default" button.
=> Make clear confirmation optional

web/scripts/ui.js
Updated clear check to use this
=> Simpler setting value access

web/scripts/ui.js, web/style.css
=> Style modals to match rest of UI

web/scripts/ui.js, web/style.css
Makes the whole titlebar draggable, rather than just that one corner.
=> Drag menu with titlebar

README.md, comfy/diffusers_convert.py, folder_paths.py, nodes.py
Adds the DiffusersLoader node. This loads folders from models/diffusers
and an example of it working
=> Add diffusers loader node

web/scripts/app.js
Allows dropping of images from other tabs/images in the browser (e.g. directly from matrix)
=> Add support for dropping images from urls

comfy_extras/nodes_mask.py, nodes.py
This allows better compositing with a new optional mask input to the LatentComposite node.  This replaces the old feather value, with additional utilities allowing old behavior to be recreated.  The new feather/mask nodes provide more control over feathering.
=> Adds masking to Latent Composite, and provides new masking utilities

web/scripts/pnginfo.js
=> Prevent generating bad replacement regex

web/extensions/core/widgetInputs.js
Fixes #461 and the comment on #453
=> Fix combo primitive

web/scripts/app.js, web/types/comfy.d.ts, web/types/litegraph.d.ts
Added litegraph type definitions
No functional changes just adding some type info for easier development:
=> Adds jsdoc for better dev experience

nodes.py, web/extensions/core/noteNode.js
Multi-line note node. Very straight forward but useful to me and seemingly other users. (#468)
=> New Note node

web/extensions/core/editAttention.js
=> Editattention setting

web/extensions/core/editAttention.js
https://user-images.githubusercontent.com/4073789/233551986-88a61778-e61c-44bb-b11e-2df19ba27199.mp4
=> Remove brackets if weight == 1

nodes.py
This enables workflows like "Inpaint at full resolution" when using batch sizes greater than 1.
For the other nodes required for this workflow (specifically the `Mask by Text` node that can
dynamically generate masks for each image in a batch), see this WIP repo:
https://github.com/BadCafeCode/masquerade-nodes-comfyui
=> Add support for multiple unique inpainting masks

comfy/samplers.py, nodes.py
This PR adds support for a Condition by Mask node. This node allows conditioning to be limited to a non-rectangle area.
=> Add Condition by Mask node

comfy/samplers.py
This is useful when e.g. you need to call the sampler many times when doing a tiled sampler.
=> allow disabling of progress bar when sampling

web/scripts/app.js, web/scripts/widgets.js
Uses the last widget position to calculate the position and size of the node to display the image
=> Automatic calculation of image position + node size from widgets

web/scripts/app.js
Fixes #617
Fix box shape
Fix card shape, LiteGraph does its selection wrong, will need fixing in the litegraph repo
=> Fix progress outline

web/scripts/app.js
just allows touch dragging on mobile device
=> patch: allow touch drag

nodes.py, server.py
I have implemented a simple Latent Save/Load nodes rely on **safetensor**. In consideration of future extensibility, I have also made it possible to store metadata together, similar to .png files.
=> feat:Latent Save/Load

comfy_extras/nodes_post_processing.py
- post processing sharpen and blur node now pad images with reflect before sharpening/bluring to reduce artifacts at the edges of the image
- sharpen node now uses a gaussian kernel instead of a simple square kernel
- alpha scaling no longer scales the center pixel in the sharpen node
- alpha scaling in the sharpen node can now be set to zero, resulting in an image identical to the input image instead of what previously would be a black image.
=> improve sharpen and blur nodes

comfy/utils.py
optimized bislerp by vectorizing the for loops away.
Double checked vectorization is correct by testing with regular lerp against `torch.nn.functional.interpolate` with `mode="bilinear"`.
output Tensors differ from those previously, likely due to minor differences in slerp implementation. If desired most of those changes could be reverted to the old slerp implementation but i feel this one is more correct.
on my computer bislerping from 512 to 4096 went from 165 seconds to 0.3 seconds
=> vecorized bislerp

comfy_extras/nodes_mask.py
Just clamps the mask value to 1 if the operation passes
=> Bitwise operations for masks

README.md, web/extensions/core/dynamicPrompts.js
Prompt textareas can now use C-style comments
=> Comment syntax

.gitignore
=> Issue 742: Extension folder should be ignored

web/extensions/core/colorPalette.js, web/extensions/core/slotDefaults.js, web/scripts/ui.js, web/style.css
This PR beautifies the settings dialog. The content sits inside a [dialog element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog).
Previous |Dark             |  Light | Solarized
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
Perhaps additional grooming is needed.
=> Beautify the settings dialog

README.md
=> Add link to 7z in README

extra_model_paths.yaml.example
Add path to Real-ESRGAN upscaler 😺 
Thanks!
=> Update extra_model_paths.yaml.example: add RealESRGAN path

latent_preview.py
https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants
=> fix: Image.ANTIALIAS is no longer available.

web/scripts/app.js, web/scripts/widgets.js
=> bugfix: image widget was mis-aligned when node has multiline widget

execution.py
This worked previously before #579
=> Reallow nodes to provide an empty set of required inputs

nodes.py
I'm not sure what the policy on adding nodes to the project is, but I've been playing around with different ideas and options and ended up using this as part of a up-scaling workflow.
The other blend modes I know of don't work with the numeric range of latents, but simple blending does, That said there might be other modes that can be added to this if someone thinks them up.
I completely understand if this isn't something you want to merge, but I figured I'd offer it up since it seems to work decently (tested with batches and different sized inputs) its mostly based on ImageBlend.
I've been loving the application, having moved over from automate1111 it does take some getting used to differences but the flexibility and way prototyping ideas works is great!
=> Add LatentBlend node, allowing for blending between two Latent inputs.

comfy/k_diffusion/sampling.py, comfy/samplers.py
New k_diffusion samplers adapted from:
https://github.com/crowsonkb/k-diffusion/blob/ab527a9a6d347f364e3d185ba6d714e22d80cb3c/k_diffusion/sampling.py#L656
=> dpmpp 3m + dpmpp 3m sde added

comfy_extras/nodes_mask.py
Currently there is no way to expand masks (the actual masked values not the image borders). Scipy is already a project dependancy, so its dilate_grayscale_mask would be a lightweight solution.
=> add a node to allow growing of masks through dilation

web/index.html, web/user.css
Allows the user to add their own styles, e.g. font sizes
=> Allow user customizable css

comfy/k_diffusion/sampling.py
Fixes https://github.com/BlenderNeko/ComfyUI_TiledKSampler/issues/13.
=> Fix reference before assignment

server.py
Minor change to allow requests with bigger body sizes to be sent to the server.
=> Increase client_max_size to allow bigger request bodies

comfy/model_patcher.py
=> Fix error message in model_patcher.py

web/scripts/app.js, web/scripts/widgets.js
It can be useful to paste images from the clipboard directly into the node graph. This commit modifies copy and paste handling to support this.
When an image file is found in the clipboard, we check whether an image node is selected. If so, paste the image into that node. Otherwise, a new node is created. If no image data are found in the clipboard, we call the original Litegraph paste. To ensure that onCopy and onPaste events are fired, we override Litegraph's ctrl+c and ctrl+v handling.
Try to detect whether the pasted image is a real file on disk, or just pixel data copied from e.g. Photoshop. Pasted pixel data will be called 'image.png' and have a creation time of now. If it is simply pasted data, we store it in the subfolder /input/clipboard/.
This also adds support for the subfolder …
=> Add support for pasting images into the graph

web/scripts/app.js
Fixes dimtoneff/ComfyUI-PixelArt-Detector#8
See https://github.com/comfyanonymous/ComfyUI/pull/1104#issuecomment-1706889760 as well.
=> fix(ui/widgets): Only set widget forceInput option if a widget is added

web/scripts/widgets.js
=> Fixed Load Image preview not displaying some files (issue #1158)

comfy/utils.py, comfy_extras/nodes_post_processing.py, nodes.py
=> Added support for lanczos scaling

comfy/model_management.py
=> Allow Intel GPUs to LoRA cast on GPU since it supports BF16 natively.

comfy/sd.py
This PR aims to fix some of the quality loss that appears when running the VAE at a lower precision (FP16 and BF16, though it's more obvious for BF16, since it only uses 7 bits for the mantissa).
I simply changed the [0;1] (image) to [-1;1] (VAE input) range conversion to happen before the conversion to BF16. This way the decimal part isn't mangled as much by the lower precision format.
Below are a few comparisons. INT8 is what most images use, the change here is relatively small. INT16 is a high color precision PNG, which makes the difference more obvious. I can't tell how much tiled decode improves since it adds a bit of artifacting/color shifting, but some of the banding seems to be gone for INT16. INT8 looked exactly the same for the most part, probably because I didn't have to change …
=> Reduce VAE quality loss in FP16/BF16

comfy_extras/nodes_compositing.py, comfy_extras/nodes_mask.py, nodes.py
=> Added support for Porter-Duff image compositing

web/extensions/core/widgetInputs.js
The widget config was moved to a function instead of a property, so it wasnt serialized into the saved graph
That works fine with JSON.stringify and skips any non-json types
However, some custom nodes are using structuredClone on the graph, and this throws errors instead of skipping properties
This changes getConfig to be accessed via a symbol so structuredClone doesn't attempt to clone it.
=> Fix custom nodes using structuredClone on the graph

web/scripts/app.js
- Align the image size based on square cell dimensions, not the first image.
- Display the boundaries of the cells.
- Properly handle the image aspect ratio.
- Change the position of buttons on the image to a fixed location instead of a relative position on the image (this prevents issues with the button position changing as the image aspect ratio changes).
=> improve: image preview

comfy/cli_args.py, folder_paths.py, main.py
There are options to set the output and temp directory, but the option for the input directory is missing, so this PR adds it.
=> Option to input directory

comfy_extras/nodes_mask.py
This PR fix some mask nodes that got broken by the mask batch changing the shape.
Solves #1725
=> Fix mask nodes

web/scripts/ui.js
Today if there is an error the auto queue keeps queuing in loop, over and over again, this PR fix it.
=> Stop auto queue on error

web/extensions/core/groupOptions.js
This PR adds the menu option to select the nodes inside the group.
=> Group menu option select nodes

README.md, web/scripts/app.js
This PR adds the shortcut Alt + C to collapse/uncollapse the selected nodes.
=> Shortcut Alt + C to collapse/uncollapse selected nodes

web/extensions/core/groupOptions.js
- Add Group For Selected Nodes
- Add Selected Nodes To Group
- Fit Group To Nodes
https://github.com/comfyanonymous/ComfyUI/assets/5104869/9838d8da-890b-4e48-8f4c-9d4cffd15272
=> Group options

web/extensions/core/nodeTemplates.js, web/scripts/app.js
This PR adds the feature to export and import templates.
You can export all templates or a single template, and import multiple template json files.
This PR also makes it possible to drag and drop a template json file into the canvas to add it to the workflow without adding it to the management system.
=> Export and import templates

web/scripts/app.js
=> Load API JSON

comfy/sd1_clip.py
=> fix: adaptation to older versions of pytroch

web/scripts/app.js
=> Call widget onRemove to remove element

comfy_extras/nodes_hypertile.py
Use Torch's rng instead of Python's. This gives deterministic behavour since ComfyUI sets Torch's seed when sampling.
Fixes #2007
=> Make HyperTile deterministic

comfy/samplers.py, comfy_extras/nodes_perpneg.py, nodes.py
Implement Perp-Neg as a sampler_cfg_function patch
=> Implement Perp-Neg

.github/workflows/test-ui.yaml, tests-ui/afterSetup.js, tests-ui/jest.config.js
Enable verbose output to see run times per test
Add a warmup before each test file loading litegraph/app
Increase test timeout to 10s
=> Try to improve test reliability

web/scripts/domWidget.js
* Fix regression introduced in https://github.com/comfyanonymous/ComfyUI/pull/2330.
* Fixes https://github.com/comfyanonymous/ComfyUI/issues/2371.
=> Fix hiding dom widgets.

server.py
Fixes `/free` handler function name
=> fix: `/free` handler function name

comfy/samplers.py
self.scheduler -> scheduler_name
=> fix: typo - calculate_sigmas_scheduler

web/extensions/core/maskeditor.js
In environments where a pen is used, the right button cannot be utilized. To compensate for this, an action combining the alt/shift key and drag is provided.
- alt-drag: erase
- shift-drag(up/down): zoom in/out
=> feat: better pen support for mask editor

web/extensions/core/widgetInputs.js
=> Prevent hideWidget being called twice for same widget

comfy_extras/nodes_model_merging.py
Additional ways of merging CLIPs, similar to the one for models.
=> Added additional nodes for CLIP merging

.github/workflows/test-browser.yml, web/scripts/ui.js
https://github.com/comfyanonymous/ComfyUI/pull/3112 adds a duplicated `Reset View` button. This PR removes it.
=> Remove duplicated Reset View button

web/scripts/app.js
Fix issue where a duplicate line was added due to a bad merge
=> Fix merge issue breaking api json loading

.github/workflows/test-browser.yml
Update browsertest ref to include more tests that were added in https://github.com/Comfy-Org/ComfyUI_frontend/pull/53
=> Update test ref

.gitignore
Ignores auto-generated *.log files.
=> Ignore *.log

.gitignore
Ignores .vscode/ directory for developers who use VSCode.
=> Ignore .vscode/

comfy_extras/nodes_audio.py, web/extensions/core/uploadAudio.js, web/scripts/app.js, web/style.css
This PR adds audio widget for `SaveAudio` node and `LoadAudio` node.
Reference PR on image upload widget impl: https://github.com/comfyanonymous/ComfyUI/pull/55
Synced with TS repo PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/54
Stable Audio Guide: https://gist.github.com/comfyanonymous/0e04181f7fd01301230adc106b691cc2
=> Add audio widget

web/extensions/core/uploadAudio.js
Prevent update if there is no audio in the input directory.
=> Fix audio upload when no audio in input dir

.github/conda-environments/linux-environment.yml, .github/workflows/linux-integration-test.yml
- Generates images from default workflow.
- Cache model + conda environment to speed up runs
- Uses [comfy-action](https://github.com/Comfy-Org/comfy-action) to run workflows
Will Add Mac + Windows in following PRs.
Successful run on Mirror repo:
https://github.com/Comfy-Org/ComfyUI-Mirror/actions/runs/9688185193/job/26734246293
=> Add integration test for Linux with Nvidia GPU. #3884

web/scripts/changeTracker.js, web/scripts/ui/menu/menu.css, web/scripts/ui/menu/queueButton.js, web/scripts/workflows.js
- Fix auto queue not working (enable either instant or on change)
- Add change tracker detection for nodes added via the node search (double click, add node, ctrl+z) #3885
- Add button click style (small shadow when clicking buttons)
- Fix loading unsaved workflow (try swapping between two unsaved workflows, or closing an unsaved workflow) #3867
=> New menu/workflows fixes

folder_paths.py
Closes https://github.com/comfyanonymous/ComfyUI/issues/3937.
=> 3.8 Compatible type annotation

.github/workflows/test-browser.yml
Closes https://github.com/comfyanonymous/ComfyUI/issues/3956
Sample expected console output:
```
Total VRAM 15981 MB, total RAM 15981 MB
pytorch version: 2.3.1+cpu
Set vram state to: DISABLED
Device: cpu
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Import times for custom nodes:
0.0 seconds: /home/runner/work/ComfyUI/ComfyUI/ComfyUI/custom_nodes/websocket_image_save.py
Starting server
To see the GUI go to: http://127.0.0.1:8188
```
Sample failing test
https://github.com/comfyanonymous/ComfyUI/pull/3988
=> Check unhandled exception in test log in test action

.github/ISSUE_TEMPLATE/bug-report.yml
Update bug issue template to include instruction on reproduce the issue with all custom nodes disabled.
=> Update bug issue template

.github/workflows/pylint.yml, .pylintrc
Enforces ComfyUI code standard. https://github.com/comfyanonymous/ComfyUI/wiki/How-to-Contribute-Code#general
=> Monitor usage of `eval` with pylint

comfy/clip_vision.py, comfy/clip_vision_config_vitl_336.json
https://huggingface.co/Kwai-Kolors/Kolors-IP-Adapter-Plus uses openai/clip-vit-large-patch14-336 as image_encoder
=> support clip-vit-large-patch14-336

comfy/text_encoders/flux.py
https://github.com/comfyanonymous/ComfyUI/issues/4167
=> Fix clip_g/clip_l mixup

comfy_extras/nodes_audio.py
The missing import makes the LoadAudio always "changed" and reloading every time.
=> Fix LoadAudio IS_CHANGED

.github/workflows/test-ci.yml
Automatically runs a matrix of full GPU-enabled tests on all new commits to the ComfyUI master branch. Results are published as checkmarks on commits and to https://ci.comfy.org/
=> Add full CI test matrix GitHub Workflow

.github/workflows/pullrequest-ci-run.yml
=> minor fix on copypasta action name

comfy/controlnet.py, comfy/ldm/flux/controlnet_xlabs.py, comfy/ldm/flux/model.py
I'm leaving this here because I'm not sure if I implemented it correctly or if the results are supposed to be this bad.
It only seems to work with FluxGuidance set to 4.0
Here's a workflow for anyone who wants to test it:
You can find the model file here: https://huggingface.co/XLabs-AI/flux-controlnet-canny/tree/main
=> xlabs Flux controlnet implementation.

comfy/latent_formats.py, comfy/taesd/taesd.py, nodes.py
Starting on implementation of #4408
=> Implement support for taef1 latent previews

README.md
Document new shortcuts:
- Comfy-Org/ComfyUI_frontend#267
- Comfy-Org/litegraph.js#32
- Comfy-Org/litegraph.js#31
"wire" was already being used
=> Add new shortcuts to readme

README.md
This PR adds a frontend section to guide users to file bugs and feature requests to frontend repo.
=> Update README to include frontend section

README.md
=> Update README.md (Add shield badges)

comfy/lora.py
In ComfyUI-layerdiffuse, I had this ugly patch on `calculate_weight` to allow weight padding when diff shape is larger than weight shape. https://github.com/huchenlei/ComfyUI-layerdiffuse/blob/2cbfe3972c18f3bce49d6bf9631d5fd49d9d81d0/layered_diffusion.py#L34-L98
Recently, https://github.com/comfyanonymous/ComfyUI/commit/c26ca272076262c8b21a8f2e094cf538d88b9e46 breaks this patch. So I think it's time we enable this to be less hacky. Here I added a new optional options dict as the second items of the value array, so that we can have a `pad_weight` flag to control whether to pad the weight to diff's shape before calculation.
The call site looks like this for IC-Light:
```python
ic_model_state_dict = ic_model.model.diffusion_model.state_dict()
work_model.add_patches(
patches={ …
```
=> Support weight padding on diff weight patch

script_examples/websockets_api_example.py, tests/inference/test_execution.py, tests/inference/test_inference.py
fix: remove redundant useless loop
fix: potential error of undefined variable
https://github.com/comfyanonymous/ComfyUI/discussions/4650
=> fix: useless loop & potential undefined variable

app/user_manager.py, tests-unit/prompt_server_test/user_manager_test.py
This PR adds support of listing user files with size and last modified timestamp. This is necessary to detect the change made to the file by other instances of ComfyUI / other programs.
=> Add full_info flag in /userdata endpoint to list out file size and last modified timestamp

comfy/utils.py
As an example previously a 1024x1024 image with tile size of 1024 required 4 tiles to process and with change requires 1. Additionally skips mask generation and tile processing when only a single tile is needed.
=> Improve tiling calculations to reduce number of tiles that need to be processed.

comfy/sd.py
https://github.com/comfyanonymous/ComfyUI/issues/5069#issuecomment-2382656368
=> Hotfix for the div zero occurrence when memory_used_encode is 0

comfy/controlnet.py
https://github.com/comfyanonymous/ComfyUI/issues/4888
=> 🐛 Add device to variable c

comfy/ldm/modules/diffusionmodules/mmdit.py
Directly import `optimized_attention` instead of adding another redirect.
=> remove attention abstraction in mmdit

comfy_extras/nodes_sag.py
repeat of #5543, by the one wot originally wrote it
=> arbitrary downscale fix for SAG with Kohya Deep Shrink

app/user_manager.py
Resolves https://github.com/comfyanonymous/ComfyUI/issues/5644
The annotation is only triggered when the API route is called, so the CI did not capture this issue.
=> Fix 3.8 compatibility in user_manager.py

app/user_manager.py
try to start multiple comfyui server at the same time, and this got error
=> fix multi add makedirs error

nodes.py
this patch resolves this:
https://github.com/comfyanonymous/ComfyUI/issues/5813
=> fix: backward compatibility patch for InpaintModelConditioning.encode

comfy/samplers.py
Supplement to https://github.com/comfyanonymous/ComfyUI/pull/5975
=> Add `cond_scale` to `sampler_post_cfg_function`

.github/workflows/ruff.yml, .pylintrc, notebooks/comfyui_colab.ipynb, ruff.toml
Follow-up on https://github.com/comfyanonymous/ComfyUI/pull/5973
This PR replaces pylint with ruff as it is faster and offers more features, such as auto fixing linter errors.
=> Replace pylint with ruff

comfy_extras/nodes_mahiro.py, nodes.py
long explanation of what it is is [here](https://huggingface.co/spaces/yoinked/blue-arxiv) (2024-1208.1) 
note: if the node name has encoding issues (utf 8/whatever), id suggest to replace the face at the end with `(>w<)`
=> Add MaHiRo (improved/alternate CFG)

README.md
This PR adds 2 new keybinding entries available in the frontend.
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1474
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/1365
=> Update README (Add new keybinding entries)

ruff.toml
Refs:
- https://github.com/comfyanonymous/ComfyUI/pull/6028
- https://github.com/comfyanonymous/ComfyUI/pull/6029
- https://github.com/comfyanonymous/ComfyUI/pull/6030
=> Enforce F821 undefined-name

api_server/routes/internal/internal_routes.py, comfy/controlnet.py, comfy/ldm/modules/sub_quadratic_attention.py, comfy/patcher_extension.py, comfy_extras/nodes_clip_sdxl.py, execution.py, notebooks/comfyui_colab.ipynb, ruff.toml, server.py
Depend on https://github.com/comfyanonymous/ComfyUI/pull/6032
=> Enforce all pyflake lint rules

main.py
1. extra_model_paths.yaml
The custom nodes installed in the paths specified in `extra_model_paths.yaml` encounter a bug where the prestartup script is not imported.
The loading of `extra_model_paths.yaml` must take precedence over the prestartup script.
2. Custom path set via CLI
Extend this PR to include [https://github.com/comfyanonymous/ComfyUI/pull/5794](https://github.com/comfyanonymous/ComfyUI/pull/5794).
=> fix: prestartup script is not applied due to `extra_model_paths.yaml` and ensure custom paths are used during startup

comfy_extras/nodes_load_3d.py
I just found use String to set bg color  would be much easierfor this node. 
ThreeJS could handle value direclty, for example, hex value, or color name(red, green, etc)
=> use String directly to set bg color for load 3d canvas

README.md, comfy/model_management.py
Closes: 
1. https://github.com/comfyanonymous/ComfyUI/issues/5420
2. https://github.com/comfyanonymous/ComfyUI/pull/3449
3. https://github.com/comfyanonymous/ComfyUI/pull/5273
This PR was validated on Atlas 800T A2. We need to install the [Ascend Toolkit](https://ascend.github.io/docs/sources/ascend/quick_install.html) first.  Then run:
```
source /usr/local/Ascend/ascend-toolkit/set_env.sh
pip install -r requirements.txt
python main.py
```
We use the default workflow and get the following results:
@YukMingLaw @starmountain1997
=> Support ascend npu

comfy/samplers.py
Different take on #5606, referenced from the original A1111 version: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15608/files
I modified it slightly to ensure the last step is to sigma 0.
Rewritten implementation to avoid license issues. Since the original was like 4 lines, I really doubt that would have been a problem though. See the A1111 pull for reasons why people might want to use this.
=> Add kl_optimal scheduler

comfy/samplers.py
https://github.com/comfyanonymous/ComfyUI/issues/6295
=> Add missing model_options param to finalize_default_conds call

comfy_extras/nodes_load_3d.py
I made two new features, fov and mask for 3d node
here is the demo video
https://github.com/user-attachments/assets/2aa692bd-3a94-4fd7-93dd-bc9031d1f6d9
This BE support for the FE https://github.com/Comfy-Org/ComfyUI_frontend/pull/2116
=> add fov and mask for load 3d node

app/app_settings.py
This PR fixes this issue.
https://github.com/comfyanonymous/ComfyUI/issues/6371
=> fixed: robust loading `comfy.settings.json`

comfy/samplers.py
Title. Ruff doesn't seem to detect this case, but Pylint does.
=> Remove `comfy.samplers` self-import

folder_paths.py
Simplifies code by removing repeat calls to assemble the same path.
=> Remove redundant code from folder_paths

nodes.py
this is a silly little bug that I accidentally left in when I implemented this mode. It's a one line fix.
=> fix a bug in the attn_masked redux code when using weight=1.0

README.md
Changes release schedule from weekly to fortnightly.
=> Update frontend release schedule in README.

README.md, comfy/model_management.py
The PR was validated on Cambricon MLUs. We need to install [CNToolkit](https://www.cambricon.com/docs/sdk_1.15.0/cntoolkit_3.7.2/cntoolkit_install_3.7.2/index.html) first. Then run:
```
pip install -r requirements.txt
python main.py --listen
```
We use the default workflow and get the following results:
=> Support Cambricon MLU

comfy/comfy_types/__init__.py, comfy/comfy_types/node_typing.py, comfy_extras/nodes_audio.py, comfy_extras/nodes_images.py, comfy_extras/nodes_video.py, nodes.py
This PR adds type hint for `FileLocator` dict for node UI output. @webfiltered @yoland68 PTAL
=> Add type hint for FileLocator

app/frontend_management.py
`{sys.executable} -m pip` -> `{sys.executable} -s -m pip`
https://github.com/comfyanonymous/ComfyUI/pull/7047#issuecomment-2697876793
=> fixed: Incorrect guide message for missing frontend.

requirements.txt
- Added node video previews ([[#2635](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2635)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2635))
- Show image size (W x H) on image nodes ([[#2699](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2699)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2699))
- Added tooltip show-delay in action bar ([[#2709](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2709)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2709))
- Replaced colorSelect.png cursor ([[#2738](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2738)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2738))
- Add thumbnails for workflow templates ([[#2729](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2729)](https://github.com/Comfy-Org/ComfyUI_fronten …
=> Update frontend to 1.11.8

comfy_extras/nodes_load_3d.py
Since I move these two params to frontend directly, we don't need them any more.
FE change is https://github.com/Comfy-Org/ComfyUI_frontend/pull/2686
=> [3d] remove unused params

comfy/k_diffusion/sampling.py
Although extra_args won't be None usually, the check for initialization should be done before trying to get the seed.
=> Ensure the extra_args in dpmpp sde series

requirements.txt
- Cherry pick https://github.com/Comfy-Org/ComfyUI_frontend/pull/3065
- [diff](https://github.com/Comfy-Org/ComfyUI_frontend/compare/c988be6b1243dc948c46833f8a1d969a96268a2e...30f7f547f2e42688501c52f880b8197d519a3e77)
- [pypi](https://pypi.org/project/comfyui-frontend-package/1.12.14/)
Fixes https://github.com/comfyanonymous/ComfyUI/issues/7241
=> Update frontend to 1.12.14

requirements.txt
- Added support for Litegraph LinkConnector ([[#2925](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2925)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2925))
- Added custom nodes manager UI ([[#2923](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2923)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2923))
- Added progress spinner on Manager initial load ([[#2936](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2936)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2936))
- Improved mask editor with opacity controls ([[#2955](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2955)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2955))
- Added Vue component multi-select widget ([[#2987](https://github.com/Comfy-Org/ComfyUI_frontend/pull/2987)](https://github.c …
=> Update frontend to 1.13

comfy_extras/nodes_primitive.py, nodes.py
This PR adds backend primitive node implementations for `Int`, `Float`, `String`, and `Boolean` types.
The current frontend-only primitive nodes have two key limitations:
1. **Node inlining in API format**
- When exporting to API format, primitive nodes are removed and values are inlined to node inputs
- This creates a disconnect between UI workflow and API payload
- Developers can't easily determine shared values from the API format alone
Example: From API workflow, it's not obvious that two KSamplers share the same seed value
```json
{
"2": {
"inputs": {
"seed": 0,
"steps": 20,
"cfg": 8,
"sampler_name": "euler",
"scheduler": "normal",
"denoise": 1
},
"class_type": "KSampler",
"_meta": {
"title": "KSampler"
}
},
"3": {
"inputs": {
"seed": 0,
"steps": 20,
"cfg": 8,
"sampler_name": …
```
=> Add backend primitive nodes

requirements.txt
- Added refresh button to workflow sidebar tab ([[#3062](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3062)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3062))
- Improved node pack card design ([[#3089](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3089)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3089))
- Added custom footer component and position props in dialogs ([[#3090](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3090)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3090))
- Improved node pack card header style ([[#3098](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3098)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3098))
- Added progress queue dialog ([[#3091](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3091)](https://github.co …
=> Update frontend to 1.14

comfy_extras/nodes_load_3d.py
BE support for FE change https://github.com/Comfy-Org/ComfyUI_frontend/pull/3122, the demo is 
https://github.com/user-attachments/assets/7c70830d-30ee-48dc-a9ec-47c875eb22aa
=> support output normal and lineart once

requirements.txt
Cherry-pick the fix: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3252
=> Update frontend to 1.14.6

comfy/model_management.py
Add empty MLU cache to model_management.py
=> MLU memory optimization

execution.py, server.py
- Change `resp.node_errors` from `list | dict[NodeId, NodeError]` to `dict[NodeId, NodeError]`
- Change `resp.error` from `string | ErrorDict` to `ErrorDict`
=> Align /prompt response schema

comfy_extras/nodes_hunyuan3d.py
could delete the VoxelToMeshBasic node now probably?
=> add VoxelToMesh node w/ surfacenet meshing

comfy/comfy_types/node_typing.py
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3364
=> Deprecate InputTypeOptions.defaultInput

requirements.txt
- Enable/Disable the drawing of image size [[#3200](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3200)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3200)
- [3d] add support to upload texture [[#3224](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3224)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3224)
- Implement load workflow error dialog in Vue [[#3225](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3225)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3225)
- Report file load error via toast [[#3226](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3226)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3226)
- [i18n] Translate toast messages [[#3228](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3228)](https://github.com/Comfy-Org/ComfyUI_front …
=> Update frontend to 1.15

comfy_extras/nodes_optimalsteps.py, nodes.py
Hello, this is the implementation of the method [OptimalSteps](https://github.com/bebebe666/OptimalSteps), which can accelerate diffusion model sampling significantly, almost without quality loss. The added node "OptimalStepsScheduler" supports the acceleration for text-to-image model FLUX and text-to-video model Wan. Here, we give a demo result of FLUX model with 10 sampling steps:
Here are the example workflows with OptimalSteps for [FLUX-workflow](https://github.com/user-attachments/files/19720395/Flux-Dev-ComfyUI-Workflow.json)  and [Wan-workflow](https://github.com/user-attachments/files/19720398/text_to_video_wan.json).
For more information and results, please visit our [repo](https://github.com/bebebe666/OptimalSteps) and [paper](https://arxiv.org/abs/2503.21774).
=> add OptimalSteps

comfy/comfy_types/node_typing.py
Mark optional TypedDict fields in `node_typing.py` `NotRequired`.
=> [Type] Mark input options NotRequired

app/frontend_management.py, requirements.txt, server.py
Part of https://github.com/Comfy-Org/ComfyUI_frontend/issues/3478. Build workflow templates as a separate PyPi package so templates can be added alongside model implementations without having to also update the frontend.
- https://github.com/Comfy-Org/workflow_templates/pull/29
- https://github.com/comfyanonymous/ComfyUI/pull/7623
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3481
- https://pypi.org/project/comfyui-workflow-templates/0.1.1/
- Includes hidream and wanfun workflow templates
- [[Add tab for outdated node packs](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3255)](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3255)
- [[Preview individual nodes for packs on the registry](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3408)](https://github.com/Comfy-Org/Comf …
=> Update frontend to 1.16 (Install templates as pip package)

comfy_extras/nodes_fresca.py, nodes.py
Implementation of FreSca
https://github.com/WikiChao/FreSca
The node is implemented as a pre-cfg function for better compatibility.
=> Add FreSca node

comfy_execution/graph.py, execution.py
This PR adds type annotation on `get_input_info`, and removes unused vars from callsites.
=> [Type] Annotate graph.get_input_info

requirements.txt
Backports https://github.com/Comfy-Org/ComfyUI_frontend/pull/3505
=> [BugFix] Update frontend to 1.16.9

requirements.txt
Add latest wanfun template workflows: 
https://github.com/Comfy-Org/workflow_templates/commit/35e72bc7132058de8f636506cd7e5995b843189d
=> Add wanfun template workflows.

CODEOWNERS
Adding Christian to CODEOWNERS.
=> Update CODEOWNERS and add christian-byrne

requirements.txt
- Ref: https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.17.10
- Contains bug fixes for API nodes
- Tested in ComfyUI Desktop
=> [BugFix] Update frontend to 1.17.10

requirements.txt
- Includes https://github.com/Comfy-Org/ComfyUI_frontend/pull/3591
- Ref: https://github.com/Comfy-Org/ComfyUI_frontend/releases/tag/v1.17.11
=> [BugFix] Update frontend to 1.17.11

comfy/comfy_types/node_typing.py
Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3550
An associated frontend version has not yet been determined.
=> [NodeDef] Add documentation on widgetType

comfy_extras/nodes_lt.py
This commit adds strength parameter to the LTXVImgToVideo node.
=> ltxv: add strength parameter to conditioning.

comfy_api_nodes/apis/client.py
Fixes https://github.com/comfyanonymous/ComfyUI/issues/7864
=> Fix content moderation not serialized properly bug

requirements.txt
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3596
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3605
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3611
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3615
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3631
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3657
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3597
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3608
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3630
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3692
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3697
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3699
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3543
- …
=> Update frontend to v1.18

main.py
This PR fixes a misleading comment that hasn't been true for at least a couple months now.
=> Fix outdated comment about Internet connectivity

comfy/weight_adapter/boft.py, comfy/weight_adapter/oft.py
The previous implementaion of OFT and BOFT have some bugs inherited from LyCORIS codebase due to some misplaced codes.
This PR fixed them and improve the weight loading for both part to avoid multiple `loaded_keys.add()` for same key.
This PR fixes https://github.com/comfyanonymous/ComfyUI/pull/7876
The BOFT/OFT models for test: https://huggingface.co/NebulaeWis/almond_eye_kohaku_zeta/tree/main/models
=> Fix the bugs in OFT/BOFT moule

comfy_api_nodes/nodes_kling.py
https://github.com/user-attachments/assets/207b1379-9ebb-46fa-ac2d-f06a268666cc
=> Enable kling-v2-master in Kling T2V Node 

comfy_api_nodes/apis/recraft_api.py, comfy_api_nodes/nodes_recraft.py, comfy_extras/nodes_images.py
move the SVG save node and type out of the recraft API nodes and into core
=> move SVG to core

comfy_api_nodes/nodes_ideogram.py, comfy_api_nodes/nodes_kling.py
Updates nodes based on [community feedback](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3792):
- Add validation for input image to avoid sending request that will fail
- Change tooltips to not include terminology only relevant to API
=> Update node tooltips and validation

comfy/k_diffusion/sampling.py
This PR should fix some problems in `res_multistep_ancestral` implementation by making `c2` coefficient respect `sigma_down` from a previous step - previously, it was "fighting" with ancestral noise addition, and that caused many visual artifacts.
=> Fix res_multistep_ancestral and res_multistep_ancestral_cfg_pp sampler

requirements.txt
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3723
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3733
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3741
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3751
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3824
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3710
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3818
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3822
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3241
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3708
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3755
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3765
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3766
- …
=> Update frontend to v1.19

comfy_extras/nodes_load_3d.py
add support to record video for load 3d node, then output it, this BE is for https://github.com/Comfy-Org/ComfyUI_frontend/pull/3749
=> add support to record video as output for 3d node

comfy_extras/nodes_apg.py
re: https://github.com/comfyanonymous/ComfyUI/issues/8026#issuecomment-2877182737
=> fix negative momentum in APG node

comfy/model_detection.py, comfy/supported_models.py, comfy_extras/nodes_camera_trajectory.py
More robust model detection for future proofing.
=> Fix typo in last PR.

README.md
=> Update README ROCm text to match link

comfy/ldm/chroma/layers.py
Reverts comfyanonymous/ComfyUI#8209
This didn't work consistently at all.
=> Revert "This doesn't seem to be needed on chroma."

requirements.txt
New templates:
- Lotus Depth
- Wan VACE t2v
- Wan VACE i2v
- Wan VACE v2v
- Wan VACE outpainting
- Wan VACE flf2v
https://github.com/Comfy-Org/workflow_templates/pull/56
https://github.com/Comfy-Org/workflow_templates/pull/58
=> Update templates to 0.1.18

requirements.txt
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3851
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3924
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3880
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3907
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3603
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3639
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3950
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3876
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3933
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3878
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3928
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3945
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3946
- …
=> Update frontend to 1.20

comfy_extras/nodes_load_3d.py
should not include mtl file in support, it will be loaded automatically
=> remove mtl from 3d model file list

requirements.txt
Include cherry picked commits that make small fixes to 3D nodes in preparation for new 3D nodes being released:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3965
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3967
---
- pypi: https://pypi.org/project/comfyui-frontend-package/1.20.5/
- patch diff: https://github.com/Comfy-Org/ComfyUI_frontend/compare/0095f02f463a8d1e961c6a3c65ab018b5d461f4a...core/1.20
---
Fixes https://github.com/Comfy-Org/ComfyUI_frontend/issues/3970
Fixes https://github.com/Comfy-Org/ComfyUI_frontend/issues/3972
---
=> Update frontend to v1.20.5 (patch)

requirements.txt
Include cherry picked commit https://github.com/Comfy-Org/ComfyUI_frontend/pull/4004 to fix [this bug with API nodes](https://github.com/Comfy-Org/ComfyUI_frontend/issues/4001).
- pypi: https://pypi.org/project/comfyui-frontend-package/1.20.7/
- patch diff: https://github.com/Comfy-Org/ComfyUI_frontend/pull/4004/files
=> Update frontend to v1.20.7 (patch)

comfy_api_nodes/nodes_pika.py
Added unique_id to hidden parameters and corrected description formatting in PikAdditionsNode.
=> Refactor Pika API node imports and fix unique_id issue.

comfy_api_nodes/nodes_veo2.py
Reverts comfyanonymous/ComfyUI#8320
=> Revert "Add support for Veo3 API node."

requirements.txt
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3079
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3958
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3953
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4022
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4024
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4000
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3954
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4008
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3952
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3961
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3965
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4009
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3975
- …
=> Update frontend to 1.21

requirements.txt
- Resolves #8381
- Resolves #8375
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4048
- Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/4049
=> [BugFix] Update frontend to 1.21.5

comfy/model_management.py
Information is from the pytorch source code.
=> Enable AMD fp8 and pytorch attention on some GPUs.

requirements.txt
* [Fix: multiple loras template missing widgets_values on 2nd Lora Loader node #74](https://github.com/Comfy-Org/workflow_templates/pull/74)
* [Chroma template](https://github.com/Comfy-Org/workflow_templates/pull/76)
* [Wan Fun Camera 1.3B & 14B](https://github.com/Comfy-Org/workflow_templates/pull/82)
* 
- [Update template thumbnails](https://github.com/Comfy-Org/workflow_templates/pull/79) 
Added a logo to each thumbnail to make sure all the templates look more consistent and easy to recognize.
=> Update template to 0.1.27

comfy_extras/nodes_model_advanced.py
This is for the cosmos predict2 model.
=> Add cosmos_rflow option to ModelSamplingContinuousEDM node.

requirements.txt
https://pypi.org/project/comfyui-embedded-docs/0.2.2/#history
The following documents have been updated with the latest version code, and the Russian version has been added. The parameters and names in each document are kept consistent with the localization of ComfyUI instead of only using English.
- ClipTextEncoderFlux - Updated documentation
(https://github.com/Comfy-Org/embedded-docs/pull/26)
- ClipTextEncode - Updated documentation
(https://github.com/Comfy-Org/embedded-docs/pull/24)
- ClipSetLastLayer - Updated documentation
(https://github.com/Comfy-Org/embedded-docs/pull/23)
- ClipSave - Updated documentation 
(https://github.com/Comfy-Org/embedded-docs/pull/22)
- ClipMergeSimple - Updated documentation
(https://github.com/Comfy-Org/embedded-docs/pull/21)
- ClipLoader - Updated …
=> Bump embedded docs to 0.2.2

comfy/model_base.py, comfy/model_detection.py, comfy_extras/nodes_cosmos.py
Use the CosmosPredict2ImageToVideoLatent node.
=> Support Cosmos predict2 image to video models.

comfy/k_diffusion/sampling.py
Using the same approach as in #8529. 
Additionally, this PR slightly unifies the style between 2M and 3M.  
It doesn't include `dpmpp_sde` since that implementation is based on ancestral sampling.
In general, this `dpmpp_2m_sde` with `eta=0` leads to less aggressive results compared to the current `dpmpp_2m` in RF, because its weighting factor `1/r` is smaller.
SD 3.5 medium, CFG=4.0 and sgm_uniform.
=> Multistep DPM++ SDE samplers for RF

requirements.txt
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3922
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3931
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3963
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4065
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4066
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4074
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4095
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4141
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4021
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4079
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4039
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4070
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4099
- …
=> Update frontend to 1.22.2

comfy_extras/nodes_perpneg.py
Resolve #8685. 
PerpNegGuider has its own `post_cfg_function` handler, so it missed the update to `args`. This PR not only updates the `args` of `post_cfg` but also adds `pre_cfg` here.
=> Perpneg guider with updated pre and post-cfg

comfy_api/v3/io.py, comfy_api/v3/resources.py, comfy_api/v3/ui.py, comfy_extras/nodes_v3_test.py, execution.py
Resources:
- Resources that are to be cached between runs can be obtained via cls.resources in execution of functions; TorchDictFolderFilename resource key was added to request torch dict files via folder and filename, how it is currently done. Code is in v3/resources.py
Preview Helper:
- PreviewImage and PreviewMask classes that take care of creating temporary files for the purpose of showing preview in nodes. Code is in v3/ui.py
=> V3 definition update - Resource management + Preview helper

requirements.txt
##Templates
https://pypi.org/project/comfyui-workflow-templates/0.1.33/
**New templates**
**fixed some  issues**
- https://github.com/Comfy-Org/workflow_templates/pull/113
- https://github.com/Comfy-Org/workflow_templates/pull/112
https://pypi.org/project/comfyui-embedded-docs/0.2.4/
Refine some old node documentation.
=> Update template and node docs package version

comfy/ldm/chroma/model.py
In preparation for improved/alternate VAE for Chroma (more details from lodestone forthcoming).
=> Un-hardcode Chroma patch_size

comfy_api/v3/io.py, comfy_api/v3/resources.py, comfy_api/v3/ui.py, comfy_extras/nodes_v1_test.py, comfy_extras/nodes_v3_test.py, execution.py
Fixes:
- Fix NotRequired import
- Fix MultiCombo not working
Additions:
- Add force_input to WidgetInputs
- Add validate_inputs function support (v3's VALIDATE_INPUTS)
- Add fingerprint_inputs function support (v3's IS_CHANGED)
- Add check_lazy_status function support
- Add finalize() to SchemaV3 so that certain schema toggles can automatically add needed hidden variables
- Add node as optional input into ui.PreviewImage so that metadata can be stored
Mocking (to be removed/edited once done testing):
- Mock N Inputs dynamic input type
=> V3 definition update - misc fixes, function additions, and dynamic inputs mock

comfy_extras/v3/nodes_controlnet.py, nodes.py
Fully converted `nodes_controlnet.py` file with 2 nodes, and put in it also the `ControlNetApplyAdvanced` node from `nodes.py` file.
Totally 3 nodes.
=> [V3]  ControlNet nodes

comfy/supported_models.py
https://github.com/comfyanonymous/ComfyUI/issues/8907
=> Fix wrong reference bug

requirements.txt
- https://github.com/Comfy-Org/workflow_templates/pull/133
- https://github.com/Comfy-Org/workflow_templates/pull/134
-  https://github.com/Comfy-Org/workflow_templates/pull/135
=> Update template to 0.1.37

requirements.txt
https://pypi.org/project/comfyui-workflow-templates/0.1.39/
- Add HiDream E1.1 template
=> Update template to 0.1.39

comfy/weight_adapter/__init__.py, comfy/weight_adapter/base.py, comfy/weight_adapter/loha.py, comfy/weight_adapter/lokr.py, comfy/weight_adapter/oft.py, comfy_extras/nodes_train.py
As title, this PR propose following updates of lora training node:
1. support algorithm selection (currently support LoRA/LoHa/LoKr/OFT)
2. support optional gradient checkpointing #8668
3. support gradient accumulation for simulating large batch size
=> [Training Node] algo support, grad acc, optional grad ckpt

requirements.txt
Add Wan ATI template
https://pypi.org/project/comfyui-workflow-templates/0.1.40/
=> Update template to 0.1.40

comfy/ldm/qwen_image/model.py, comfy/model_base.py, comfy/model_detection.py, comfy/sd.py, comfy/supported_models.py, comfy/text_encoders/llama.py, comfy/text_encoders/qwen_image.py, nodes.py
Model files: https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI
=> Initial support for qwen image model.

comfy_api/latest/_ui.py
Per @mcmonkey4eva 's comment, added safety check around torchaudio import in _ui.py.
=> _ui.py import torchaudio safety check

requirements.txt
https://pypi.org/project/comfyui-workflow-templates/0.1.58/
1. Wan2.2 fun inp 14B
[video_wan2_2_14B_fun_inpaint.json](https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/video_wan2_2_14B_fun_inpaint.json)
2. Added lightx2v 4 steps lora to wan2.2 flf2v workflow
[video_wan2_2_14B_flf2v.json](https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/video_wan2_2_14B_flf2v.json)
=> Update template to 0.1.58

comfy_api/latest/_ui.py
Per mcmonkey's feedback to account for errors thrown by different torch versions like Windows DirectML: https://github.com/comfyanonymous/ComfyUI/pull/9234#discussion_r2264159892
=> Make torchaudio exception catching less specific

comfy_extras/nodes_wan.py
This PR contains only the **minimal changes** and targets **master** branch.
Nodes were tested after conversion on the `WAN 2.2` txt2video and img2video official workflows.
=> convert WAN nodes to V3 schema

comfy/ldm/wan/model.py, comfy/model_detection.py, comfy/supported_models.py, comfy_extras/nodes_wan.py
Use the old WanCameraImageToVideo node.
=> Implement wan2.2 camera model.

requirements.txt
Bump frontend to 1.25.8
```
python main.py --front-end-version Comfy-Org/ComfyUI_frontend@1.25.8
```
- Diff: [Comfy-Org/ComfyUI_frontend: v1.24.4...v1.25.8](https://github.com/Comfy-Org/ComfyUI_frontend/compare/v1.24.4...v1.25.8)
- PyPI Package: https://pypi.org/project/comfyui-frontend-package/1.25.8/
- npm Types: https://www.npmjs.com/package/@comfyorg/comfyui-frontend-types/v/1.25.8
- Restored ability to use group nodes. Based on feedback, will provide smoother transition with option to automatically convert to subgraph.
- Added ability to unpack a subgraph ("convert back to nodes")
- Added sampling previews onto subgraph nodes automatically
- Added configurable hotkey for exiting subgraphs
- Detect missing nodes inside subgraph for easier install with Manager
- Improved subgraph I/O …
=> Update frontend to v1.25.8

requirements.txt
https://pypi.org/project/comfyui-workflow-templates/0.1.60/
[video_wan2_2_14B_fun_camera.json](https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/tags/v0.1.60/templates/video_wan2_2_14B_fun_camera.json)
Also included is the workflow using lightv2x lora and the original one in the same template.
=> Update template to 0.1.60

comfy/context_windows.py
Matching exact tensor value may not work depending on the workflow, and the tolerance for isclose has to be 0.0001 to work.
=> Make context step index detection much more robust

comfy_api_nodes/nodes_openai.py
Frontend part: https://github.com/Comfy-Org/ComfyUI_frontend/pull/4958
=> api_nodes: add GPT-5 series models

comfy/ldm/qwen_image/model.py, comfy/model_management.py, comfy/model_patcher.py, comfy_api/latest/_io.py, comfy_extras/nodes_model_patch.py, nodes.py
These are not real controlnets but actually a patch on the model so they will be treated as such.
Put them in the models/model_patches/ folder.
=> Support for Qwen Diffsynth Controlnets canny and depth.

comfy_api_nodes/nodes_ideogram.py
Nodes were tested after conversion, behavior or any inputs were not changed compared to V1 version.
=> [V3] convert Ideogram API nodes to the V3 schema

comfy/controlnet.py, comfy/ldm/qwen_image/controlnet.py
These are normal controlnets, use them like normal controlnets. Not released yet.
=> Support InstantX Qwen controlnet.

comfy/audio_encoders/audio_encoders.py, comfy/audio_encoders/wav2vec2.py, comfy_api/latest/_io.py, comfy_extras/nodes_audio_encoder.py, nodes.py
This is useless on its own but there are multiple models that use it.
=> Implement wav2vec2 as an audio encoder model.

requirements.txt
Add Google gemini image template
https://pypi.org/project/comfyui-workflow-templates/0.1.68/
[api_google_gemini_image.json](https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/api_google_gemini_image.json)
=> Update template to 0.1.68

comfy/model_base.py, comfy_extras/nodes_wan.py
Use the Wan22FunControlToVideo node.
=> Support wan2.2 5B fun control model.

comfy_extras/nodes_video.py
V3 nodes test:
V1 nodes test:
---
I found only only one repo that import `SaveVideo` node:
https://github.com/bentoml/comfy-pack/blob/22114ebfa6052451434bd081fcc0e980adab8f00/nodes/nodes.py#L482-L488
=> [V3] convert Video nodes to V3 schema

comfy_api_nodes/nodes_stability.py
Everything has been checked, everything works, no changes in behavior have been made compared to V1.
=> [V3] convert nodes_stability.py to V3 schema

comfy_extras/nodes_primitive.py
This PR targets **master** branch.
=> convert Primitive nodes to V3 schema

comfy/clip_model.py, comfy/clip_vision.py, comfy/ldm/flux/model.py, comfy/model_patcher.py, comfy_extras/nodes_model_patch.py
Load the USO projector.safetensors file with the ModelPatchLoader node and use the siglip_vision_patch14_384.safetensors "clip vision" model and the USOStyleReferenceNode.
=> USO style reference.

comfy_api_nodes/nodes_bytedance.py
Frontend part: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5336
Showcase:
https://github.com/user-attachments/assets/7f3cdc49-58f3-4473-821a-87fb135ffd53
=>  API nodes: add ByteDance video

requirements.txt
This template update relies on this PR https://github.com/comfyanonymous/ComfyUI/pull/9749
https://pypi.org/project/comfyui-workflow-templates/0.1.76/
=> Update template to 0.1.76

requirements.txt
Relies on this PR https://github.com/comfyanonymous/ComfyUI/pull/9802
https://pypi.org/project/comfyui-workflow-templates/0.1.78/
[api_bytedance_seedream4.json](https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/api_bytedance_seedream4.json)
=> Update template to 0.1.78

comfy/audio_encoders/audio_encoders.py, comfy/audio_encoders/whisper.py
Not useful yet but some models use it.
=> Add encoder part of whisper large v3 as an audio encoder model.

comfy/supported_models.py
Previous pr reduced the peak memory requirement.
=> Lower wan memory estimation value a bit.

CODEOWNERS
Updated CODEOWNERS to include @kosinkadink as a code owner.
=> Add @kosinkadink as code owner

comfy_api_nodes/nodes_bfl.py
=> [V3] convert nodes_bfl.py to V3 schema

comfy_api_nodes/nodes_luma.py
Workflow with all nodes were created with V1 version and successfully executed in the V3 version to ensure that nothing is broken:
https://github.com/user-attachments/assets/8ce95238-2cd7-455d-a457-93795b7803be
=> [V3] convert nodes_luma.py to V3 schema

comfy_extras/nodes_lotus.py
Git diff:
```
index 8b91fa8..1675f54 100644
@@ -25209,18 +25209,12 @@
"conditioning"
],
-        ],
"name": "LotusConditioning",
+        "display_name": "LotusConditioning",
"python_module": "comfy_extras.nodes_lotus",
"category": "conditioning/lotus",
-        "api_node": false
+        "output_node": false
},
"EmptyLatentHunyuan3Dv2": {
"input": {
```
=> [V3] convert nodes_lotus.py to V3 schema

comfy_extras/nodes_lumina2.py
Git diff:
```
index 9f43e32..9e298ca 100644
@@ -23457,22 +23457,20 @@
"input": {
"required": {
"system_prompt": [
-                    "COMBO",
+                    [
+                        "superior",
+                        "alignment"
+                    ],
{
-                        "tooltip": "Lumina2 provide two types of system prompts:Superior: You are an assistant designed to generate superior images with the superior degree of image-text alignment based on textual prompts or user prompts. Alignment: You are an assistant designed to generate high-quality images with the highest degree of image-text alignment based on textual …
```
=> [V3] convert nodes_lumina2.py to V3 schema

requirements.txt
Fix borken model link in Wan2.2 animate template: https://github.com/Comfy-Org/workflow_templates/pull/211
Fix Wan2.2 t2v template issue: https://github.com/Comfy-Org/workflow_templates/issues/194
=> Update template to 0.1.91

comfy_api_nodes/nodes_wan.py
Frontend PR with pricing was already merged: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5829
=> feat(api-nodes): add WanImageToImageApi node

comfy_api_nodes/nodes_bytedance.py
Frontend already correctly displays pricing for this.
https://github.com/user-attachments/assets/07855eab-670a-409d-8f73-6b4b5d29c858
=> feat(api-nodes): enable Seedance Pro model in the FirstLastFrame node

requirements.txt
https://pypi.org/project/comfyui-workflow-templates/0.1.93/
https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/video_wan2.1_alpha_t2v_14B.json
https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/api_wan_text_to_image.json
https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/api_bytedance_text_to_video.json
https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/api_bytedance_image_to_video.json
https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/api_bytedance_flf2v.json
=> Update template to 0.1.93

requirements.txt
https://pypi.org/project/comfyui-workflow-templates/0.1.94/ 
https://raw.githubusercontent.com/Comfy-Org/workflow_templates/refs/heads/main/templates/api_openai_sora_video.json
https://github.com/Comfy-Org/workflow_templates/pull/221
=> update template to 0.1.94
