comfyanonymous/ComfyUI

nodes.py

Checkpoints, configs, VAEs, LoRAs and clip model directories are now recursively searched across all operating systems, allowing for the use of subdirectories and symlinked subdirectories.

add recursive listing of models

---

main.py
requirements.txt
webshit/index.html

As discussed, implemented WebSockets to replace the current polling.
I was going to move the classes out to separate files, but for ease of reviewing i've left them in main but it might be worth you splitting them out

Replace Http Server + Add WebSockets

---

main.py

Triton doesnt work on Windows so this hides the error, I've seen a few people asking about it

Hide Triton warning on Windows

---

nodes.py
webshit/index.html

This add basic dynamic prompting to any text widget declared with `"dynamic_prompt": True`. For now, only the `CLIPTextEncode` is declared as such. 
The syntax `{value_A|value_B|value_C}` will result in one value being randomly picked for the prompt. 
The image generated will have the actual prompt embedded, not the dynamic syntax. So if you drag&drop a generated image in the webui you will get `value_B` for example.
This does not break compatibility with previous workflows.

feature : basic dynamic prompting

---

execution.py
server.py
web/scripts/api.js

Client will reuse the same id for the lifetime of the tab
Server stores last executing node and will send to client on connect allowing it to display active node/progress

Updated to reuse session id if available

---

web/extensions/core/invertMenuScrolling.js
web/scripts/ui.js
web/style.css

Adds a simple dialog for settings
Adds an option for inverting mouse scrolling on context menus (e.g. lora dropdown) addressing half of #46

Added settings dialog + setting to invert menu scrolling

---

main.py
nodes.py
server.py
web/scripts/app.js

Added temp directory with cleanup on start + exit
use_temp_file yes/no widget on SaveImage
Ability for viewing temp files
Combo widgets can have default values (use temp defaults to no)

Save image temp dir

---

server.py
web/scripts/api.js
web/scripts/app.js
web/scripts/pnginfo.js

Adds endpoint for getting embeddings
Supports importing images created in automatic1111 web-ui
- Model, Clip Skip
- HR fix (latent + model)
- LORAs 
- Embeddings
- Other normal sampler settings
Gives a good starting point for quickly getting up and running with old prompts

A1111 png metadata import

---

web/extensions/core/rerouteNode.js
web/scripts/app.js

Allows connecting reroute nodes together before adding an input
Provides type info if only an output is connected but is still changeable to a different type
Supports node colors
Prevents collapsing node
Fix bug with virtual nodes and simplify code - by someanon

Reroute rewrite

---

web/scripts/widgets.js

If the node is offscreen when it's created, no initial resize event is fired so the widgets don't get their sizes calculated.
This runs the size calculations on draw if there is no size set

Calc sizes on draw

---

server.py

When you open an image in a new tab, the browser will treat it as though it has an actual filename rather than "view" when you download it

Add content disposition header so images have name

---

web/index.html
web/lib/litegraph.core.js

- Added correct meta tags to index.html - head
- Changed litegraph.core.js - pointerevents_method: "pointer"  
This should not negatively affect desktop browsers, since pointer events are supported in most modern browsers. https://caniuse.com/pointer
- Litegraph's double click events are handled even using non-primary pointer.
- Changed setting to not close dialogs on mouseleave.
Current state:
- Can move around canvas
- Right click by tapping with two fingers  
(Hint: can tap with the second finger later.)
- Can type in conditions
- Double tap to bring search box up  
(Hint: tap somewhere around top-right on the screen so it will be shown while typing.)
- Tapping input fields opens them like normal, can type in them.
Further work:
- Zooming is not implemented yet, maybe some touch …

Initial mobile support

---

web/extensions/core/widgetInputs.js
web/jsconfig.json
web/scripts/app.js
web/scripts/widgets.js

Adds convert options to the node menu
And once converted, convert back
New primitive node that can be connected to one of these inputs
When connected it will copy the current value, numbers will be given a random toggle so it can be used for seeds
Links are restricted by type + widget configuration (e.g. you cant connect the same Primitive to seed and width, as width is restricted to steps of 64)
Primitives can be linked to multiple nodes to allow sharing of values
Values are sync'd to the source node, meaning things like LoadImage display the correct value
For now it supports text, numbers and combos but can easily be updated to support anything else
To quickly add a primitive widget you can double click the input (the circle, not the label)
If anyone has any feedback / could give this …

Convert widget to input (and back)

---

nodes.py

This node will create transparent paddings to existed image and generate correct mask.
Now, users can do outpaint in pipeline directly

feat: Add ImagePadForOutpaint

---

web/scripts/app.js

This PR set the color of slots by type, so you can see what connects where without dragging the connection.
P.S.: colors created by chat GPT to be distinguishable, if it was a bad choice of colors blame the chat GPT 😁

Slot colors by type

---

nodes.py
server.py

The `realpath()` expands symbolic links, this PR changes it to `abspath()`, because it preserves the symbolic links, allowing the output folder to be a symbolic link pointing to a folder outside the ComfyUI folder.

Allow output folder to be a symbolic link

---

web/scripts/app.js

I am by no means an color expert, but the current slot colors are (in my opinion) not very visually pleasing. I've changed them to be a bit more consistent.

change slot colors to a more consistent palette

---

web/scripts/ui.js
web/style.css

This PR makes possible to drag the menu.
The menu starts in the original position and can be dragged by the handle on the top left corner.
The position is not saved, it is just to move the menu to see the node that is behind it, the position resets on page refresh.

Draggable menu

---

nodes.py

Allows users to set the filename prefix of the SaveImage node to something like this : `PR/%width%x%height%/ComfyUI`

%width% and %height% wildcards for filepath

---

server.py
web/scripts/app.js

This PR adds a optional RETURN_NAMES attribute to return the outputs names.
It is needed for nodes that return multiple outputs with same type, or with primitive types (now that we have the widget to input) to set a better name instead of the type.

Optional RETURN_NAMES to set the output name

---

web/scripts/app.js

This PR adds a header draw on groups and restricts the drag action on groups to the header area.
It solves the issue #175

Move group by header

---

comfy/model_management.py

Do not set the vRAM state to `lowvram`/`highvram` if the `--cpu` argument is passed (CPU only).

no lowvram state if cpu only

---

web/extensions/core/colorPalette.js
web/scripts/app.js
web/scripts/ui.js
web/style.css

This PR adds a frontend setting for color palette.
Currently it only changes the node slot colors, but can be extended to set other colors too.
You can choose between the built-in palettes or download the template to make you color palette and import it, you can also export a palette and delete custom palettes that you imported.
This solves the issue discussed here #268

Color palette setting

---

web/scripts/app.js
web/scripts/ui.js

Clean `nodeOutputs` when loading another workflow to make sure previous images are not rendered anymore.

clean state when loading another workflow

---

web/extensions/core/saveImageExtraOutput.js

This allows you to use any widget value as a replacement in the SaveImage output name
Search and replace is done in the format `%node.widgetname%`  
where `node` is a node S&R property name or a node title  
e.g. to output the model name: `%CheckpointLoaderSimple.ckpt_name%`  
To allow for shorter names or duplicates, you can either use the change node title and use that or right click any node -> Properties -> Node name for S&R  
Dates are usable by using `%date:FORMAT%`, it handles
`d` and `dd` for day of month (dd with leading zero)
`M` and `MM` for month of year
`yy` and `yyyy` for year
`h` and `hh` for hour
`m` and `mm` for minute
`s` and `ss` for second
e.g. `%date:yyyy-MM-ddThh-mm-ss%` -> `2023-03-29T01-02-03`

Extra formatting values on SaveImage

---

web/style.css

The original `margin-top: -70px` rule would behave weirdly when resizing the window. The new rule turns the menu into a sidebar instead if the screen size is smaller than 850px in height (minimized window, laptop screen, etc).
As this is a media query rule, it doesn't break the position set on the element by the javascript. Maximizing the window should restore the original position automatically.

Turn comfy-menu into a sidebar on small screens

---

web/scripts/ui.js

loadGraphData clears nodeOutputs
This swaps the order so it populates the outputs after loading

Fix loading history outputs

---

web/scripts/app.js

When the default graph is changed in UI, it is also mutating the defaultGraph object so if you reload it it doesnt undo all of the changes

Clone default graph before using

---

main.py
nodes.py
server.py

This adds the ability for custom nodes to add routes to the server.
It moves the loading of custom nodes to after the initial creation of the server so additional routes can be added
---
Example:
```py
@PromptServer.instance.routes.get("/hello")
async def get_hello(request):
return web.json_response("hello")
```
```py
async def get_world(request):
return web.json_response("world")
PromptServer.instance.app.add_routes([
web.get("/world", get_world)
])
```

Custom API routes

---

web/extensions/core/rerouteNode.js

ISSUE:
Currently, if one connects reroutes in a circle, the client will get stuck in an infinite loop, while trying to find the root input.
FIX:
Detect the circle and disconnecting the link.

fix client freeze on connect reroutes in a circle

---

web/scripts/app.js

If you hit the queue button before the previous queue action has finished (e.g. set queue count to 10, then double click), seeds will not be randomised for each prompt
This moves each click of the button to push onto a queue that is then processed sequentially ensuring each graph correctly runs afterQueued

Added a queue for the queue action

---

web/extensions/core/snapToGrid.js
web/scripts/app.js
web/scripts/ui.js

For #335
Hold shift when dragging/resizing nodes to align them to a grid
Adds a setting to control the size of the grid (and support for numeric settings, tooltips, extra attrs)
When dragging shows a "shadow" where the node will go
The nodes dont align with the background canvas grid as litegraph just renders a static PNG for the background

Snap to grid when dragging & resizing nodes

---

web/extensions/core/slotDefaults.js
web/scripts/app.js

Adds simple basics for slot default node types that you can quickly create using middle click on the node input/output.
This can be configured on a per-node basis, but for starters I think these are a few OK defaults and can be refined over time
Enables `release_link_on_empty_shows_menu` - when you drag a link to an empty space it allows you to add a node
`alt_drag_do_clone_nodes` - alt+drag clones the node

Adds middle click for default node creation and enable features

---

web/extensions/core/widgetInputs.js

If "filename_prefix" widget is converted to an input, SaveImage's `widget.serializeValue()` is ignored and the extra replacements (`%node.widget%` and `%date:format%`) is not done.  This PR fixes it.

Fix "extra filename replacements in SaveImage is not done when prefix is supplied by Primitive".

---

comfy_extras/nodes_post_processing.py
nodes.py

Split from #336, `Blend, Blur, Dither, Sharpen` are pure torch nodes which implement simple image processing operations. 
`Blur` and `Sharpen` are simple 2d convolutions with basic kernels (torch allows us to batch these in 4d), `Blend` is blending two images with various modes* too limit reimplementation (references can be found [here](https://en.wikipedia.org/wiki/Blend_modes)), and `Dither` implements Floyd-Steinberg Dithering.
*Note that there a ton of different blend modes, and I did not add any of the Dodge and Burn modes or arithmetic modes. The arithmetic modes and dodge and burn modes are not as common imo, and should be a separate node as too many options would confuse the user.

Adds Blend, Blur, Dither, Sharpen nodes

---

web/scripts/app.js

Simple quality-of-life improvement. When a node has images, if one is selected, the left/right arrow keys can be used to move to the next/previous images and escape can be used to go back to the overview.

Add left/right/escape hotkeys for image nodes

---

comfy/cli_args.py
comfy/ldm/modules/attention.py
comfy/model_management.py
main.py

`argparse` is generally much more maintainable and easier to use to parse in args as it provides a lot of useful features. This pr aims to switch it to that.
Some notes
- These arguments are in `cli_args.py` and not main because we will likely be using the args in multiple positions, and modules are effectively singletons, so it is easier to import it out of there. 
- Currently we are using it `main`, `model_management` and `attention` and `model_management` is imported in several different places. Theoretically we could wrap `model_management` in a class, and create it in `main`, but then we would have to do singleton management anyway wherever `model_management` is imported.
- TL;DR; It is what [auto does](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/cmd_ar …

Switches argparsing to use argparse library

---

comfy/cli_args.py
server.py

Should resolve #397. I did check myself, but @space-nuko you might to test it to double check.
One thing though is perhaps maybe make the `response.headers['Access-Control-Allow-Origin']` a parameter instead? I don't know how safe it is/isn't to allow all.

Add CORS middleware (allows for cross origin requests)

---

comfy/cli_args.py
main.py

When converting to argparse, I forgot to correctly convert `--extra-model-paths-config` as it previously it supported
`python main.py --extra-model-paths-config extra_model_paths.yaml --extra-model-paths-config second_model_paths.yaml`
It now once again supports that. It also now supports
`python main.py --extra-model-paths-config extra_model_paths.yaml second_model_paths.yaml`
as well and yields the exact same results. Args can still be specified before and after it.
Edit: Adds some metavars to argparse which makes help message more informative. Previously `python main.py -h` shows
```
...
--listen [LISTEN]     Specify the IP address to listen on (default: 127.0.0.1). If --listen is provided without an 
--enable-cors-header [ENABLE_CORS_HEADER]
--cuda-device CUDA_DEVICE
...
```
now it …

Fixes lack of support for multi configs

---

comfy/model_management.py
requirements.txt

closed #387 
need to install the [oneAPI Base Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html) first, on Arch Linux it is `paru -S intel-oneapi-basekit intel-compute-runtime-bin`
> Use AUR's `intel-compute-runtime-bin` instead of `intel-compute-runtime` to avoid the `Assertion '__n < this->size()' failed.` error
Maybe it also depends on the [oneAPI AI Analytics Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/ai-analytics-toolkit.html), I'm not sure
Then run:
```bash
source /opt/intel/oneapi/setvars.sh
pip install torch==1.13.0a0 torchvision==0.14.1a0 intel_extension_for_pytorch==1.13.10+xpu -f https://developer.intel.com/ipex-whl-stable-xpu
pip install -r requirements.txt
python main.py --use-split-cross-attention
```
If …

Basic support for Intel XPU (Arc Graphics)

---

custom_nodes/example_node.py.example
nodes.py
server.py
web/scripts/app.js

This PR tries to do something similar to the second part of #285 - except using a separate lookup dict and a new field for the names.
Probably not the best solution since extensions/new modules just display as the old base name anyway. Apart from that, the category name is left unchanged.
(It might be possible to loading these strings from one or more json files or doing a second conversion client side to solve those issues)

Add human-readable names for nodes

---

web/scripts/pnginfo.js

This PR fixes exception when importing large workflows from images. Example:
```
pnginfo.js:36 Uncaught RangeError: Maximum call stack size exceeded
```

Fix large workflow pnginfo import

---

web/extensions/core/nodeTemplates.js
web/scripts/ui.js
web/style.css

Adds canvas menu option for Node Templates
These are collections of nodes that you can save and add for standard building blocks
Manage dialog allows renaming and removing
Menu item for saving shows but is disabled when no nodes are selected for easier discoverability for how to use

Node templates

---

web/scripts/app.js

Simple warning that shows when you load a graph with nodes you dont have registered

Adds warning when loading graph with nodes you dont have

---

web/scripts/app.js

Add some error handling around the graph configure call
Tries to extract the filename from the error to give a hint of what the cause might be.
My test extension that just throws when reloaded:
```
import { app } from "/scripts/app.js";
app.registerExtension({
name: "I.DoAnError",
registerCustomNodes() {
class DoAnError {
onConfigure() {
throw new Error("boom");
}
}
LiteGraph.registerNodeType("DoAnError", DoAnError);
DoAnError.category = "DoAnError";
},
});
```

Catch configure errors

---

web/style.css

I know the blue border already indicates this, I just think adding an arrow is more standard makes it clearer which items have submenus

Add arrow to menu items with submenus

---

nodes.py

Checks, if input image is RGBA. If not, converts it.

make LoadImagesMask work with non RGBA images

---

web/extensions/core/saveImageExtraOutput.js

Search and replace values still support searching by the node title, but the property will now default to the node class name.

Changed default name to be the node type not title

---

web/extensions/core/colorPalette.js
web/style.css

Missed this in #481, comfy-list was not styled so history and queue were not. Also, Light theme has a bad border color as seen in the history image below since it blends with background.
Previous:
Now:

Fixes comfy list not being styled

---

web/extensions/core/widgetInputs.js

Currently if you convert a combo to an input and double click the input to get a primitive node, it doesnt work
This fixes that

Fix double click on converted combo widget link

---

comfy/sd.py
comfy/sd1_clip.py
nodes.py

Does the following:
reworks the `tokenize_with_weights` function to instead return triplets (token, weight, word_id) where word_id is a unique number per word/embedding. I'm slightly paranoid about long embeddings as I basically rewrote the entire function, so maybe some more testing is in order.
splits up the tokenizing and encoding into two different functions so that custom nodes can put themselves in-between this process without duplicating code.
This PR makes it possible to for instance do the things in [this](https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb) repo

changes tokenization/encoding to make it easier to manipulate tokens, weights and embeddings

---

web/extensions/core/keybinds.js

This allows you to do "tweak prompt, queue, tweak prompt, queue, tweak prompt, queue,..."

Fix "Ctrl+Enter doesn't work when textarea has focus" regression introduced in #491.

---

web/extensions/core/editAttention.js

I thought someone in #485 would have re-implemented it by now, but since I have been using the AdvancedClip Node recently I really desire this back.
I did it by myself, but it should still have all the same functionality.

Allows control arrow to edit attention in textarea

---

web/extensions/core/snapToGrid.js
web/scripts/ui.js
web/style.css

Allows creating settings with `type: "slider"`

Add slider input for settings

---

web/extensions/core/editAttention.js

Remove a console.log, my bad.
Also now, this is a new feature similar to how previously it finds the current enclosure if there is no selection, it also now attempts to find the current word.
You don't even have to highlight a word anymore as previously you had to highlight a single word to give it the initial attention braces. Now it automatically tries to find the immediate word.

Selects current word automatically

---

web/extensions/core/editAttention.js

It currently assumes that words are always separated by spaces, but that's not necessarily the case. For instance, I'm sure you've seen prompts with `commas,but not spaces,like this`, in which case `commas,but` and `spaces,like` each are treated as one word.
This way simply seeks forwards and backwards until it finds a delimiter.

Improve current word selection

---

web/scripts/api.js

Prevents "Duplicate Tab" stealing session id, fixes #549
I've tested with Firefox, Chrome, Colab local tunnel

Use window.name instead of session storage

---

execution.py
folder_paths.py
nodes.py
server.py
web/scripts/app.js

* feat: copy content to clipspace (context menu on node)
* feat: paste content from clipspace (context menu on node)
Extend validation to allow for validating annotated_path in addition to other parameters.
Add support for annotated_filepath in folder_paths function.
Generalize the '/upload/image' API to allow for uploading images to the 'input', 'temp', or 'output' directories.
Explain:
I intentionally used a name that is similar to "clipboard" but distinct, as the clipboard is currently used for copying within the node. This provides a foundation for future development of features that allow for editing clipspace data (especially images) and reflecting them in the node.
The previously proposed feature/img-send pull request can be replaced with this feature if it is incorporated.
You can …

Add clipspace feature.

---

comfy/sample.py
comfy/samplers.py
nodes.py

This PR makes the following changes:
- refactors the code in [common_ksampler](https://github.com/comfyanonymous/ComfyUI/blob/master/nodes.py#L743) to a set of functions that are easier to reuse.
- makes it possible for other code to calculate sigmas without creating a Ksampler to call [_calculate_sigmas](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/samplers.py#L432)
- allow calls to [Ksampler.sample](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy/samplers.py#L465) to supply a set of sigmas to be used instead of the pre-calculated ones.
I was not entirely sure where to put the functions that resulted from the refactoring of the common_ksampler function, these currently reside in comfy/sample.py
These changes make it possible to for instance create the custom …

refactor and restructuring of sampler code to give custom nodes more access

---

web/extensions/core/slotDefaults.js

Enables filtering the node search by input/output type:
When dragging input/output links to an empty space and selecting "Search" it will automatically filter the list to the correct type:

Node search - filter by type

---

web/style.css

Originally from #513
- button hover style
- ensure context menu is always above everything

Small styling tweaks

---

web/extensions/core/colorPalette.js
web/style.css

After this everything should be styled. The last two were the searchbox and the context menu which were not styled at all.
| Previous | Dark| Solarized | Light |
| - | - | - | - |
| ![image](https://user-images.githubusercontent.com/23466035/235504150-c57a1d05-51f3-4610-8e39-ed08bd507f92.png) | ![image](https://user-images.githubusercontent.com/23466035/235504032-f9c6d0c4-183f-4733-bb94-765dd0b2040e.png) | ![image](https://user-images.githubusercontent.com/23466035/235503811-96c55d92-6d37-4377-808c-d24df0ff71a2.png) | ![image](https://user-images.githubusercontent.com/23466035/235503922-85996b27-0ea0-466c-902b-d1c3e8a96c4d.png) |
| ![image](https://user-images.githubusercontent.com/23466035/235503563-41d5f408-e137-43b4-a263-91d3141de2ad.png) | …

Style searchbox and context menu

---

comfy/cli_args.py
main.py

As mentioned in #613, imo `windows-standalone-build` is currently a bit confusing as it's only purpose is auto launching the tab. However, MacOS and linux users might not realise that the windows standalone build is just autostart since its description implies other effects, and may not enable it because of that. But even if they did realise windows standalone build is autostart, now because of that you can't actually add any specific features to the windows standalone build command as those users will be expecting it to be autostart and will be suprised once it breaks after that.
This adds an auto-launch option and windows standalone build command enables it if it isn't already. Now if you do actually want windows-standalone-build to do other things like windows specific optimizations or …

Auto-launch cli arg

---

server.py

Allows the server to serve symlinks in the web folder
JS extensions can then be installed to the custom_nodes folder and the js then symlinked instead of needing to be copied on each startup or copied once and then being out of date on subsequent updates of the extension

Allow static files to be symlinks

---

web/scripts/app.js
web/scripts/widgets.js
web/style.css

This PR increases the canvas resolution to match the actual number of pixels of the display. This results in a less blurry UI for people with HiDPI monitors, or people who are using their browsers page zoom feature.
Here's an example when `window.devicePixelRatio` is 1.875
**Before**
**After**
I've also updated the multiline text widget so it correctly positions the textarea element at the higher resolution.

Improve UI render quality at higher pixel ratios

---

nodes.py

Speeds up generation if LoRAs/ControlNet are ultimately unused despite being in the graph

Don't load some model types if weight is zero

---

execution.py
web/scripts/api.js
web/scripts/app.js

- Much more data sent back by `/prompt` if nodes fail validation
- There was a bug in the previous implementation where nodes other than the output were excluded from the `node_errors` hash, this fixes that
- Highlight nodes/inputs that failed validation in the frontend
- Send back more information about exceptions raised during prompt execution
- Highlight nodes that raised exceptions in the frontend and show a message
Closes #681

Improve error reporting

---

web/scripts/app.js

Should be ```exception_message``` instead of ```message```
due to this:
https://github.com/comfyanonymous/ComfyUI/blob/a532888846809de7b8890e8beb10ea87edf39d7e/execution.py#L174

typo fix: field name in error message

---

web/index.html
web/style.css

The built-in dialog menus for litegraph require a container element with the `litegraph` class, so I added the class to the body. Now the properties dialog/dialogs added by extensions will work correctly

Fix litegraph dialog CSS

---

web/scripts/app.js

To support dynamic custom loading on frontend, separate the node registration process based on the defs in the registerNodes function.

refactor: registerNodes

---

server.py

I've wanted this so I can correctly order the queued prompts in the frontend, since the backend can change the number that was passed

Send back prompt number from `/prompt` endpoint

---

web/extensions/core/maskeditor.js

This commit addresses a bug where a crash occurs when copying the backup canvas to the mask canvas if the size is 0 before setting it.

bugfix: Crash fix for intermittent crashes that occur when opening MaskEditor.

---

server.py
web/extensions/core/maskeditor.js
web/scripts/app.js
web/scripts/ui.js
web/scripts/widgets.js

To reduce network traffic in a remote environment, a lossy compression-based preview mode is provided for displaying simple visualizations in node-based widgets.
* Added 'preview=[image format]' option to the '/view' API.
* Updated node to use preview for displaying images as widgets.
* Excluded preview usage in the open image, save image, mask editor where the original data is required.

improve: lightweight preview to reduce network traffic

---

README.md
comfy/cli_args.py
comfy/taesd/taesd.py
comfy/utils.py
folder_paths.py
main.py
nodes.py
server.py
web/extensions/core/colorPalette.js
web/scripts/api.js
web/scripts/app.js

Lets KSampler show previews with [taesd](https://github.com/madebyollin/taesd)
Download the `.pth` models from https://github.com/madebyollin/taesd and stick them in `models/taesd` first
Previews are encoded to JPEG bytes first then sent over websockets, they're resized to 512 pixels first so the network load shouldn't be too much (~50kb per frame for 2048x2048 resolution)
Also adds taesd-related nodes, they're functionally equivalent to VAE loader/encoder/decoder nodes
[output2.webm](https://github.com/comfyanonymous/ComfyUI/assets/24979496/f8cfc538-55d8-4d6f-b817-0db743d4f885)

Preview sampled images with TAESD

---

web/scripts/app.js
web/scripts/widgets.js

* Fixing the calculation issue when an image widget is added to he size calculation of the text widget.
* This issue occurs when there is already a text widget in a node, but an image widget is added through the preview functionality.

bugfix: size calculation conflict between text widget, img widget

---

web/scripts/app.js

* ```app.nodeOutputs[node.id + ""]``` is nullable
* Consider the case where a fileitem JSON is assigned to a string image widget.

bugfix: robust patch on pasteFromClipspace

---

README.md
main.py

- Fixed three text mistakes
- Made the code for the shortcuts table more visually appealing
- Converted the external links into anchor tags to open them in a new tab
- Brought some PEP8 adjustments
- Gave some love to Linux by not limiting the Ctrl+C exception pass only to Windows

Fix: Prevent KeyboardInterrupt exception thrown in Linux

---

web/extensions/core/contextMenuFilter.js
web/style.css

**ContextMenuFilter extension**
- Added right and left arrow to combo. Arrow right moves to the bottom of the list and left to the top.
- Highlight the option currently selected.
- e.keyCode is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). We should use [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) instead. However, we should opt for [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) since people use different keyboard layouts. Also removed `keyCode ==== 10` because this code [does not exist](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#value_of_keycode).
**CSS**
- Removed unit after 0 values because it's redundant.
- Font property font-family …

Improve ContextMenuFilter extension

---

README.md

The current ComfyUI installation instructions for macOS include `pytorch-directml`, which it's not currently available in Apple silicon. However, it's possible to run ComfyUI in Apple silicon computers (M1 or M2) without `pytorch-directml`.

Add Apple silicon installation steps

---

web/scripts/api.js

Fix for the unhandled message that appears in the console: 
```
Unhandled message: {"type": "execution_cached", "data": {"nodes": ["7", "15", "5", "10", "17", "13", "6", "12", "4", "16", "8", "18"], "prompt_id": "cd24e0bf-ca8d-46cf-b48c-354f311747f3"}} Error: Unknown message type execution_cached
at WebSocket.<anonymous> (api.js:130:18)
(anonymous) @ api.js:135
```

Fix unhandled message "execution_cached"

---

web/extensions/core/colorPalette.js
web/extensions/core/keybinds.js
web/scripts/ui.js

- keyCode was removed because it's deprecated
- The settings dialog can now be closed by pressing escape
- Removed the colon at the end of every setting's label because it looks nicer without

Clean keybinds extension

---

web/extensions/core/widgetInputs.js

Possible fix for #767.
The last_y and y properties of widgets were not being updated when the node had a multiline text widget.

Fix overlapping when converting widgets to inputs

---

web/extensions/core/rerouteNode.js

The links array changes during the loop when disconnecting inputs, invalidating the loop condition and the index counter. This caused links to be left over when they should have been disconnected.

Fix reroute node connecting different types

---

extra_model_paths.yaml.example

Hi!
The majority of LyCORIS users from A1111 are using [KohakuBlueleaf/a1111-sd-webui-lycoris](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris).
By default, it requires placing models in models/LyCORIS.
I think this patch is a sane example for most of the users.
Thank :)

docs(extra model paths): add LyCORIS path

---

comfy/samplers.py

The wrong dimensions were being checked, [1] and [2] are the image size. not [2] and [3]. This results in an out-of-bounds error if one of them actually matches.

Fix size check for conditioning mask

---

.gitignore
main.py

Currently, in ComfyUI-Manager, automatic installation of dependencies is performed when installing custom nodes. However, this can lead to module conflicts or failure to install due to file locking issues, especially in Windows environments.
To address this problem, a solution has been implemented where the imports are minimized at the top of main.py, allowing the install script to run in an environment with minimal imports.

feat/startup-script: Feature to avoid package installation errors when installing custom nodes.

---

web/extensions/core/clipspace.js
web/extensions/core/colorPalette.js
web/extensions/core/editAttention.js
web/extensions/core/invertMenuScrolling.js
web/extensions/core/keybinds.js
web/extensions/core/maskeditor.js
web/extensions/core/nodeTemplates.js
web/extensions/core/saveImageExtraOutput.js
web/extensions/core/slotDefaults.js
web/extensions/core/snapToGrid.js
web/extensions/core/uploadImage.js
web/extensions/core/widgetInputs.js
web/index.html
web/scripts/api.js
web/scripts/app.js
web/scripts/widgets.js
web/types/comfy.d.ts

This enables local reverse-proxies to host ComfyUI on a path, eg "http://example.com/ComfyUI/" in such a way that at least everything I tested works. Without this patch, proxying ComfyUI in this way will yield errors.
I'm not very familiar with the codebase currently, so this may be a suboptimal method, and/or it may be missing some key path handlers.
I'd be happy with any solution that enables subpathed reverse-proxying to work.
If in doubt, you can test with apache2 or nginx (or for @comfyanonymous I can give you the internal thing to test with)

use relative paths for all web connections

---

nodes.py

Patches attribute not found error when a lora_name is swapped, and the lora_path has changed resulting in self.loaded_lora being deleted.

Patch del self.loaded_lora for persistent lora_name swapping

---

web/types/comfy.d.ts

getCustomWidgets expects a plain record and not an array of records

fix: ⚡️ small type fix

---

comfy/samplers.py

ComfyUI complains about ambiguous boolean values when timestep ranges are used with batch sizes > 1 because `timestep_in` becomes multivalued.
The values in the tensor appear to all be the same, so just looking at the first index should be enough.

Fix timestep ranges when batch_size > 1

---

web/scripts/widgets.js

I have added slider and toggle widgets from `litegraph.js`. It improves usability compare to an input number where you have to type the value each time.
For example, it is possible to create an image_resolution node with an increment of 64 and an invert toggle button to easily change the desired resolution of an output image:
the code used to create this custom node:
```py
class ImageResolution:
@classmethod
def INPUT_TYPES(s):
return {
"required": {
"width": (
"SLIDER",
{
"default": 1024,
"min": 0,
"max": 6144,
"step": 64,
},
),
"height": (
"SLIDER",
{
"default": 1024,
"min": 0,
"max": 6144,
"step": 64,
},
),
"invert": (
"TOGGLE",
{
"default": False,
},
),
},
}
RETURN_TYPES = ("INT", "INT")
RETURN_NAMES = ("width", "height")
FUNCTION = "inverse_values"
CATEGORY = "image"
def …
```

added slider and toggle widget

---

nodes.py

When using SaveLatent from the API there is no indication of where its file was saved, I looked at how SaveImage worked, and basically mirrored the logic to SaveLatent, in my testing this worked.
That said, I'm not sure if this is the best way to do this, or if this might cause issues with something else, I'm new to ComfyUI and know almost nothing about Python.
Hopefully this is good, and will save you a few minutes.

SaveLatent should report its outputs so they are visible to API

---

web/extensions/core/linkRenderMode.js
web/scripts/ui.js

Add support for combo settings and changing the link render mode, which is a surprisingly popular script.
Defaults to spline which is the existing mode.

Add setting to change link render mode

---

web/extensions/core/contextMenuFilter.js

I've seen this crash due to a couple of extensions and it ends up leaving behind a semi broken combo list.
It doesn't really matter if it cant find the matching widget as it's just used for setting the initial selected index, so better to default that to 0 than crash.

Prevent menu filter crashing if the widget cant be found

---

web/scripts/app.js

I don't know if there is any consequences of doing this, but the performance improvements is significant for everyone who have tons of extensions, especially for ppl who running comfyui from a remote server (e.g. Colab)
Before the change:
After the change:

Make the extensions loads in parallel instead of waiting one by one

---

nodes.py
server.py

Allows serving web content from the custom_nodes folder, meaning that custom nodes dont have to symlink/copy web files.
Also helps when people remove custom nodes, they often leave web files behind and have weird issues.
The `supports = ["custom_nodes_from_web"]` allows custom node authors to check if the current version of ComfyUI the user is running supports this feature or not, e.g. they couyld implement it something like this:
```py
def should_install_js():
return not hasattr(PromptServer.instance, "supports") or "custom_nodes_from_web" not in PromptServer.instance.supports
```
If there is a better mechanism for this, open to suggestions.
A simple test for this:
```
NODE_CLASS_MAPPINGS = {
}
WEB_DIRECTORY = "./somejs"
__all__ = ['WEB_DIRECTORY']
```
Then create `somejs/hello.js` in …

Allow loading js extensions without copying to /web folder

---

web/scripts/widgets.js

**Problem:**
In the situation where the `nodeCreated` of `dynamicPrompts.js` is being called before another extension's `nodeCreated`, it becomes impossible to disable using dynamicPrompts = false.
currently, this disable code is useless
https://github.com/comfyanonymous/ComfyUI/blob/30eb92c3cbe0e0dfa442d452b5f1187c654e572e/web/extensions/core/dynamicPrompts.js#L20
**Solution:**
Assigning the `dynamicPrompts` configured in the widget config of STRING to the text widget's creation ensures that the configuration is set before the `nodeCreated` of `dynamicPrompts` is executed.
```
return {"required": {"text": ("STRING", {"multiline": True, "dynamicPrompts": False})}}
```

fix: cannot disable dynamicPrompts

---

nodes.py

Added option to set tile size manually for Tiled VAE encode and decode nodes

Make tile size in Tiled VAE encode/decode user configurable

---

server.py

**Motivation**
When the mask editor saves a modified image, the pngInfo metadata is currently lost. This means that nodes which use the additional pnginfo can't access it when the image being loaded has been mask edited. (I'm writing a suite of such custom nodes...)
**Solution**
When saving, create a PngInfo(), copy the contents of the `.text` attribute (if it exists) into it, and then include it in the save.

Preserve pnginfo

---

server.py

Most linux file systems use case-sensitive file names by default. MacOS also has them optionally, meaning that this endpoint was basically reporting the wrong names for embeddings that have at least one capital letter. Windows preserves case, but is case-insensitive.
This leads to the completions provided by [ComfyUI-Custom-Scripts](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) to cause an ignored embedding warning upon image generation.
Another option is to load embeddings case-insensitive, but in the case that a user (for some godforsaken reason) has multiple distinct embeddings with the same name but different capitalisation, the choice would be ambiguous.

Remove forced lowercase on embeddings endpoint

---

web/extensions/core/linkRenderMode.js

Thank you for adding this feature (linksRenderMode) to core. I would like to add the "Hidden" option (invalid number 3 will just hide the connector lines), so that I can remove that extension from my extension pack to prevent conflicts
https://github.com/failfa-st/failfast-comfyui-extensions

feat(extensions): Allow hiding link connectors

---

web/extensions/core/widgetInputs.js
web/scripts/app.js

Updates the way widgets with `forceInput: True` are handled.
Pre-Change:
- Standard Widget
- Load Node Def -> Create Widget -> Convert to Input option in menu
- Forced Input
- Load Node Def -> Create Input
Post-Change
- Standard Widget(No Change)
- Load Node Def -> Create Widget -> Convert to Input option in menu
- Forced Input
- Load Node Def -> Create Widget -> Force Convert to Input
Currently the Primitive node expects converted widgets to have a `widget` property on the input, but as "forced input" widgets are not converted to an input from a widget, they don't contain the property leading to errors.
This change treats "force input" widgets as widgets from the beginning, and then converts them to inputs. This way they should be identical to converted widgets. This also opens the door …

refactor/fix: Treat forceInput widgets as standard widgets

---

web/scripts/app.js

On execution start, call onExecutionStart on all nodes which have it.
Allows a custom node to initialize itself - for instance, to clear any UI output from the previous run.

onExecutionStart

---

comfy/ldm/modules/attention.py
comfy/ldm/modules/diffusionmodules/util.py
comfy/model_management.py

I did my best to try and refactor the Intel detection and keep changes minimal. I enabled bfloat16 in the VAE for Intel GPUs too as part of this since the GPUs that can use IPEX will have it by default, just as a heads up. Despite my efforts, it does seem like comfy/model_management.py seems to be getting pretty messy.

Enable BF16 VAE on Intel GPU and some additional fixes to generalize CUDA specific functionality to Intel and other GPUs

---

folder_paths.py

By default excludes .git folders
Refactored variable names to better match what they represent
In the future could support user provided excluded dirs via config file
Use relpath instead of join/replace/join

feat: Add support for excluded_dirs to folder_paths.get_filename_list_

---

server.py

The front end has a field 'description' for nodes which is currently always set to ''.
This one line change sets that field to the custom node DESCRIPTION attribute, if it is set, else leaves it as ''.
This can be used to allow more robust selection of special front-end behaviour
For instance, `DESCRIPTION="displays_text"` might indicate that a node should expect to receive some text to display (there's a PR coming with that functionality if this one is merged!)

Send node description (if any) to the UI

---

execution.py

If a node has inputs from other nodes, you cannot currently implement `VALIDATE_INPUTS` as this causes the execution to crash. Instead of breaking out and returning inputs as `None`, just set that specific input to be `None` so validation can still be done on widget inputs
Test node:
```py
class Example:
@classmethod
def INPUT_TYPES(s):
return {"required": {
"latent": ("LATENT", {}),
"text": ("STRING", {"default": "hello"}),
}}
@classmethod
def VALIDATE_INPUTS(s, latent, text):
print("VALIDATE_INPUTS:" + text + " | " + str(latent is None))
return True
@classmethod
def IS_CHANGED(s, latent, text):
print("IS_CHANGED:" + text + " | " + str(latent is None))
return text
RETURN_TYPES = ("STRING",)
FUNCTION = "test"
CATEGORY = "utils"
OUTPUT_NODE = True
def test(self, latent, text): …
```

Fix crash on node with VALIDATE_INPUTS and actual inputs

---

server.py

Disables aiohttp access logs.
At least until there's a proper log level system, these seem quite verbose to be enabled with the logging level comfy ships with(Verbose)
Fixes #1346

fix(server): Disable access logs

---

web/scripts/widgets.js

Float widgets have rounding errors (see https://github.com/comfyanonymous/ComfyUI/issues/889). This PR rounds the widgets to a configurable precision which defaults to 0.001 (the precision displayed - so that the value is identical to what it appears to be).

round float widgets (by default to 0.001)

---

web/extensions/core/widgetInputs.js
web/scripts/app.js

Create a `defaultInput` option (like `forceInput`) which does what it sounds like - the widget gets converted to an input by default, but can be changed back to a widget if desired. Usage is simply:
```python
REQUIRED = {"string_normally_input": ("STRING", {"default":"", "defaultInput": True})}
```
No change to behaviour if the option isn't used.

defaultInput

---

web/scripts/app.js

After copying nodes, we should clear the system clipboard. That way the next paste will only paste the nodes we've just copied and not anything else.
This also fixes an error with copying and pasting from text boxes.

Fix: Copied nodes don't get pasted if there is an image in the clipboard

---

web/scripts/app.js

Firefox doesnt fire a paste event on ctrl+shift+v (Chrome does) so we dont want to block the default litegraph key handler 
This update means you cant use ctrl+shift+v to paste images/json and will always use the litegraph clipboard with that shortcut, but I don't think that's a problem (maybe even a feature 😅)

Allow pasting nodes with connections in firefox

---

web/scripts/app.js

structuredClone is undefined at low version browser which build with early version chrome like chrome95

fix structuredClone undefined error;

---

web/scripts/app.js

Problem:
When multiple images with different ratios are passed to the image widget, images with ratios different from the determined cell ratio appear distorted.
Fixed:
Maintain the original image's ratio.

fix: Ensure proper handling of images with mixed ratios.

---

server.py

Try to prevent JS search from breaking on pathnames with square brackets.
Tested by renaming my ComfyUI path to `ComfyUI[test]`, then starting without the patch -> no custom nodes show up, nor the "Manager" button.  Checkout branch with my change and start again, Manager button shows up, custom nodes seem to work.
Note that while this is the only use of glob I could find in the ComfyUI code, there are probably custom nodes with the same issue, so I don't know if this will actually make for a reasonable UX if there are square brackets in any pathname.

Escape paths when passing them to glob

---

nodes.py

This PR adds proportional scale to latent and image scale, if width or height is 0 it calculates that value proportionally to the original size, so you can scale by setting just the width or height without the need to manually calculate the proportion or the scale factor.
I got the idea for that feature from #1591

Proportional scale latent and image

---

comfy_extras/nodes_mask.py

Currently the GrowMask node doesn't work properly with batches, only grows the first mask and then returns everything as single image like this:
After this change it works and is compatible with AnimateDiff:

Allow GrowMask node to work with batches (for AnimateDiff)

---

server.py

If an error occurs while retrieving object_info, only the node that encountered the error should be handled as an exception, while the information for the other nodes should continue to be processed normally.

fix: robust patch for '/object_info'

---

web/extensions/core/widgetInputs.js
web/scripts/app.js

A few updates to improve primitives:
1. Allow connecting primitives to other numbers that have configs that are different but have some overlap, and merge the constraints, e.g.
Input 1: [step = 10, min = 20, max = 50]
Input 2: [step = 5, min = 5, max = 30]
Connecting a primitive to the two of these will be restricted to [step = 10, min = 20, max = 30]
If the steps are not simply divisible (e.g. you tried to connect step = 8 to the above example) it'll be rejected.
2. Removes the "config" object that was previously stored in the graph and if a COMBO widget was converted would contain the full list, and not refresh if new items were added between sessions.
It now loads gets the config dynamically from the node definition instead of storing it.
3. "Refresh" button now reloads combo values in …

Widget input/primitive updates

---

web/scripts/app.js

Should fix custom nodes that are returning arrays as an output type

If the output type is an array, use combo

---

comfy/latent_formats.py
comfy/taesd/taesd.py
latent_preview.py

Allows to load TAESD models in safetensors format.
Currently, only `models/vae_approx/tased_(en|de)coder.pth`  can be load.
It will also be able to load `models/vae_approx/tased_(en|de)coder.safetensors` .
TAESD models in safetensors format exist at:
https://huggingface.co/madebyollin/taesd/tree/main
https://huggingface.co/madebyollin/taesdxl/tree/main
The following warning can be avoided by using safetensors if no other factors are present:
> UserWarning: TypedStorage is deprecated. It will be removed in the future..

Supports TAESD models in safetensors format

---

web/scripts/app.js

Fixes #1723 
Trivial, safe change - change `.type ===` to `?.type ===`, which will fail if the input is undefined instead of raising an error

add query to fix 1723

---

extra_model_paths.yaml.example

This file only references A111, which isn't helpful to making it work for ComfyUI. These changes make it clear how to format it for ComfyUI.

Update extra_model_paths.yaml.example with comfy specific example

---

folder_paths.py

Small fix, in case of the extensions list being empty it allows all extensions instead of removing all files.
This is useful for custom nodes.

Allow all extensions if extension list is empty

---

web/lib/litegraph.core.js

The getBounding wasn't considering the collapsed flag for the width, so collapsed nodes were being grabbed wrongly by near groups.

Fix node getBounding for collapsed nodes

---

web/scripts/app.js

This issue mainly occurs in the Firefox browser. 
In certain situations, a namespace issue with the `graph.` leads to the `app.graph.` not being found, causing the UI to crash.

fix: Fixing intermittent crashes with `undefined graph` 

---

comfy/controlnet.py

After latest updates, cond now has this data under 'y' key instead of 'c_adm'.

Change 'c_adm' to 'y' in ControlNet.get_control

---

latent_preview.py

The TAESD preview returns the first latent anyway to be displayed, but the code before performed decoding on all latents and returned the first index. For single images that is fine, but 1) causes slowdowns when using batches greater than one, and 2) causes VRAM OOM when batch size is a fairly large number.
Changed code now passes only the first latent into the decoder, in the form [1, :, :, :] via slicing, and then stores result into x_sample as [channels, h, w] same as before. No more VRAM isssues with large batch sizes, and preview is faster for any batch size > 1.

Fix TAESD preview to only decode first latent, instead of all

---

web/extensions/core/contextMenuFilter.js

I noticed that when a scrollable list is long (say, you have many checkpoints) it's possible for the list filter at the top of the div to be scrolled offscreen. It turns out currentNode.widgets can be null, and in that case the script errors out and scrolling to the top of the list on display is never called. This guards against that so the script should always continue on as normal, and the filter is reached.

fix: handle null case for currentNode widgets to prevent scroll error

---

comfy_extras/nodes_post_processing.py

Added Bayer ordered dithering to Quantize node. Options for 2x2, 4x4, 8x8 and 16x16 Bayer matrix. This is mostly useful for retro pixel art styles.

Added Bayer dithering to Quantize node.

---

comfy/model_patcher.py

fix unet_wrapper_function name in ModelPatcher.  
It should be the same as in method set_model_unet_function_wrapper.
Make the .to attribute of wrap_func work.

fix unet_wrapper_function name in ModelPatcher

---

web/scripts/domWidget.js

Collapsing a node with a DOM element will now hide the element

Handle collapsing to hide element

---

tests-ui/tests/widgetInputs.test.js
web/extensions/core/widgetInputs.js
web/scripts/widgets.js

Allows filtering of the items in a COMBO primitive (e.g. LoadImage images list) when using control_after_generate. 
You can also use regex to filter the items by wrapping the expression in `/`s e.g. `/(sdxl|sd15)/`
Maintains existing behavior of `addValueControlWidget` for extensions currently using it, adding `addValueControlWidgets` which returns an array of added widgets.

Control filter list

---

web/extensions/core/undoRedo.js

Adds a very simple undo/redo implemetation.
Litegraph has some beginnings of before/after change events however its missing from a lot of key actions.
This just handles mouse/keyboard events to check if there are any changes in the graph vs the previous, which seems like a reliable way of catching any changes.
It stores the entire serialized graph for each history state which isn't great, but with a limited size of 50 it should be fine in real use

Simple undo/redo

---

folder_paths.py
nodes.py

This fixes two problems:
1. program crash if it can't create the input folder. Now it only prints an error message
2. program crash if the custom_nodes folder is a symlink. Now it will follow the symlink.
These are issues found while [packaging comfyui for NixOS](https://github.com/NixOS/nixpkgs/pull/268378)

fix: folder handling issues

---

tests-ui/tests/extensions.test.js
tests-ui/utils/index.js
web/scripts/app.js

Adds some tests for extension callbacks to ensure these aren't broken in updates
Also adds a "afterConfigureGraph" extension callback that fires after a graph is loaded

Add Extension tests

---

web/extensions/core/nodeTemplates.js

It is currently swapping entries rather than moving when you drag to re-order the templates
e.g. if you have [a,b,c,d] and you drag d to the top to get [d,a,b,c]
if you then close and reopen, you get [d,b,c,a]

Fix template sorting

---

web/extensions/core/saveImageExtraOutput.js
web/extensions/core/widgetInputs.js
web/scripts/utils.js

Allows for the search & replace of widget placeholder values on primitive nodes.
Adds a property on primitives for enabling this (defaults to false):

Allow widget placeholder replacement on primitives

---

web/extensions/core/maskeditor.js

improved:
1. Basic structure improvement
2. Enhance to display the image in the center of the dialog.
3. Zoom feature: ctrl + wheel
4. Pan feature: ctrl + left button drag
fixed:
Fix the issue where the existing mask does not appear when loading an image with a mask.

improve: Mask Editor

---

tests-ui/tests/extensions.test.js
tests-ui/tests/widgetInputs.test.js
tests-ui/utils/ezgraph.js
web/extensions/core/rerouteNode.js
web/extensions/core/widgetInputs.js

Allows connecting reroutes to primitives. The reroute needs to be connected to the target input before a primitive is allowed to be connected.
Widget settings (e.g. min/max) will be merged like with normal primitives connected to other nodes.
Group nodes currently won't support this and will need their own fixes, i'll make another PR to resolve this (once i've fixed it!).

Allow reroute to work with primitive nodes

---

tests-ui/tests/groupNode.test.js
web/extensions/core/groupNode.js

Fixes internal reroutes connected to other group nodes
The example in the issue #2231 can be used for checking

Fix internal reroutes connected to other groups

---

web/extensions/core/maskeditor.js

Addressing the issue where an unnecessary hidden panel disrupts the drawing.
this patch fixes this issue:
https://github.com/comfyanonymous/ComfyUI/issues/2246

mask editor bugfix

---

web/extensions/core/undoRedo.js
web/scripts/app.js

Fixes #2242
Edit: removed flicker reduction as stop/start rendering seems to trigger some bug in LiteGraph
~~Also attempts to reduce some flicker on undo/redo - most noticably moving CLIPTextEncode nodes, the textareas will flicker. Images will still flicker due to being reloaded (looks likely due to the rand parameter forcing a reload, haven't looked into this)~~

Prevent cleaning graph state on undo/redo

---

tests-ui/tests/groupNode.test.js
tests-ui/utils/ezgraph.js
tests-ui/utils/index.js
web/extensions/core/groupNode.js
web/extensions/core/rerouteNode.js
web/extensions/core/undoRedo.js
web/extensions/core/widgetInputs.js
web/scripts/app.js

Fixes 3 issues:
1. Fix crash on unlinked grouped reroute
[group_unlinked_reroute.json](https://github.com/comfyanonymous/ComfyUI/files/13640111/group_unlinked_reroute.json) - Disconnect image link between the two group nodes, click queue
- Before: Crashes on queue
- After: Shows missing input error
2. Fix converted widget inputs
[group_widget_inputs.json](https://github.com/comfyanonymous/ComfyUI/files/13640163/group_widget_inputs.json) - Convert two KSamplers to a group node
- Before: Various issues - links disconnected, value lost, fixing the links and queuing gets links incorrect (Return type mismatch between linked nodes)
- After: Works
3. Add basic support for reroute inputs connected to converted widget inputs 
[reroute_converted_input.json](https://github.com/comfyanonymous/ComfyUI/ …

Group node fixes

---

comfy/samplers.py
comfy_extras/nodes_sag.py
nodes.py

The SAG config is activated by the node `_for_testing/Self-Attention Guidance`, and then the sampler does it automatically.
There are a few implementation details that need further work:
- ~We make one more call to the UNet than is needed~
- We only store the attention from the last unconditional call to the UNet. This means that if a large batch is broken up into multiple UNet calls, things will break.
I used the formula from @ashen-sensored. Although it seems to disagree with the paper, it gives better results, so I think I probably misunderstood that. In any case, would be nice to have a second pair of eyes on samplers.py:L272.

Implement Self-Attention Guidance

---

web/scripts/domWidget.js

If you quickly drag a SaveAnimatedWEBP node, with an animated image on it, off the edge of the window so it isnt visible, the image will get "stuck" at the edge

Fix dom widgets not being hidden when node is not visible

---

web/scripts/app.js

Add title to the API workflow json.
Motivation: API client users can find nodes by title, instead of just by class_type.
Related 
* [[Feature Request] Custom API node IDs #1326](https://github.com/comfyanonymous/ComfyUI/issues/1326)
* [[Feature Request] Save json with title label value in API mode. #1433](https://github.com/comfyanonymous/ComfyUI/issues/1433)
* [custom names for nodes in API export #2031](https://github.com/comfyanonymous/ComfyUI/issues/2031)

Add title to the API workflow json.

---

execution.py
main.py

**Motivation:** API clients sometime miss websockets messages, its nice to be able to see how the job via the `/history` endpoint. I am writing a 3rd party API client that can schedule workflows from python, and it is a bit fragile depending on the websockets API for errors. The `/history` endpoint is reliable, but the error is opaque. This change gives an API a clear indicator and reason why the job failed.
Example output of `/history`:
```json
{
"b1b64df6-9b2c-4a09-bd0e-b6c294702085": {
// ... old prompt and output dictionaries here.
"status": {
"status_str": "success",
"completed": true,
"notes": [
[
"execution_start",
{ "prompt_id": "b1b64df6-9b2c-4a09-bd0e-b6c294702085" }
],
[
"execution_cached",
{ "nodes": [], "prompt_id": "b1b64df6-9b2c-4a09-bd0e-b6c294702085" }
]
]
}
}
}
``` …

   Enhanced /history, with status about errors, completion.

---

web/extensions/core/groupNode.js
web/extensions/core/undoRedo.js

Fixes modifier keys triggering multiple history entries, e.g. previously shift+drag/alt+drag and move node would store each position while it was being dragged rather than just the start/end of the drag events

Fix modifiers triggering key down checks for undo history

---

web/scripts/app.js
web/scripts/widgets.js

Adds setting to allow the control_after_generate to change to before
Works with group nodes/primitives/normal
When set to "before" it will not generate a new value the first time the node is executed in the session, this means you can reload old workflows and generate, and you'll get the same image the first time you run.

Control value before generate

---

web/scripts/app.js

Adds Copy Image menu item if browser supports writing images to clipboard:
Writing images to clipboard is enabled in Chromium based browsers by default, Firefox requires a config setting:
https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility
> From version 87: this feature is behind the dom.events.asyncClipboard.clipboardItem preference (needs to be set to true). To change preferences in Firefox, visit about:config.
Chrome seems to currently only support writing PNG data, Firefox supports that and other types so it'll try writing the raw image then if that fails converts to PNG.

Adds copy image option if browser feature available

---

web/scripts/logging.js

This meant when the setting value was changed from its default by the settings loading, it was not reacting to the change.
I've also had a quick check of all other settings and they all appear correct.

Fix logging not handling onChange

---

web/extensions/core/groupNode.js

Create a group node containing 1 or more LoadImage nodes
Manage group node -> Rename `image` widget
Previously would crash as the button couldnt locate the image widget

Fix renaming upload widget

---

execution.py

`status_dict: dict|None = None` relies on PEP 604 to use the `|` to mean "or". Previously (Python<3.10) one had to use `Union` or `Optional`. The previous change (https://github.com/comfyanonymous/ComfyUI/commit/1b3d65bd84c8026dea234643861491279886218c) is probably breaking ComfyUI for some people who are using older versions of python. This PR fixes the issue.

Don't use PEP 604 type hints, to stay compatible with Python<3.10.

---

web/scripts/ui.js

There are two places this logic could live in, either line 387 or 388 and it makes more sense from UX point of view to discard changes while the autoQueueEnabled was turned off.
Keeps the logic the same as it currently is for instant auto queueing so it needs to manually be triggered
(maybe should still update this.graphHasChanged?)

Fix queue on change to respect auto queue checkbox

---

web/extensions/core/groupNode.js
web/scripts/app.js

1. Add a node to a group node that has a combo list (e.g. Checkpoint Loader)
2. Add/rename/delete a model
3. Click Refresh on the menu
4. The list will now be updated on the widget correctly, newly added instances of this group will have the correct list

Support refresh on group node combos

---

web/scripts/api.js
web/scripts/app.js

Stores the workflow and client id in sessionStorage so when working with multiple tabs and a tab is refreshed, the correct workflow will be loaded instead of the one that happened to save last.
Also means when you duplicate a tab, you'll get the correct workflow. There appears to be a bug in Firefox where a duplicate of a duplicate etc ... at some point the sessionStorage ends up empty and you lose the ID but it works fine in Chrome.

Make auto saved workflow stored per tab

---

web/extensions/core/maskeditor.js

I tried to do an inpaint on my image, and found that I was unable to brush the bottom area, as shown below:
After investigation, it was caused by an invisible div element that wrapped the buttons and slider.
There was an issue https://github.com/comfyanonymous/ComfyUI/issues/2246 and an PR https://github.com/comfyanonymous/ComfyUI/pull/2249  about this problem, but the PR didn't fix that all, so I create this PR.

Fix: mask editor inpaint area

---

web/extensions/core/groupNode.js
web/extensions/core/groupNodeManage.css

1. Fixes scroll in manage window with many nodes (duplicate the default workflow a few times, convert to group, manage)  #2655
2. Fixes crash on modified input where group has no widgets (add 2x ImageInvert, hide the first ones input, save) #2665

Group manage fixes

---

web/scripts/widgets.js

Only applied when isCombo.  Loops back to index 0 when at end of list.
Useful in testing workflows to loop through checkpoints, noise schedulers, samplers, etc.  Also has applications for animate workflows.
Apologies for my editor's overzealous elimination of whitespace.

add increment-wrap as option to ValueControlWidget

---

comfy_extras/nodes_latent.py

as title says, the default value was changed to fixed as random is already default behavior for batch latent seeds. This is mainly for QoL as you can just get onto noodling it in right away.

Changed default of LatentBatchSeedBehavior to fixed

---

web/scripts/app.js

The Image Save node in WAS Node Suite will save prompts in `Prompt` instead of `prompt`: https://github.com/WASasquatch/was-node-suite-comfyui/blob/33534f2e48682ddcf580436ea39cffc7027cbb89/WAS_Node_Suite.py#L7227-L7238. But the frontend doens't support `Prompt`. This PR fixed this problem.

Fix frontend webp prompt handling

---

web/extensions/core/maskeditor.js

**Issue**: mask editor is always using black masking brush. It's hard to see mask on darker images and it's also impossible to see picture under the mask. Also see https://github.com/comfyanonymous/ComfyUI/issues/2456
**Solution**: add 3 brush color modes - black, white and negative. Some modes are more useful for specific pictures. Default mode is black and it has 0.7 opacity without ability to change it. White is also 0.7 opacity and it looks the same as in automatic1111 webui mask editor. Modes can be toggled by pressing "Color" button next to brush thickness slider.
I only changed mask rendering in mask editor, mask saving behaves as usual

Mask editor: semitransparent brush, brush color modes

---

web/extensions/core/widgetInputs.js
web/scripts/app.js

Adds `convertWidgetToInput` method to all nodes
Converts widgets to inputs & links them when loading API format if no matching input is found, but a widget is.

Support linking converted inputs from api json

---

web/extensions/core/simpleTouchSupport.js
web/scripts/ui.js
web/scripts/ui/settings.js
web/style.css

By no means perfect, but better than it currently is.
- Ability to hide menu
- Responsive setting screen
- Touch events for zooming (pinch), opening rightclick/context menu (touch hold, release)
I've tested on Firefox + Chrome on Android, and Safari on an old iPad. If someone could please test on a newer iOS device that would be great.
Close button menu, hides the menu and shows a hamburger menu icon:
Settings collapses into a single column with a close button at the top

Improved mobile support

---

comfy/samplers.py

If ```ddim_scheduler``` is ever called on a model whose model_sampling sigmas contain less sigmas than the requested steps, the current code will result in an infinite while loop due to ```ss``` being set to 0.
This PR makes sure ```ss``` will be at least 1 to prevent ComfyUI from hanging forever.

Fix infinite while loop being possible in ddim_scheduler

---

comfy/samplers.py

currently custom samplers can add themselves to the list of built-in samplers but there's no facility to request discarding the penultimate sigma. this minor change moves the list of samplers subject to discard penultimate sigma into a `set` that exists as a class property.
this allows a custom sampler that wants to skip the penultimate sigma to do something like:
```python
from comfy.samplers import KSampler
KSampler.DISCARD_PENULTIMATE_SIGMA_SAMPLERS.add('sonar_dpmpp_sde')
```

Allow custom samplers to request discard penultimate sigma

---

web/lib/litegraph.core.js
web/style.css

The solution I took is to use a CSS rule to force `filter: brightness()` to execute on GPU instead of CPU. This is apparently a hint that is needed for Safari. Chrome et al appear to do it for us automatically. 
My test case was simply having 536 nodes in the search results box. I reach this number after installing about 15 comfyui plugins using the plugin manager. I noticed that the larger the results list was, the longer the denial of interaction was under Safari. 
I have tested to confirm that adding `will-change: transform` is enough to eliminate the performance problem, and out of all the strategies I came up with, this is the one that best guarantees no other change is made to visuals or behavior of the program. I was initially going to replace filter:brightness with a bgcolor …

Safari: Draws certain elements on CPU. In case of search popup, can cause 10 seconds+ main thread lock due to painting.

---

nodes.py

Allow configurable addition of batch number to output file name.
Existing png files with workflow metadata can still be dropped in without any problems; the default is to not append the batch number.
Very useful to people like me who generate a lot of images in batches and find an image to continue working on in a future review  (at this point there is no way to regenerate the image using the `Latent From Batch` node as I've lost the batch number)

Add batch number to filename

---

web/scripts/pnginfo.js

Plenty of images at CivitAI (like this [image](https://civitai.com/images/6098063)) have prompts stored in the `iTXt` chunk. I think it's because they contain non-Latin characters <sup>[1](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html)</sup>.

Support additional PNG info.

---

comfy_extras/nodes_perpneg.py

Adjusts the Perp-Neg implementation to match the [paper](https://arxiv.org/abs/2304.04968) (see Algorithm 1 in Appendix A.1). Fixes #2858
With this fix, Perp-Neg correctly ignores any components of the negative prompt that are parallel to the positive prompt. In other words, common parts are ignored as intended.
Positive: "forest"
Negative: "forest"
Before:
After:
edit: oops, didn't realize renaming the branch would close the PR. sorry for the noise

Fix Perp-Neg math

---

comfy/samplers.py

Fixes an issue where if `model_options` has `transformer_options` with `patches` and conditionings have `patches` the `patches` on conditionings are lost.
In the original code
```
transformer_options = {}
if 'transformer_options' in model_options:
transformer_options = model_options['transformer_options'].copy()  
if patches is not None:
if "patches" in transformer_options:
cur_patches = transformer_options["patches"].copy() # --> Here the dict is copied
for p in patches:
if p in cur_patches:
cur_patches[p] = cur_patches[p] + patches[p] # --> this change doesn't go back into transformer_options
else:
cur_patches[p] = patches[p]  # --> this change doesn't go back into transformer_options
else:
transformer_options["patches"] = patches
```

Fix model and cond transformer options patches merge

---

server.py

We can use this command to access all the files in the hosting server when `--listen` is specified:
```
curl "http://<comfyhost>:8188/../../../../../../../../../../../../../../etc/passwd"
```
It may be an issue of `aiohttp` but I wonder if the `follow_symlinks` option is neccessary for ComfyUI

disable follow_symlinks in static serving for security reason

---

comfy/samplers.py
comfy_extras/nodes_differential_diffusion.py
nodes.py

The authors of the paper introduced a concept called a _change map_. For brevity, I will refer to it here as a _mask_.
The node `_for_testing/Differential Diffusion` is meant to be used alongside the `InpaintModelConditioning` node or the `Set Latent Noise Mask` node, and then the sampler does it automatically.
* A [full change](https://github.com/exx8/differential-diffusion/issues/2#issuecomment-1738136217) of the mask is done, essentially $\fbox{mask >= threshold}$ instead of $\fbox{mask > threshold}$. This is important because the contents of the mask should be followed, and for latent inpainting/outpainting (where the mask becomes binary), the initial step _should_ paint _something_.
* Lighter areas get painted earlier, darker areas later.
* Try adjusting the mask's blur, opacity, …

Implement Differential Diffusion

---

comfy/model_patcher.py

Fixes WARNING SHAPE MISMATCH warnings I encountered while merging large fp32 models, may resolve complaints in #3125 and #3122 and #3094

Fix typo in lowvram patcher

---

web/scripts/pnginfo.js

This PR improves the A1111 metadata parsing fixing some issues and adding some features.
Specifically it make 4 changes:
1. Sets the VAE name (`vae_name`) in the `VAELoader` when present.
2. Properly parses metadata that contains `:` as part of the value in a key-value pair. This can happen in string and JSON values.
3. Skips additional fields so they are not reported as warnings in the console. Specifically: `Version`, `VAE hash`, `TI hashes`, `Lora hashes`, and `Hashes`.
4. Sets the steps for High Resolution Upscaler when present in the metadata.

Improve A1111 metadata parsing

---

web/extensions/core/widgetInputs.js

ComfyUI Node has an overwhelming number of convert.. input dropdown menus. 
It was so inconvenient that I shortened it like this.

Change Convert XXX to input

---

web/scripts/ui.js

Always ensure In bounds.
Fixed an issue where the main menu disappears intermittently as the coordinates become negative.

fix: main menu vanishing

---

comfy_extras/nodes_custom_sampler.py

Custom scheduler nodes have sigma inputs capped by 1000, but models with ZSNR operate on sigmas larger than this cap (`sigma_max` for ZSNR model ~= 4518.7637).
This PR raises max limit for sigmas to 5000, allowing to use custom schedulers with ZSNR models.

Increase sigma_min/sigma_max range for custom schedulers (fix for ZSNR models)

---

comfy/samplers.py

Currently, there is code to handle the case that there are less masks than batch size, but if the masks exceed batch size, the math on line 38 breaks, trying to repeat 0 times (and causing the mask batch size to not match expected length even if the math did work out somehow).
This PR simply caps the mask tensor batch size at the size of input_x, making use of cond masks less frustrating when changing batch size as often happens with video workflows.

Fix error when more cond masks passed in than batch size

---

README.md
comfy/cli_args.py
main.py
server.py

- Add two cli arguments to allow key and cert file path to be passed to enable TLS, make the app accessible at`https://...`
- Update readme, add example of how to use.
Ref #1481 #1105

Add TLS Support

---

comfy/model_management.py

Change torch.xpu to ipex.optimize with default options removed, xpu device initialization call and remove workaround for text node issue from older IPEX that was fixed from testing the latest v2.1.30+xpu package that released recently.

Intel Arc IPEX updates for XPU

---

node_helpers.py
nodes.py

Fixed Value Error: Decompressed Data Too Large thrown by PIL when attempting to opening PNG files with large embedded ICC colorspaces.
Error occurs because PIL misinterprets large embedded ICC profiles in PNG images as malicious decompression bombs, and throws 
By setting the follow flag to true when loading PNG images PIL discards meta data, preventing the error:  
ImageFile.LOAD_TRUNCATED_IMAGES = True

Fixed Issue with LoadImage node when loading PNG files with embedded ICC profiles.

---

web/extensions/core/maskeditor.js

Introduces an "Opacity" slider to the mask editor dialog window, positioned to the right of the existing "Thickness" slider. 
Users can now adjust the opacity of the mask within the range of 0.1 to 1.0.

Add an opacity slider to the mask editor dialog

---

comfy_extras/nodes_model_downscale.py

PatchModelAddDownscale is accessing `model.model_sampling` directly instead of using `get_model_object` function, causing wrong behavior when using nodes like ModelSamplingDiscrete.
This PR contains fix only for PatchModelAddDownscale node. There might also be another places in code where `model.model_sampling` is being accessed directly, but I'm not sure whether it causes any issues or not.

Use get_model_object instead of model.model_sampling in Deep Shrink node

---

README.md
web/scripts/app.js

New shortcuts for canvas zoom in/out.
alt + `+` : zoom in
alt + `-`  : zoom out
ctrl + shift + LMB + vertical drag: zoom in(up) + out(down)
Several system doesn't have mouse.
https://github.com/comfyanonymous/ComfyUI/issues/3406#issuecomment-2095286274

feat: shortcuts for zoom in/out

---

node_helpers.py
nodes.py

Created a generic wrapper function node_helpers.pillow, that takes PIL functions as a dependency injection to apply the try except solution of using ImageFile.LOAD_TRUNCATED_IMAGES = True to fix PIL issues #4472 and #2445
The fix for ComfyUI issue #3416 is re-implemented using the generalized function
Additionally, the calls to Image.open and ImageOps.exif_transpose have be updated in a few nodes the new generic wrapper function node_helpers.pillow
This gives us a single place to handle meta data related pil errors, and apply fixes without having to duplicate code in other locations. It also provides an easy to use generic wrapper for node creators to use as a way to handle pil errors that fixes have been found for. 
the function is called as follows: 
```
img = …
```

Added generic wrapper function node_helpers.pillow to fix PIL issues #4472 and #2445

---

web/scripts/app.js

Adds a setting, enabled by default, for storing the current canvas position & zoom.
This is embedded in the json files and images generated by the workflow.

Setting for saving and restoring canvas position and zoom level

---

README.md
comfy/model_management.py

The change brings things in line the XPU free memory calculation and has it mimic how the CUDA memory calculation is done since allocated memory will return a smaller number than reserved memory and is therefore too aggressive. Also update Intel GPU install procedure documentation in the README instead of just linking it to the discussion topic.

Fix Intel GPU memory allocation accuracy and documentation update.

---

web/scripts/app.js

Had a few files that were named `Comfy_nnnnn_.jpg` and didn't notice the jpg format at first. Small PR to show a message about not finding a workflow when one is not present.
Additional small code change to remove unnecessary indentation level.

Show message on error when loading wf from file (works on drag and drop)

---

execution.py

Provide a better error message when attempting to execute the workflow with a missing node.

improve: better error message for execution of missing node

---

comfy/model_patcher.py
comfy/types.py

When I was implementing IC-Light, I found that it is hard to reason what are available to the callback. https://github.com/huchenlei/ComfyUI-IC-Light-Native/blob/893f5238d87e7ca4ffd4a810a124972289778857/ic_light_nodes.py#L118
This PR adds type annotation for `unet_wrapper_function`, so developer can figure out how the function should behave without running the debugger.

Add type annotation UnetWrapperFunction

---

web/scripts/app.js

Currently, after the user sets custom titles for nodes, saving workflow to API format stores the titles like so:
```
"0": {
"inputs": {
...
},
"class_type": ...,
"_meta": {
"title": "My Title"
}
}
```
However, when loading the API workflow from a JSON, the user-set titles are ignored and reset back to the default titles. This is a simple fix that sets the titles correctly from `_meta` when loading from API format workflow JSON.

Load titles from API format JSON

---

web/extensions/core/snapToGrid.js

Extends the core Comfy.SnapToGrid behavior that exists for nodes to apply to LiteGraph's LGraphGroup with the same behavior (ghost on move, snap on move-end and resizing).
Also, pulls out redundant rounding code into util function.

Extend core snapToGrid to snap Groups as well

---

web/scripts/domWidget.js

This PR improve dom widget performance with a simple 3-line change.
I've discovered a performance issue with the rendering of DOM widgets:
In simple terms, the calculation for the ClipPath is only necessary when collisions with the selected node occur. However, due to incorrect parameters passed in the previous code, all DOM widgets were constantly calculating their own ClipPaths, even when it served no purpose. This could potentially cause performance issues when there are many DOM widgets.
Additionally, I have already verified that there are no issues with the fix in my own maintained litegraph.ts library.

improve dom widget performance

---

.gitignore
comfy_extras/nodes_perpneg.py

Noticed PeturbedAttentionGuidance didn't work with PerpNegGuider; the fix seemed obvious once I saw how PerpNegGuider overrides all the base sampling stuff.
There might be cleaner fixes if passing all three conditioning requests to calc_cond_batch isn't actually useful; I didn't dig into that function.

Fix to allow use of PerpNegGuider with cfg_function_post hooks (like PAG)

---

comfy/model_management.py

Sorry, forgot to send this patch earlier. See https://github.com/intel/intel-extension-for-pytorch/issues/636#issuecomment-2144804349 and the thread in general for the discussion on this but it seems like the argument is that the runtime is fine and that the XPU-CPU transfer is not ready yet in IPEX before returning the image data so it needs to be set to non-blocking.

Exempt IPEX from non_blocking previews fixing segmentation faults.

---

comfy/lora.py

Loading Loras made with SimpleTuner (example: https://civitai.com/models/513204/stable-diffusion-3-famous-folks?modelVersionId=571990 ) currently fails due to different keys.
This simple patch makes loading them work (and they seem to have the right result).

Fix lora keys for SimpleTuner

---

server.py

Related to https://github.com/huchenlei/ComfyUI_frontend/pull/43
This PR prefixes every api endpoint with `api/` prefix, so that they can be easily identified and proxyed in the frontend dev server. Old endpoints are kept functioning the same way as before.

Add api/ prefix to api endpoints

---

server.py

Closes https://github.com/comfyanonymous/ComfyUI/issues/3788.

Fix web server routes with `api/` prefix

---

.github/workflows/test-browser.yml

This PR adds an github action for browser tests with [PlayWright](https://github.com/microsoft/playwright).
The browser tests should prevent accidental front end UI regression, and keep the front-end features synced in the current repo & in TS repo ([huchenlei/ComfyUI_frontend](https://github.com/huchenlei/ComfyUI_frontend)) during the TS migration period.

Add browser test action synced with TS repo

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/user-support.yml

This adds issue templates so that newly submitted GitHub Issues will have an option to select a template, and will be asked to fill out relevant information.
You can see an example of this in action on the Swarm issues page: https://github.com/mcmonkeyprojects/SwarmUI/issues/new/choose
The selection looks like:
And each option gives a form like so:
When submitted it looks like so: <https://github.com/mcmonkeyprojects/SwarmUI/issues/29>
Note how it automatically adds the appropriate issue label, and formats the logs cleanly, and etc.
Obviously for the ComfyUI version I'm PRing here, it has Comfy-specific info rather than Swarm info. This includes a link to the Comfy Org Discord and to the ComfyUI Matrix Space.
Users will still have the option to "open a blank issue" if their needs are …

add issue templates for ComfyUI Issues Page

---

.github/workflows/test-browser.yml

As Github Action is free for public repo, enable CI test on push as well.

Enable browser tests on push

---

web/scripts/app.js

The issue was originally introduced by https://github.com/comfyanonymous/ComfyUI/pull/3112.
`ComfyApp.loadGraphData` accepts 4 positional arguments, with the last one being the fileName string. This PR fixes 2 call sites that passing fileName as the 3rd argument.
@pythongosssss PTAL

Fix loadGraphData func call

---

.github/workflows/windows_release_dependencies.yml
.github/workflows/windows_release_nightly_pytorch.yml
.github/workflows/windows_release_package.yml

LZMA2 is a variant of LZMA, it uses significantly more RAM, and ~70% faster (trade space for time).
[My test](https://github.com/YanWenKun/ComfyUI/actions/workflows/windows_release_package.yml) result:
```
-m0=lzma2 -mx=5 -mfb=32 -md=16m -ms=on -mf=BCJ2
8m 53s 
1.39 GB package
-m0=lzma2 -mx=7 -mfb=64 -md=32m -ms=on -mf=BCJ2
10m 30s 
1.36 GB package
-m0=lzma2 -mx=8 -mfb=64 -md=32m -ms=on -mf=BCJ2
10m 48s 
1.36 GB package
```
I didn't test `-mx=9 -mfb=64 -md=64m`, the gain would be marginal.
RAM usage on GitHub Actions looks totally fine.
I've opted for `-mx=8` in the commit.
Underneath is simply a node.js runtime version bump from 16 to 20. Tested and confirmed no issues to be concerned about.

Fine-tuning GitHub Actions

---

custom_nodes/example_node.py.example

This change includes corrections for several spelling errors in the `example_node.py.example` file.
These were previously raised by #3157, but they missed a few deeper in the file.

Fix several typos in example_node.py.example

---

comfy/cli_args.py
folder_paths.py
main.py
nodes.py

Loading custom node can greatly slow startup time. During development/testing of ComfyUI, it is often better to use an environment that no custom node is loaded.
This PR adds a `--no-custom-node` flag to allow users/developers skip loading of custom node without removing/renaming the custom_node directory.

Add `--no-custom-node` cmd flag

---

custom_nodes/example_node.py.example

It looks like support for this feature was added in #354 
Supplement example files to improve discoverability of this feature

Add example for how to add custom API routes

---

server.py

This is a fix to #3465 for LoadImage node. Behavior also generalizes to preventing duplication of existing files. 
Adds function compare_image_hash to do a sha256 hash comparison between an uploaded image and existing images with matching file names. 
This changes the behavior so that only images having the same filename that are actually different images are saved to input with increment, existing images are instead now opened instead. 
Currently, exact duplicates with the same filename are resave saved with an incremented filename in the format:
filename (i).ext 
with the code: 
```
while os.path.exists(filepath): 
filename = f"{split[0]} ({i}){split[1]}"
filepath = os.path.join(full_output_folder, filename)
i += 1
```
This commit changes this to include a sh256 hash comparison: 
``` …
```

Fix to #3465. Prevent, resaving of duplicate images if overwrite not specified

---

comfy/sd.py

When using `CheckpointSave` with `--force-channels-last`, there's an error: https://github.com/comfyanonymous/ComfyUI/issues/3923
From tensors not being contiguous, as they can't be saved.
This change forces all tensors to be contiguous when saving.
Have validated that:
- This works properly without errors both with and without force-channels-last
- the resultant files are identical
- the resultant files work regardless of whether channels last is set or not
When not using channels-last, the `contiguous()` call is effectively a no-op as the tensors will already be contiguous

fix non-contiguous tensor saving (from channels-last)

---

web/scripts/changeTracker.js

This `onNodeAdded` hook fixed #3885 well but it's running unnecessarily for every node in the workflow on startup. It's having a noticeable effect on startup time. This change adds check for `app.configuringGraph` flag to tell if the graph is loading or not.

Skip state check hook on first load

---

nodes.py

Related PR: #3943
Previously the module name of imported custom node is set as filename / directoryname, which can cause potential name conflict.
Imagine you have both `comfy_extras/audio_nodes.py` and `custom_nodes/audio_nodes/`. They both resolve to the same module name `audio_nodes` which can cause issue.
This PR makes module name relative path to the ComfyUI root folder so that this situation does not happen.
I can add some unit tests if the unit test infrastructure setup in https://github.com/comfyanonymous/ComfyUI/pull/3897 is merged.

Use relative path for custom/extra node module name

---

web/scripts/app.js

Same issue and same fix as #3918. This one is preventing the view from being restored when refreshing page. 
`loadGraphData`:
https://github.com/comfyanonymous/ComfyUI/blob/bb663bcd6c81a4395100c5f8527a221037d366f8/web/scripts/app.js#L1852-L1859
The call to `loadGraphData` when trying to restore workflow:
https://github.com/comfyanonymous/ComfyUI/blob/bb663bcd6c81a4395100c5f8527a221037d366f8/web/scripts/app.js#L1601-L1602
`workflowName` can be empty string when not using saved workflow, making restore_view false implicitly.

Fix loadGraphData call during restore

---

comfy/model_patcher.py
comfy/samplers.py

Hello!
I am submitting this pull request to add an iterable pre-CFG function entry in the model options.
This modification will enable reworking the predictions before the CFG function, allowing for a wide range of possibilities.
For example, in [this node](https://github.com/Extraltodeus/Uncond-Zero-for-ComfyUI/blob/28ef8d78cf7c54cb6b73a8cb6bf70a37ef15816f/nodes.py#L23), I subtract something from the previous step to make everything sharper. It would be convenient to be able to do it beforehand as it is not required to do this particular modification within the CFG function.
Additionally, this will allow adding "on the fly" options like perp-neg without requiring a guider. The theoretical function could modify the predictions as needed and then return them seamlessly, enabling this …

Add sampler_pre_cfg_function

---

nodes.py
server.py

This PR add node class's `RELATIVE_PYTHON_MODULE` to node def object returned by `/object_info` API endpoint. `RELATIVE_PYTHON_MODULE` is the relative python module path against the project root, e.g. `custom_nodes.foo`
This will help show the node belongs to which custom node pack in the redesigned node search box. https://github.com/Comfy-Org/ComfyUI_frontend/pull/83
- `cd tests-ui/`
- `npm i`
- `npm test:generate`
- Inspect `tests-ui/data/object_info.json`
Some examples:
```json
"name": "CheckpointLoaderSimple",
"display_name": "Load Checkpoint",
"python_module": "nodes", <------
"category": "loaders",
"output_node": false
```
```json
"name": "ResizeMask",
"display_name": "ResizeMask",
"description": "\nResizes the mask or batch of masks to the specified width and …
```

Add python_module to node info

---

.github/workflows/stable-release.yml

- Create a Github Release based on newly created tags starting with `v*`
- Create standalone windows builds for matrix of Cuda 12.1, Cuda 11.8, Python 3.12.2, Python 3.11.8.
- Not using cache so everything can run together

Add Github Workflow for releasing stable versions and standalone bundle.

---

web/scripts/ui/menu/workflows.js
web/style.css

Right click on an image, there should now be a "Send to workflow" option, listing all your saved workflows.  
You can choose one from here, or the current workflow.  
If a workflow has multiple LoadImage nodes, you can choose the default by including "Input" in the title of the node, else you'll get a prompt to choose which node to use.
Have an unsaved workflow, close it, previously the dialog was misaligned horizontally
May help resolve some issues with other nodes  
Run this to test adding extra elements around the canvas, previously this would totally break the canvas:
```
(() => {
var el = (txt, bd = "red", bg = "black") => {
var t = document.createElement("div");
t.style.background = bg;
t.style.border = "5px solid " + bd;
t.style.minWidth = "100px";
t.style.minHeight = "100px"; …
```

New menu fixes - fix send to workflow

---

web/extensions/core/uploadAudio.js

The audio player widget is breaking when a preview format is specified. See [Comfy-Org/ComfyUI_frontend#141](https://github.com/Comfy-Org/ComfyUI_frontend/issues/141). When no preview format is set, `getPreviewFormatParam()` returns `""` so it doesn't cause an error.
I just removed the preview param from the widget's request to api/view, because I don't think audio previews will be implemented.

Disable audio widget trying to get previews

---

web/extensions/core/uploadAudio.js

Currently the LoadAudio node always loads default file, even when a file is specified in the workflow being loaded. See [Comfy-Org/ComfyUI_frontend#85](https://github.com/Comfy-Org/ComfyUI_frontend/issues/85) 
The `widgets_values` are not set when the audio widget is created. So I added `onGraphConfigured` callback which sets the widget value.

LoadAudio restores file value from workflow

---

execution.py

Timestamp is necessary for the frontend to display the duration of a workflow task. The timestamp cannot be calculated on client side on receving these messages as the persisted value for `/history` endpoint need to have the timestamp as well for correct history item duration display.
This PR also adds a `execution_success` message to mark the successful end of the task.

Add timestamp to execution messages

---

web/scripts/api.js

Supress the warning on unhandled message type in the frontend. Continuation of https://github.com/comfyanonymous/ComfyUI/pull/4076

Supress frontend exception on unhandled message type

---

comfy/cldm/cldm.py
comfy/cldm/control_types.py
comfy_extras/nodes_controlnet.py

Related Issue: 
https://github.com/comfyanonymous/ComfyUI/issues/4068
This PR adds a more meaningful error message when user pick the wrong controlnet model.
Repro workflow:
[controlnet_union_tile_xl.json](https://github.com/user-attachments/files/16334046/controlnet_union_tile_xl.json)

Add error message on unsupported control type in union controlnet

---

web/scripts/changeTracker.js

Fixes an issue where under certain conditions, the ComfyUI custom undo / redo functions would not run when intended to.
When trying to undo an action like deleting several nodes, instead the native browser undo runs - e.g. a `textarea` gets focus and the last typed text is undone.  Clicking outside the `textarea` and hitting `ctrl + z` again just keeps doing the same thing.
This could use a slight refactor, but I went with "minimal changes".

Fix "undo" incorrectly undoing text input

---

README.md

This link always points to the latest release.

Change windows standalone URL to stable release.

---

comfy_extras/nodes_custom_sampler.py

Adding dpmpp_2s_ancestral as custom sampler node to enable its use with eta and s_noise when using custom sampling.
This sampler has some advantages versus using SDE when doing inference with certain turbo hybrid models and being able to control eta and s_noise seemed obvious

Add dpmpp_2s_ancestral as custom sampler

---

web/scripts/ui/menu/menu.css

Made active workflow entry use primary fg color. Before / After:
I tested it on all the built-in color themes.

Active workflow use primary fg color

---

comfy_extras/nodes_pag.py
comfy_extras/nodes_sag.py

Since the introduction of cfg++ which uses very low cfg value, a step of 0.1 in SAG scale might be too high for finer control. Even SAG of 0.1 can be too high when cfg is only 0.6, so I change the step to 0.01.

Lower SAG scale step for finer control

---

comfy/text_encoders/flux.py
comfy/text_encoders/sd3_clip.py

Spelling was wrong which made it inconsistent with rest of related code and might cause future confusion
Correcting it early will avoid custom nodes from adapting it and if any of the ones in registry already did they are unlikely to be many right now.

Correct spelling 'token_weight_pars_t5' to 'token_weight_pairs_t5'

---

server.py

If you switch frontend versions while there is no active connection to the server, the browser will use the cached index.html on startup and fail to load. This can happen if you try to use the new frontend for the first time and start the program before opening the webpage. See:
- Comfy-Org/ComfyUI_frontend#291
In general, I think it's better to not cache the entry point.

Don't cache index.html

---

.github/workflows/stable-release.yml

Also changed: 
- Added workflow input for git tag
- Clone taesd with depth 1 to reduce file download from 122mb to 37mb
Tested in Mirror Repo: https://github.com/Comfy-Org/ComfyUI-Mirror/actions/runs/10257690631

Stable release uses cached dependencies

---

.github/workflows/test-browser.yml

Downgrade browser test CI to use python 3.8 to capture compatibility issues. Any errors during startup will be capture and reported in the browser test CI.

Change browser test CI python to 3.8

---

folder_paths.py

This PR adds type hints to function declarations and some variables in folder_paths.py to improve the developer experience. If its OK I would add type hints to more parts of the codebase in future PRs.

Add type hints to folder_paths.py

---

.github/workflows/pullrequest-ci-run.yml

When the 'Run-CI-Test' label is added to a PR, it will be tested by the CI, on a small matrix of stable versions.

add GitHub workflow for CI tests of PRs

---

.github/workflows/pullrequest-ci-run.yml

'_target' allows secrets to pass through, and we're just using the secret that allows uploading to the dashboard and are manually vetting PRs before running this workflow anyway

PullRequest CI Run: use pull_request_target to allow the CI Dashboard to work

---

comfy/controlnet.py
comfy/latent_formats.py
comfy/ldm/hydit/controlnet.py
comfy/ldm/hydit/models.py
comfy_extras/nodes_hunyuan.py

this pr add support for HunYuanDit ControlNet.
https://huggingface.co/Tencent-Hunyuan/HYDiT-ControlNet-v1.2/tree/main
[hunyuan-controlnet-workflow.json](https://github.com/user-attachments/files/16513972/hunyuan-controlnet-workflow.json)

feat: add support for HunYuanDit ControlNet

---

comfy/controlnet.py

The original author intended to design two weighting methods for running controlnet: constant and decay. However, the default is now decay, which prevents the correct invocation of controlnet's weights in the conventional manner. It is recommended that the standard controlnet components continue to use constant control. Special controls like Linear_UP should be placed in nodes similar to 'advanced controlnet', providing additional control options, either constant or Linear_UP. I have trained multiple controlnet models and three HunyuanDiT controlnet models. Using the Linear_UP method to invoke the model results in the weights not being correctly expressed.

Update controlnet.py to fix the default controlnet weight as constant

---

comfy/utils.py

This PR will add full LoRA support for Diffusers based LoRAs. The only weights that do not match up correctly are.
```
("guidance_in.out_layer.bias", "time_text_embed.guidance_embedder.linear_2.bias"),
("vector_in.out_layer.bias", "time_text_embed.text_embedder.linear_2.bias"),
```  
The diffusers versions of those weights differ from the official implementation for some reason. However, this will not affect LoRA support as LoRAs generally do not use bias.

FLUX: Added full Diffusers mapping for FLUX.1 schnell and dev. 

---

comfy/sd.py

In comfy-mecha the Merger node creates a state dict in memory without passing by the file system. Currently I need to duplicate the function `comfy.sd.load_checkpoint_guess_config()` to the nodepack code because it takes a path as input but I need to pass a state dict instead.
The alternative solution to copying the function is to temporarily monkey patch `comfy.utils.load_torch_file`, but this solution is as brittle as copying the function to the nodepack code.
I think the best solution is to create a new function `load_state_dict_guess_config()` and keep the other one for backwards compatibility or ease of use.
I have been told that some functions under `comfy.sd` are deprecated, if this one is also deprecated then I would appreciate some guidance on the best way to do this!

alternative to `load_checkpoint_guess_config` that accepts a loaded state dict

---

.github/workflows/pullrequest-ci-run.yml

Updates the Pull Request CI action that triggers when you add the `Run-CI-Test` to now automatically comment a link to the CI dashboard (I think yoland requested this somewhere last week)
(also use_prior_commit because the the final commit on a PR in a github action is an automerge instead of the real last commit)
Bot messages show up like so:
And will have a message like:
> (Automated Bot Message) CI Tests are running, you can view the results at https://ci.comfy.org/?branch=4260%2Fmerge
(Yes it's `context.issue.number` in the github-script but `github.event.pull_request.number` in the workflow, don't even ask me why idek, but I did test this and that's how it has to be to work)

Automatically link the Comfy CI page on PRs

---

.gitignore

Because macos dont have prebuild packages we have to build it from the repo.
In macos OS create extra usless files that we don't want to commit

Add `DS_Store` to gitignore

---

comfy/ldm/flux/controlnet_xlabs.py
comfy/ldm/flux/model.py

This updates the Flux model with the possibility of processing InstantX style Flux controlnet residuals which apply to both single and double blocks. 
I would like to have this merged since I have ported the InstantX union controlnet to comfyui, which produces output in this format. I will first distribute it as a custom node but can later create a pull request to merge it as well.

Add Flux model support for InstantX style controlnet residuals

---

custom_nodes/example_node.py.example
server.py

This PR adds optional `DEPRECATED` / `EXPERIMENTAL` fields to the node definition class. 
Node developers should be able to use this flag to mark their nodes as deprecated/experimental instead of inventing custom ways to hide node in search result in the frontend.

Add optional deprecated/experimental flag to node class

---

server.py

For example `wget http://127.0.0.1:8188/models/checkpoints`  returns `["sd_xl_base_1.0.safetensors", "sd_xl_refiner_1.0.safetensors", "v1-5-pruned-emaonly.ckpt"]`
the `if not folder in folder_paths.folder_names_and_paths:` check is a pretty tight whitelist, that's only path types defined explicitly by model-paths config or custom nodes -- anything that's not a predetermined path yields a 404
The existing route `/embeddings` can arguably be deprecated or removed in favor of `/models/embeddings` to yield near-identical results (but with file extensions added)

add a get models list api route

---

comfy/ops.py

When generating images with fp8_e4_m3 Flux and batch size >1, using --fast, ComfyUI throws a "view size is not compatible with input tensor's size and stride" error pointing at the first of these two calls to view.
As reshape is semantically equivalent to view except for working on a broader set of inputs, there should be no downside to changing this. The only difference is that it clones the underlying data in cases where .view would error out. I have confirmed that the output still looks as expected, but cannot confirm that no mutable use is made of the tensors anywhere.

Replace use of .view with .reshape

---

execution.py
tests/inference/test_execution.py
tests/inference/testing_nodes/testing-pack/specific_tests.py
tests/inference/testing_nodes/testing-pack/stubs.py

This change fixes a bug where non-constant values could be passed to the IS_CHANGED function. This would result in workflows taking an extra execution before they acted as if they were cached.
The actual change is like 4 characters -- the rest is adding unit tests.

Fix a bug where cached outputs affected IS_CHANGED

---

comfy/model_management.py

This code automatically forces upcasting attention for MacOS versions 14.5 and 14.6. My computer returns the string "14.6.1" for `platform.mac_ver()[0]`, so this generalizes the comparison to catch more versions.
I am running MacOS Sonoma 14.6.1 (latest version) and was seeing black image generation on previously functional workflows after recent software updates. This PR solved the issue for me.
See comfyanonymous/ComfyUI#3521
This preempts cli arg `--force-upcast-attention`. I have not tested other versions of MacOS, and this may need to be modified to affect future versions beyond 14.6 as well.

Generalize MacOS version check for force-upcast-attention

---

execution.py

#2666 introduced an enum status indicator as result, which replaces previous `self.success` flag. However the previous `self.success` flag is send as `status_str` to the frontend via API. This causes frontend assigns wrong task status. This PR fixes this issue.

Fix task.status.status_str caused by #2666

---

comfy/model_detection.py

Open this PR to close #4563
This will fully support functionality and allow reusability for single-file inpainting checkpoints for SD15 which have been converted to diffusers-based  format.
Looking forward to the feedback!

Added SD15_Inpaint_Diffusers model config for Model_detection.py

---

comfy/model_management.py

Per the upstream policy outlined [here](https://dev-discuss.pytorch.org/t/intel-gpu-enabling-status-and-feature-plan/2389), Intel will be making available their XPU support into Pytorch proper with version 2.5 which includes their new Xe GPUs and therefore, Intel's Extension for Pytorch (IPEX) will become optional. In order to prepare for this, I am updating how ComfyUI checks for IPEX support. Complicating this is the fact that in the [Pytorch 2.4 release notes](https://pytorch.org/blog/pytorch2-4/), Intel has made XPU support available as a prototype for anyone that makes a custom build of v2.4 with some environment and command arguments passed in.
Therefore, this support was a bit tricky to implement but after doing some research, it seems like making similar changes made to …

Pytorch XPU check overhaul and other small XPU backend changes

---

comfy_execution/caching.py
tests/inference/test_execution.py

Currently, if a graph partially fails validation (i.e. some outputs are valid while others have links from missing nodes), the execution loop could get an exception resulting in server lockup.
This isn't actually possible to reproduce via the default UI, but is a potential issue for people using the API to construct invalid graphs.

[Bug #4529] Fix graph partial validation failure

---

server.py

Adding a new field `download_path`. Needed by frontend to report progress for all files being downloaded.

Add download_path for model downloading progress report.

---

app/frontend_management.py
tests-unit/app_test/frontend_manager_test.py

Closes https://github.com/comfyanonymous/ComfyUI/issues/4557
If frontend zip download failed, properly cleanup the empty dir.

Cleanup empty dir if frontend zip download failed

---

.ci/windows_base_files/README_VERY_IMPORTANT.txt
notebooks/comfyui_colab.ipynb
script_examples/basic_api_example.py
script_examples/websockets_api_example.py
script_examples/websockets_api_example_ws_images.py

RunwayML took down their HF page https://huggingface.co/runwayml
That was what hosted SDv1.5
To keep the file accessible for legacy usages, I've reuploaded to the Comfy-Org HF page: https://huggingface.co/Comfy-Org/stable-diffusion-v1-5-archive/blob/main/v1-5-pruned-emaonly.safetensors
This PR swaps the links within comfy to the archive copy
The reupload is hash identical (`6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa`) to the original RunwayML safetensors file.
For obvious reasons, I've uploaded the pruned-emaonly-safetensors, not the 7GiB unpruned copies nor the ckpt pickle files. This PR swaps the extension in the few existing references to match.

swap legacy sdv15 link

---

nodes.py

modified `init_extra_nodes` function to return the `import_failed` list. This change allows the upstream callers (`main`) to decide about the extra node state.
e.g., fail if a node failed to load; as some custom nodes might leave comfy in a bad state

feat: return import_failed from init_extra_nodes function

---

.github/workflows/stale-issues.yml

This will run daily, scan any issues marked "User Support", and mark them stale if they have had no activity for 30 days (1 month). A stale issue allows 7 days for a user to reply to un-stale it.
if there is no reply, it will look like this:
If there is a reply within the 7 day period, it will look like this:
This lets us start cleaning up the old "User Support" issues. Bugs and feature requests will remain open. Anything assigned to a developer or a milestone will remain open.
After it's ran a bit, I'll run a separate process to start marking the old unlabeled issues into "User Support" to let them all either autoclose or be manually kept open, and then we can wipe the backlog of thousands of issues down to a much more manageable size by the end of it.

add github action to automatically handle stale user support issues

---

.github/workflows/stale-issues.yml

The quick text edit to the PR @ https://github.com/comfyanonymous/ComfyUI/pull/4683 included a `'` symbol which broke the singlequotes, so the stale-issues workflow wasn't running, this fixes that.

fix typo in stale-issues

---

comfy/cli_args.py
latent_preview.py

Adds launch argument to be able to configure live preview size which is quite desirable on large monitors.
The default of 512 will still persist if launch argument `--preview-size` followed by an integer is not set.
Images display workflow of it not being used in first one and second is when set to 768 while generating a 1024 image.

Make live preview size a configurable launch argument

---

comfy/ldm/modules/diffusionmodules/openaimodel.py

The purpose of this addition is to support FancyVideo within AnimateDiff-Evolved. Eventually also adding a helper function to store these patches on ModelPatcher's model_options would be good, but this will suffice for now based on my needs.

Add emb_patch support to UNetModel forward

---

comfy_execution/caching.py

As suggested by @ltdrdata, we can automatically consider nodes that take
the UNIQUE_ID hidden input to be NOT_IDEMPOTENT. This will likely just save
some custom node authors from frustration as they try to figure out why nodes
are sharing output.

Nodes using UNIQUE_ID as input are NOT_IDEMPOTENT

---

comfy/samplers.py

Doing `import scipy` does not import `scipy.stats` resulting in the following error when running in API mode:
```
!!! Exception during processing !!! module 'scipy' has no attribute 'stats'
Traceback (most recent call last):
File "[redacted]i/ComfyUI/execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "[redacted]/ComfyUI/execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "[redacted]/ComfyUI/execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File …
```

Fix scipy.stats import when using beta scheduler on API

---

execution.py
tests/inference/test_execution.py

This change resolves an error when a node with OUTPUT_IS_LIST=(True,) receives an ExecutionBlocker. I've also added a unit test for this case.

Fix error with ExecutionBlocker and OUTPUT_IS_LIST

---

app/user_manager.py

fix: url decode filename from API

---

folder_paths.py

Example:
Just set filename prefix to eg `%year%-%month%-%day%/ComfyUI`,
this will save as eg `ComfyUI/output/2024-07-15/ComfyUI_00001_.png`
Supercedes #3402 but with cleaner code and a more configurable usage
The benefit is, of course, more ways to organize files.
Arguably more vars would be useful, eg prompt and wotnot, but that would require text processing nodes linking together, which is possible with some custom node packs.
Date/time however is easily inserted directly.
I also added an `if "%" in filename_prefix:` guard to prevent redundant calculations when the user doesn't want them.

allow current timestamp in save image prefix

---

.github/workflows/test-unit.yml

The unit tests CI is accidentally removed in https://github.com/comfyanonymous/ComfyUI/pull/4316.
This PR adds back the CI action to run unit tests.

Add back CI action for tests-ui

---

main.py
tests-unit/main_test.py
tests-unit/utils/extra_config_test.py
utils/extra_config.py

Expand base path like: `~/Library/Application\ Support` to make it easier to add overrides.
Added this line to `load_extra_path_config`: 
```
base_path = os.path.expanduser(base_path)
```
Refactored `load_extra_path_config` into another file to make it easier to unit test. When you import it from the `main.py` in a unit test, it imports all the other things. This causes things to break because unit tests are not run with CUDA enabled pytorch.

Expand user directory for basepath in extra_models_paths.yaml

---

tests-unit/comfy_test/folder_path_test.py

All past 30 min of comtts are done on the top of Mt Fuji By Comfy, Robin, and Yoland
All other comfy org members died on the way
Introduced unit tests to verify the correctness of various folder path utility functions such as `get_directory_by_type`, `annotated_filepath`, and `recursive_search` among others. These tests cover scenarios including directory retrieval, filepath annotation, recursive file searches, and filtering files by extensions, enhancing the robustness and reliability of the codebase.

[🗻 Mount Fuji Commit] Add unit tests for folder path utilities

---

tests-unit/utils/extra_config_test.py
utils/extra_config.py

Expand variables in base path. Environment variables are more commonly used on Windows, such as `%APPDATA%` for storing user specific data.

Expand variables in base_path for extra_config_paths.yaml.

---

app/user_manager.py
comfy/cli_args.py
folder_paths.py
main.py

`python main.py --user-directory /path/to/directory`

Add cli arg to override user directory

---

comfy_execution/caching.py

`CacheKeySetInputSignature.get_immediate_node_signature` is called multiple times for the same node as ancestors of different nodes.
Most nodes are fine, but when there are time-consuming operations in `class_def.INPUT_TYPES()`, such as `get_filename_list`, the performance of `cache.set_prompt` becomes quite bad on machines with poor disk performance.
On one of my devices, `set_prompt` of `caches.outputs` and `caches.ui` took 500+ms before modification, and it would be worse if there were more time-consuming nodes. This PR reduces the time to 80ms on average

Reduce repeated calls of get_immediate_node_signature in cache

---

app/user_manager.py
tests-unit/prompt_server_test/user_manager_test.py

Dealing with os separator is quite painful in the frontend. This PR normalizes the path returned by `/userdata` endpoint to always use `/` as file separator.

Normalize path returned by /userdata to always use / as separator

---

comfy_execution/graph.py

`ExecutionList` adds nodes and links recursively. There are 3 recursive calls per node in a chain of nodes, which means you run into recursion limits at around 300 linked nodes (default recursion limit is 1000 in CPython).
```
File "C:\Dev\ComfyUI\execution.py", line 492, in execute
execution_list.add_node(node_id)
File "C:\Dev\ComfyUI\comfy_execution\graph.py", line 125, in add_node
self.add_strong_link(from_node_id, from_socket, unique_id)
File "C:\Dev\ComfyUI\comfy_execution\graph.py", line 153, in add_strong_link
super().add_strong_link(from_node_id, from_socket, to_node_id)
File "C:\Dev\ComfyUI\comfy_execution\graph.py", line 102, in add_strong_link
self.add_node(from_node_id)
File "C:\Dev\ComfyUI\comfy_execution\graph.py", line 125, in add_node
self.add_strong_link(from_node_id, …
```

Fix RecursionError for (very) large graphs

---

comfy_execution/caching.py

Solved #4882 #4914 . 
This PR is an improvement of #4871 . By reducing `INPUT_TYPES` calls and reduced `set_prompt` performance for `caches.outputs` and `caches.ui` in a way that does not destroy the execution cache.

Reduce repeated calls of INPUT_TYPES in cache

---

comfy_extras/nodes_hypernetwork.py
comfy_extras/nodes_photomaker.py
comfy_extras/nodes_sd3.py
comfy_extras/nodes_upscale_model.py
comfy_extras/nodes_video_model.py
folder_paths.py
nodes.py

I see a lot of reports of `'NoneType' object has no attribute 'lower'` meaningless error, that internally just means... a model name is wrong but prompt validation passed or was skipped (I'm not sure why? Normally prompt validation handles this, but i see the error report a lot), so this PR adds an error check with a clear error message if this ever hits.
I explicitly separated the error check function to be only cases that don't have their own `if x is None`, particularly loader nodes that pass the output of `get_full_path` directly into a `load_torch_file`

add simple error check to model loading

---

comfy/samplers.py
server.py

Adds a route to list all valid model types as a JSON list.
This will benefit those working with the api as it will allow for an easy way to list model types.
I have seen people in the past request a feature like this ( such as #830 ) and this adds it in a safe and simple way.

Add route to list model types

---

folder_paths.py
server.py

This is based on the same work as https://github.com/comfyanonymous/ComfyUI/pull/4968 but a much simpler and more agreeable approach: when object_info is hit, use a strong cache to ensure each model list is read exactly once, rather than once per node - ie skip the cache validation *within the current call*, until the next object_info hit.
Currently only `/object_info` triggers a cache clear, but it can be made to apply to `/object_info/{x}` and `/models/{x}` as well if desired. (I'd argue that strong caching in those subcalls is desired, as only `/object_info` is intended as a 'refresh' - though also a separate dedicated `/refresh` route would be preferred imo)
For this code I made a nice lil subclass helper doodle to reduce the amount of chaotic global variable pollution in that file a …

very simple strong-cache on model list

---

extra_model_paths.yaml.example
folder_paths.py
tests-unit/utils/extra_config_test.py
utils/extra_config.py

Very simple, just add `is_default: true` in a block within `extra_model_paths.yaml` and it will insert those folders at the front of the list rather than the end, preceding even the ComfyUI default folder.
This allows automatic installations to define a clear default that will be used particularly for things like the model downloader (which would then be in turn user overridable in the frontend settings to pick a preference when desired)

add 'is_default' to model paths config

---

api_server/routes/internal/internal_routes.py

returns a json maps of folder paths
Looks something like:
```
{
"checkpoints": [
"Z:\\Stable-Diffusion",
"C:\\GitHub\\ComfyUI_windows_portable\\ComfyUI\\models\\checkpoints",
"C:\\GitHub\\ComfyUI_windows_portable\\ComfyUI\\output\\checkpoints"
],
"configs": [
"C:\\GitHub\\ComfyUI_windows_portable\\ComfyUI\\models\\configs"
],
"loras": [
"Z:\\Lora",
"C:\\GitHub\\ComfyUI_windows_portable\\ComfyUI\\models\\loras",
"C:\\GitHub\\ComfyUI_windows_portable\\ComfyUI\\output\\loras"
],
etc...
}
```
this is for the frontend model downloader to be able to see available paths and have the user select one
pairs with https://github.com/comfyanonymous/ComfyUI/pull/4979 to allow config to set which one comes first

add internal /folder_paths route

---

comfy/k_diffusion/sampling.py
comfy/samplers.py
comfy_extras/nodes_custom_sampler.py

supposedly this scheduler helps ZSNR models, simple enough to add and doesn't just crash instantly, very "aggressive" scheduler though.. (initial values are very high and had to be clamped)

add laplace scheduler [2407.03297]

---

script_examples/websockets_api_example.py

After wasting a ton of time trying to do this a different way, it turned out to be extremely simple to pull off after I finally figured out that the start of the stream had an extra 4 bytes added to it, so the image data was at [8:] and not [4:]. I guess the websockets_api_example_ws_images.py example kind of addresses this with the images_output.append(out[8:]) line? But it's handled differently overall, so I'm not going to mess with that example file.
Here's an example of it working with a Gradio app:
Thanks @asagi4 for making me requestion my previous approach, causing me to do a bunch of digging!

Added to the websockets_api_example.py to show how to decode latent previews from the binary stream

---

script_examples/websockets_api_example.py
script_examples/websockets_api_example_ws_images.py

Within the examples scripts, it doesn't really do anything since they are one-shot scripts that end on completion, but if people build and expand off the scripts by adding in a function like:
```python
def get_prompt_images(prompt):
global preview_image #for storing latent previews
ws = websocket.WebSocket()
ws.connect("ws://{}/ws?clientId={}".format(server_address, client_id), timeout=5,)
images = get_images(ws, prompt)
outputs = []
for node_id in images:
for image_data in images[node_id]:
image = Image.open(io.BytesIO(image_data))
outputs.append(image)
ws.close()
return outputs
```
Then it's necessary to include the `ws.close()` since this function will get called mutliple times and because each time it's called, a new random `str(uuid.uuid4())` will be called. If they aren't closed …

Add ws.close() to the websocket examples

---

.github/workflows/test-unit.yml
tests-unit/folder_paths_test/filter_by_content_types_test.py
tests-unit/utils/extra_config_test.py

Add mac and windows runners. 
Compare paths in a cross-platform way.
Only test for mimetypes that are natively supported on every OS.

Run unit tests on Windows/MacOS as well.

---

comfy/k_diffusion/sampling.py
comfy/samplers.py

To close #4449 
Adapted from [official](https://github.com/CFGpp-diffusion/CFGpp/blob/3a6655dc9348ee544bc33956dc55d7d63ada2823/latent_diffusion.py#L831)'s implementation and modify some variable names.

Add dpmpp_2m_cfg_pp sampler

---

comfy/ldm/flux/model.py

This fixes torch.compile with GGUF on flux1. (Also might fix bf16 but I can't test on volta). Based on a quick test the results are 1:1.
Ref: https://github.com/city96/ComfyUI-GGUF/issues/118
- Changed `[...]` to `[:, :]` since we know how many dimensions `img_ids` has.
- Removed the addition since `img_ids` is zeros anyway
- Changed `[None]` to unsqueeze

Flux torch compile fix

---

folder_paths.py

This guy (points to self) managed to create a file called "nul"* in a windows checkpoints subdirectory. 
This caused all sorts of havoc with many nodes that needed the list of checkpoints when python tried to figure out the relative path to the file. So, might as well check for unexpected problems with computing the file paths here (esp. as this is already done for subdirectory paths in the code block after this one).
* Like CON and PRN, NUL is "special" and should not exist on a Windows filesystem. Supposedly it is not possible to create such a file. However, MINGW64 had no problem creating the file for me when I redirected to nul instead of /dev/null (which would have been correct for MINGW64).

Add a try/catch to skip special file_name values instead of failing to load a node.

---

comfy/model_management.py

As of the latest version of macOS (15.0.1), the `--force-upcast-attention` flag is required to fix a "black image" bug (#3521). Similar to #4548, this PR checks whether the macOS version is affected and automatically forces upcast attention.

Increase maximum macOS version to 15.0.1 when forcing upcast attention

---

app/frontend_management.py

Reduces the risk of errors like this:
By avoiding makings call to github API if the frontend is already downloaded locally for a specific version anyway. Only not-yet-installed versions or `latest` still makes github API calls this way.
The check is a very simple - if you're not default, and have a version starting with "v", you want a specific frontend version, so we can just check that specific folder exists, and use it if so.
Prior to this PR, this type of error could potentially happen at any time when launching comfy, from either GitHub API limits like the user above saw, or from network connectivity issues, or etc.
The API limit error risk was increased by the fact that the existing code reads a list of all versions by making multiple API calls in sequence, ie it may eat more API …

Frontend Manager: avoid redundant gh calls for static versions

---

server.py

Intermittent network issues during Websocket communication should not crash ComfyUi main process.

Ignore more network related errors during websocket communication.

---

app/frontend_management.py

Partially revert https://github.com/comfyanonymous/ComfyUI/pull/5152
In electron build, the downloaded file ownership can be taken by the electron app, and cause rename to fail.
```
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
[2024-10-25 17:14:15.902] [error] stderr: Using pytorch cross attention
[2024-10-25 17:14:17.258] [error] stderr: Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
[2024-10-25 17:14:17.452] [error] stderr: Downloading frontend(Comfy-Org_ComfyUI_frontend) version(1.3.22) to (D:\electron\assets\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.3.22.tmp)
[2024-10-25 17:14:18.642] [error] stderr: Failed to initialize frontend: [WinError 3] The system cannot find the path specified: …
```

Revert download to .tmp in frontend_management

---

comfy_extras/nodes_sd3.py

Enable skip layer guidance on SD3.5 - enhances guidance vector on specific feature levels.
Defaults implementation enhances attention into medium detailed structures - E.g. Hands.

SLG first implementation for SD3.5

---

comfy_extras/nodes_images.py
nodes.py

Feedback
-
Nodes menu has inconsistency in names, some with spaces between words, other not. i made some minor changes on our local installations (students project). This is something important for the next releases. The actual menu push developers to add their category into the top level, what is not the best option for the users to search for a specific category, if the category exists into various levels.
also, it must be considered that developers would have a guided structure to include their custom nodes packages into existing categories (until the node requires a new one) for consistency and easy search.
Mockup
-
By re-arranging the main node menu, we give to developers a way to inlude their custom nodes in a practical manner.
Pull request & future development
-
this first pull is …

Rename `ImageCrop` to `Image Crop`

---

comfy/extra_samplers/uni_pc.py

Recent Pythons warn about:
```
comfy/extra_samplers/uni_pc.py:19: SyntaxWarning: invalid escape sequence '\h'
"""Create a wrapper class for the forward SDE (VP type).
```
so make that docstring a raw string.

Avoid SyntaxWarning in UniPC docstring

---

app/user_manager.py
tests-unit/prompt_server_test/user_manager_test.py

This PR makes POST `/userdata/{file}` and POST `/userdata/{file}/move/{dest}` accept an extra optional param `full_info` so that the updated full file info (size and last modified timestamp) is returned to the caller. Without the param, the return value would be the file path string.
This can save the frontend an extra GET `/userdata` call to update the size and last modified info.

Allow POST `/userdata/{file}` endpoint to return full file info

---

comfy/ldm/flux/model.py

`torch.onnx.export` interprets `h_len - 1` as constant breaking dynamic shape import.

fix dynamic shape export

---

api_server/routes/internal/internal_routes.py
api_server/services/terminal_service.py
app/logger.py
server.py
tests-unit/server/routes/internal_routes_test.py

This updates the logging from using a MemoryHandler to overriding stdout/stderr in order to obtain all outputs, including progress bars. (Previously done here https://github.com/comfyanonymous/ComfyUI/pull/4664) 
Adds two new endpoints for the frontend
GET `/internal/logs/raw` - returns an array of the last 300 raw stdout/stderr entries and their timestamps, and the size of the terminal (required for accurate rendering)
POST `/internal/logs/subscribe` - Body: `clientId`: the socket id, `enabled`: if logs are being subscribed to send via websocket in a new event `logs`. 
The format of `/internal/logs` has slightly changed as it is no longer formatted via `logging` but just the outputs.
The `logs` event contains any entries since last flush and the terminal size if it has changed.
Events …

Live terminal output

---

comfy_extras/nodes_sd3.py
nodes.py

https://github.com/comfyanonymous/ComfyUI/discussions/5574

improve: add descriptions for clip loaders

---

main.py

concerning #5585
CUDA_VISIBLE_DEVICES is ignored for HIP devices/backend. Instead it uses HIP_VISIBLE_DEVICES. Setting this environment variable has no side effect for CUDA/NVIDIA so it can safely be set in any case and vice versa.

fix --cuda-device arg for AMD/HIP devices

---

api_server/services/terminal_service.py

os.get_terminal_size() can fail and causing logs to be unable to render in frontend

Add terminal size fallback

---

comfy_extras/nodes_lt.py

At length=1, the LTX model can do txt2img and img2img with no other changes required.

Change EmptyLTXVLatentVideo minimum length from 9 to 1

---

comfy/model_management.py
comfy/model_patcher.py
execution.py
main.py

These changes makes the memory management less fragile (much less chances of custom nodes/extensions/future code changes breaking it) and should remove the noticeable delay when changing workflows with large models.
The reason I'm making a PR with these changes so people can test it and make sure there's no obvious bugs before I merge it.

Improved memory management.

---

comfy_execution/validation.py
execution.py
tests-unit/execution_test/validate_node_input_test.py

Requested by @Kosinkadink 
Supports running workflow with union types, i.e. types separated with comma like `T1,T2,...`. The frontend code (litegraph) already supports the connection of it. It's the backend validation failing blocking this feature to be properly used.
Before:
After:
[UnionTest.json](https://github.com/user-attachments/files/17937955/UnionTest.json)
Required custom nodes:
- https://github.com/Comfy-Org/ComfyUI_devtools
- https://github.com/WASasquatch/was-node-suite-comfyui

Add union link connection type support

---

utils/extra_config.py

This PR updates the `load_extra_path_config` function to properly handle relative paths in YAML configuration files.
Relative paths are now resolved relative to the directory containing the YAML file.
- Added a check using `os.path.isabs` to determine whether a path is relative or absolute.
- Relative paths are resolved using the directory of the YAML file when `base_path` is not specified.
This PR introduces minimal changes and only affects cases where `base_path` is not set. 
As far as I know, there are no breaking changes.

resolve relative paths in YAML configuration for extra model paths

---

comfy_extras/nodes_hooks.py

Working on a tutorial for hooks, I realized I should have ported this node in from ADE earlier. It's a built-in way of generating multiple keyframes that will also help me write the tutorial.

Add Create Hook Keyframes Interp. Node

---

comfy_execution/validation.py
execution.py
tests-unit/execution_test/validate_node_input_test.py

- Relands #5806
- Resolves https://github.com/comfyanonymous/ComfyUI/issues/5890
- Resolves comment in issue https://github.com/comfyanonymous/ComfyUI/issues/5890#issuecomment-2515974525
- Now uses almost(*) identical logic to former behaviour if types match:
- If types matched before this PR, they will still match
- If they _do not_ match:
- Check both types are string
- Perform new union type check
(*) Only changes are one function call and a `not not` conversion

Reland union type

---

comfy/ops.py

Currently, if you attempt to use a SDXL *(PonyXL somehow works...)* checkpoint with `fp8_ops`, it will cause `NaN` in the latent, which results in black images. This is caused by the `input` overflowing the value range of `float8_e4m3fn`, and can be fixed by adding a clamp with the range set to `-448` ~ `448`, without too much quality degradation.
> **Source for the Range**: https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html <br>
> - **E4M3** - it consists of 1 sign bit, 4 exponent bits and 3 bits of mantissa. It can store values up to **+/-448**
- Added `torch.clamp` at [L272](https://github.com/comfyanonymous/ComfyUI/blob/v0.3.7/comfy/ops.py#L272)
- #4572 
<hr>
- Generate a `1024x1024` image using **SDXL** checkpoint on a **RTX 4070 Ti S**:
- …

Fix SDXL generating black images when using --fast (fp8_ops)

---

.github/workflows/test-ci.yml

- Commented out Windows OS from the CI matrix in test-ci.yml.
- Removed the test-win-nightly job to streamline testing on macOS and Linux only.
- Adjusted the matrix strategy to focus on Python versions and CUDA compatibility without Windows support.

Update CI workflow to remove Windows testing configuration

---

.ci/update_windows/update.py
comfy/cldm/cldm.py
comfy/controlnet.py
comfy/extra_samplers/uni_pc.py
comfy/hooks.py
comfy/k_diffusion/deis.py
comfy/ldm/audio/dit.py
comfy/ldm/aura/mmdit.py
comfy/ldm/genmo/joint_model/asymm_models_joint.py
comfy/ldm/hydit/controlnet.py
comfy/ldm/hydit/models.py
comfy/ldm/modules/attention.py
comfy/ldm/modules/diffusionmodules/model.py
comfy/ldm/util.py
comfy/model_base.py
comfy/model_detection.py
comfy/model_management.py
comfy/sampler_helpers.py
comfy/samplers.py
comfy/sd.py
comfy/sd1_clip.py
comfy/supported_models.py
comfy/text_encoders/t5.py
comfy_extras/nodes_hypertile.py
comfy_extras/nodes_model_advanced.py
fix_torch.py
ruff.toml
server.py
tests/inference/testing_nodes/testing-pack/util.py

Based on https://github.com/comfyanonymous/ComfyUI/pull/5987
This PR enforces F841 (Unused variable).

Lint all unused variables

---

main.py

`current_time` in line 124 is referenced before assignment. Logic wise this can never happen as `need_gc` is set to `False`, but it is triggering the static check on F821.

Lint and fix undefined names (2/N)

---

comfy/ldm/audio/autoencoder.py
comfy/ldm/audio/dit.py
comfy/ldm/models/autoencoder.py
comfy/ldm/modules/sub_quadratic_attention.py

This PR marks several undefined refs ignored. They are in not-executed dead code sections otherwise we should receive error reports from users. Proper cleanup would require more linter rules to be enabled / larger scale refactor.

Lint and fix undefined names (3/N)

---

comfy/gligen.py
comfy/ldm/audio/dit.py
comfy/ldm/models/autoencoder.py
comfy/ldm/modules/diffusionmodules/mmdit.py
ruff.toml

This PR is the first PR that fixes most obvious undefined names errors.

Lint and fix undefined names (1/N)

---

server.py

This PR prevents html/htm/js/css files being served as web page for code execution.
- Put a index.html file with random content in `ComfyUI/output` folder
- Run ComfyUI
- Type `http://localhost:8188/api/view?filename=index.html&type=output&subfolder=` in browser nav bar
- Observe that the page is getting loaded. With the patch, you should observe that the html file is being downloaded instead.
During testing, make sure that you disable browser cache between different testing procedures.

[Security] Fix potential XSS on /view

---

comfy_extras/nodes_load_3d.py
nodes.py

Hi,
I implment a node to load local 3d models, here is FE change:
https://github.com/Comfy-Org/ComfyUI_frontend/pull/1563
which needs this BE changes.
here are the introduction video as your reference:
1. basic load feature
https://github.com/user-attachments/assets/f9f1a7f4-5bd2-4a96-b9d7-681b2d7f68f3
3. showGrid, cameraType, View
https://github.com/user-attachments/assets/3c539495-6a35-49eb-84fc-14d5dd8c55c4
5. material, lightIntensity
https://github.com/user-attachments/assets/dbc4dd0b-d387-4ec0-b276-5e966ccc6794
7. fbx and animation
https://github.com/user-attachments/assets/a615f99a-7555-477c-beb4-d1d885bf093b
9. up-direction
https://github.com/user-attachments/assets/40e9f61a-91cf-4e7a-8b62-e3dd1a59e9d5
11. multi-models (video file is too big)
12. supported-formats (video file is …

add load 3d node support

---

folder_paths.py
tests-unit/comfy_test/folder_path_test.py

The changes are small enough not to complicate the code.
Just added a check if such a path value already exists in `folder_names_and_paths` - then first the old value is deleted and then the new one is added.
Ideally, it would be possible to check whether it is necessary to delete and add at all, but there would be more code, and apparently it will not work faster because of several additional checks and it will become much less readable.

add_model_folder_path: ensure unique paths by removing duplicates

---

comfy_extras/nodes_photomaker.py

This commit: https://github.com/comfyanonymous/ComfyUI/commit/8f0009aad0591ceee59a147738aa227187b07898 added the `model_type` field to the CLIP vision configs. However, it seems that the built-in photomaker node still misses this field, resulting in a "missing model_type key in dictionary" error.
This PR fixes the issue, and with this small change, everything works as expected.

(fix): added "model_type" to photomaker node

---

CODEOWNERS

This PR adds `.github` folder to maintainer owner list. `.github` folder contains issue templates and github CI configurations.

Add .github folder to maintainer owner list

---

app/model_manager.py
tests-unit/app_test/model_manager_test.py

This PR adds support for reading `.safetensors` files with kohya-ss metadata ([originates from the first public user-facing LoRA implementation](https://github.com/kohya-ss/sd-webui-additional-networks)) that contain embedded preview images. Though these are currently (unfortunately) rare, I hope this PR will encourage further adoption.
Priority is still given first to external preview image files.
Example model: https://pixeldrain.com/u/oXzNGXje
Functionality can be verified by accessing the model via the model library from the sidebar.
<details><summary>Without this PR</summary>
<p>
</p>
</details> 
<details><summary>With this PR</summary>
<p>
</p>
</details>

Support preview images embedded in safetensors metadata

---

.ci/update_windows/update.py
app/user_manager.py
comfy/cldm/cldm.py
comfy/extra_samplers/uni_pc.py
comfy/hooks.py
comfy/ldm/aura/mmdit.py
comfy/ldm/modules/diffusionmodules/util.py
comfy/ldm/util.py
comfy/model_base.py
comfy/model_management.py
comfy/model_patcher.py
comfy/sd.py
comfy/sd1_clip.py
comfy_extras/chainner_models/model_loading.py
comfy_extras/nodes_hooks.py
main.py
new_updater.py
ruff.toml
tests-unit/server/routes/internal_routes_test.py
tests/conftest.py
tests/inference/test_execution.py
tests/inference/test_inference.py

This PR enforces ruff lint rule `T201` that bans usage of `print`. All existing usage of `print` in core are replaced with `logging`. All usages in tests/deployment files are annotated with `# noqa`.

Replace print with logging

---

README.md

updated and simplfied ComfyUI readme for Intel GPUs.
Intel GPU Support Now Available in PyTorch 2.5 https://pytorch.org/blog/intel-gpu-support-pytorch-2-5/
more info can be found: https://pytorch.org/docs/main/notes/get_start_xpu.html
1. using upstream pytorch nightly builds for Intel Arc GPUs, (Desktop discreet A-Series/B-Series GPUs, Core Ultra-H, Core Ultra Series-2)
```
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/xpu
```
```
python main.py
```
2. Users can also use Intel® Extension for PyTorch (IPEX) to setup env for ComfyUI. This is device specific for improved performance and requires a conda env.
more info can be found: https://pytorch-extension.intel.com/installation?platform=gpu
oneAPI base toolkit setup is no longer needed …

Adding upstream pytorch installation instruction for Intel GPUs to README.md 

---

comfy_extras/nodes_align_your_steps.py

The 10 step minimum for the AYS scheduler is pointless, it works well at lower steps, like 8 steps, or even 4 steps.
For example, with LCM or DMD2.
Example here: https://i.ibb.co/56CSPMj/image.png

remove minimum step count for AYS

---

comfy/ldm/pixart/blocks.py

in the url[https://download.pytorch.org/whl/xformers/]
The xformers lib version like this.
so should add another split method to fix it.

fixed a bug in ldm/pixart/blocks.py

---

README.md
comfy/cli_args.py
comfy/model_management.py
main.py

I expect that there might be some opinions about 1.) and 2.) so I am open for anyone arguing for some detail changes or another way to implement if needs be. List of changes here include:
1.) Add in a `--oneapi-device-selector` that does something similar to `--cuda-device` but for Intel oneAPI devices. This doesn't need to necessarily be limited to GPUs but I expect for the time being that it will effectively only do that. Documentation on how to use this can be found at https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector
2.) Per https://github.com/pytorch/pytorch/blob/v2.5.0/docs/source/notes/numerical_accuracy.rst#reduced-precision-reduction-for-fp16-and-bf16-in-scaled-dot-product-attention-sdpa of which …

Add oneAPI device selector for xpu and some other changes.

---

main.py

This pull request introduces small changes to allow ComfyUI to be integrated with external event loops, such as those used by FastAPI(or any other). The refactor primarily focuses on the `main.py` file, making it possible to run the ComfyUI server programmatically alongside other Python applications.  
Key updates:  
- Wrapped the existing server setup and execution logic into a reusable `start_comfyui` function.  
- Ensured compatibility with external event loops without disrupting the current standalone usage.  
- Added minimal changes to keep the current behavior intact when running `main.py` directly.  
This update is especially useful for developers who want to embed ComfyUI as part of a larger application or integrate it with frameworks like FastAPI.
All changes are backward …

Enable External Event Loop Integration for ComfyUI [refactor]

---

app/logger.py
comfy/cli_args.py
main.py

- No change to default behaviour
- Adds CLI argument: `--log-stdout`
- With this arg present, any logging of a level below `logging.ERROR` will be sent to `stdout` instead of `stderr`
- Fixes typo
3rd party logging libraries sometimes treat error streams differently to regular streams.  The logging library used by the desktop app tags error output with `[error]` by default.  Currently, there is no way to determine if output is an error or not, without parsing all text (which is brittle at best).
This change allows the invoker to decide if ComfyUI should try to emulate normal executable output (rather than python logging default).

Add option to log non-error output to stdout

---

app/custom_node_manager.py
folder_paths.py
nodes.py
server.py
tests-unit/app_test/custom_node_manager_test.py

This PR prepares the following feature request: https://github.com/Comfy-Org/ComfyUI_frontend/issues/1008
Related frontend PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/2032
Implementation details:
- `@routes.get("/workflow_templates")` - This endpoint returns a map of custom_nodes names and their associated workflow template files. The ones without templates are omitted. Example:
```
{
"ComfyUI-LTXTricks": [
"example_ltxv_stg",
"example_ltx_flow_edit",
"example_ltx_interpolation",
"example_ltx_inversion",
"example_ltx_iv2v",
"example_ltx_rf_edit"
],
"ComfyUI_Noise": [
"unsample_example",
"variations_example"
]
}
```
- `LOADED_MODULE_DIRS` where we keep track of all successfully loaded custom_nodes and their directories (even when there is no class mapping and web directory)
- …

serve workflow templates from custom_nodes

---

comfy_execution/graph.py
execution.py

Title. Provides a speed up for certain nodes, such as those that perform file system ops without a cache, i.e. [LoadImage](https://github.com/comfyanonymous/ComfyUI/blob/e1dec3c79269d1ed9d9cb018b2874737b02d2757/nodes.py#L1624)
On my system, running a cached workflow with 10 LoadImage nodes and 10 PreviewImage nodes takes 0.08 seconds without this PR, and 0.04 seconds with.

Remove duplicate calls to INPUT_TYPES

---

comfy/hooks.py
comfy/model_patcher.py
comfy/samplers.py

This PR adds a 'sigmas' entry into ```transformer_options``` so that downstream code can know the full scope of the current sampling run.
This makes it possible to fix the inconsistency in hook keyframe behavior when sampling is split across different sampling nodes, or if a node's sampling code splits it across multiple calls.
https://github.com/comfyanonymous/ComfyUI/issues/6183
https://github.com/comfyanonymous/ComfyUI/pull/6185

Fix Hook Keyframe 'guarantee_steps' behavior and add 'sigmas'

---

main.py
server.py

For some reason it is currently ignored, this small PR fixes it.
Reason for fix:
We need support of `verbose` arg, because we start the ComfyUI web server at the same time as our Uvicorn server in the same process, and we proxy requests to ComfyUI from sub-path, and we ourselves want to write in console the path to the ComfyUI server in the terminal taking into account our proxy address.

(fix): "verbose" argument

---

comfy/comfy_types/README.md
comfy/comfy_types/examples/example_nodes.py

- Fixes imports in comfy_types README / example
- Clarifies example documentation

Fix custom node type-hinting examples

---

comfy/samplers.py

`calculate_sigmas` currently doesn't handle unknown scheduler names correctly. The variable `sigmas` never gets bound in the error case, so it will fail with a rather unintuitive `NameError: name 'sigmas' is not defined`.
This pull modernizes `calculate_sigmas` and scheduler lookup to use a dictionary for the scheduler list and adds type annotations. Of course it also fixes the original issue by raising `ValueError` after the log message. Changes tested to be compatible with Python 3.8.
Taking this approach also has the advantage of not having to repeat/keep the list of scheduler names in sync (since it can just be generated from the list keys) and reduces duplicated code. Also, custom nodes can easily add themselves to the scheduler list without having to do stuff like monkeypatch …

Fix unknown scheduler error handling in calculate_sigmas function

---

comfy/utils.py
nodes.py

This commit fixes the temporal overlap calculation (which previously always evaluated to 1), and removes a redundant tile at the end of the range when its elements are completely covered by the previous tile.

Fix temporal tiling for Tiled VAE decoder, remove redundant tiles.

---

.github/workflows/update-frontend.yml

Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/2144
Resolves https://github.com/Comfy-Org/ComfyUI_frontend/issues/2145
This PR adds a new on-demand github action to create PR of frontend update with https://github.com/comfy-pr-bot account.
Example workflow run in mirror repo:
https://github.com/Comfy-Org/ComfyUI-Mirror/actions/runs/12603097223
Example PR created:
https://github.com/Comfy-Org/ComfyUI-Mirror/pull/6
Following tasks needs to be done in repo settings to get this action to work properly:
- Add https://github.com/comfy-pr-bot as collaborator with write access to the repo
- Add a repo secret `PR_BOT_PAT` (Content in sent slack DM)

Add update-frontend github action

---

comfy/hooks.py
comfy/samplers.py

In _calc_cond_batch, "sigmas" on transformer_options is written with the value of t, which is only the current step's sigma (and this PR does not change it). In inner_sample, there is another "sigmas" assigned to transformer_options earlier that is intended to have all the sigmas used for the current sampling run (i.e. all the steps that will be run).
When I added that inner_sample "sigmas", I did not notice the string was already used inside _calc_cond_batch, so third-party nodes that were intending to use the full sample sigmas do not work as intended since those values end up not being exposed anywhere.
So this PR just changes the "sigmas" assigned to transformer_options in inner_sample to "sample_sigmas" to make sure there is no overlap in the name. In the long term, we should have a …

In inner_sample, change "sigmas" to "sample_sigmas"

---

comfy/model_patcher.py
comfy/utils.py

Resolves https://github.com/comfyanonymous/ComfyUI/issues/6303
This PR adds documentation on `comfy.utils.get_attr` pointing developer to `ModelPatcher.get_model_object`.

Document get_attr and get_model_object

---

tests-unit/utils/extra_config_test.py
utils/extra_config.py

No breaking changes, just a small fix + more tests.
1. Added conversion of `base_path` to absolute path if it is relative, for correct detection of duplicate paths (and the `add_model_folder_path` function accepts `full_folder_path: str`, so it is logical to do so)
2. Added 3 tests for all cases of `extra_model_paths.yaml`: when base_path is relative, when it is absolute and when it is not there at all.
3. Fixed old tests "load_extra_path_config", added OS detection, because the path `C:/Users/TestUser/AppData/Roaming/` on Linux is considered relative.

(fix): load_extra_path_config: relative path not converted to a full path

---

comfy_extras/nodes_custom_sampler.py

This PR adds a node to modify the first sigma value in a list of sigmas. This is applicable for models trained with zero terminal SNR. The default and max values are chosen based on the NovelAI V3 paper (which also describes, in A.2, why this first sigma value may be desired to be modified). https://arxiv.org/abs/2409.15997
Some more examples of this being used in practice can be found here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15608#issue-2257938921
I personally believe this node is useful while also being straightforward enough it can live in this repo to benefit everyone.

Add SetFirstSigma node

---

server.py

Prevents noisy errors like this being spit out to the console.
```
Error handling request
Traceback (most recent call last):
File "C:\comfyui\venv\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\comfyui\venv\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\comfyui\venv\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\comfyui\server.py", line 50, in cache_control
response: web.Response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\comfyui\server.py", line 128, in origin_only_middleware
response = await handler(request) …
```

PromptServer: Return `400` for empty `filename` param

---

comfy/k_diffusion/sampling.py

This function provides greater precision than `exp(x) - 1` for small values of `x`.
Found with TorchFix https://github.com/pytorch-labs/torchfix/

Use `torch.special.expm1`

---

comfy/k_diffusion/sampling.py
comfy/samplers.py

Implement a simple deterministic 2-multisteps sampler from the algorithm 2 of [Interpreting and Improving Diffusion Models from an Optimization Perspective](https://openreview.net/pdf?id=o2ND9v0CeK) with the general version in term (12). The default ge_gamma is 2 as the paper suggested (algorithm 2). 
There is a comparison with cfg=3 and exponential scheduler.

Implement gradient-estimation sampler

---

app/custom_node_manager.py
tests-unit/app_test/custom_node_manager_test.py
tests-unit/utils/json_util_test.py
utils/json_util.py

This PR adds internationalization (i18n) support for custom nodes in ComfyUI by:
1. Adding a new `/i18n` endpoint that serves translations from custom nodes' locales folders
2. Supporting multiple translation files per custom node (`main.json`, `nodeDefs.json`, etc.)
3. Implementing a recursive JSON merging utility to combine translations from multiple nodes
4. Adding comprehensive test coverage for translation loading and JSON merging
The changes enable custom node developers to provide translations that are automatically loaded and served through the API.
Example custom node locales directory: https://github.com/huchenlei/ComfyUI-layerdiffuse/tree/main/locales

[i18n] Add /i18n endpoint to provide all custom node translations

---

CODEOWNERS

Make web server developers own `/utils/` directory.

Add utils/ to web server developer codeowner

---

comfy/conds.py

Replaces https://github.com/comfyanonymous/ComfyUI/pull/6287
https://github.com/comfyanonymous/ComfyUI/commit/d6bbe8c40f28446738cd2687a9a13310a3189f1a removes the calls to `lcm`. This PR removes the function itself.

[Cleanup] Remove unused function lcm in conds.py

---

comfy/cli_args.py
folder_paths.py
main.py
tests-unit/comfy_test/folder_path_test.py

- The `base_path` and `models_dir` properties of `folder_paths` are set during file import.
- Many extensions are using these directly.
- The ComfyUI directory cannot be read-only.
- Add --base-directory command line argument.
- Almost* no change to existing behaviour
- * cli_args is now imported prior to folder_paths - nil impact expected.

Allow changing folder_paths.base_path via command line argument.

---

comfy_extras/nodes_load_3d.py

Add a new preview 3d - animation node to support FBX/glb animation preview, requested in https://github.com/comfyanonymous/ComfyUI/issues/6583
FE changes is https://github.com/Comfy-Org/ComfyUI_frontend/pull/2341

Add node for preview 3d animation

---

comfy/ldm/modules/attention.py

Show guide message for `--use-sage-attention` if the `sageattention` module isn't installed.

improve: better guide message for sageattention

---

folder_paths.py

Pytorch 2.6 introduces [a new format for AOTInductor modules](https://pytorch.org/blog/pytorch2-6/#beta-new-packaging-apis-for-aotinductor), which uses the extension `.pt2`. 
I've had good results compiling comfyui models to AOTInductor modules and then loading them back in ComfyUI: you get the same performance improvements as `torch.compile`, but without the overhead of compiling at runtime.  At the moment there's no standardization for the metadata contained in an AOTInductor archive, and all the config/tensor name information is stripped, so to actually detect what kind of model is being loaded is a question for the future.  For now, we can make it easier to load AOTI archives in custom nodes by adding the format as a known pytorch extension.

Allow searching for .pt2 archives

---

comfy/model_management.py

This PR enables a new PyTorch flag, currently only available in nightly releases as of 2025-01-12, that enables FP16 accumulation in matmul ops for NVIDIA GPUs. On my system with a RTX 3090, running the default provided image generation workflow at a resolution of 1024x1024, provides an `it/s` bump from `4it/s` to `5it/s`.
I've opted to only enable this when `--fast` is used since it seems to be "potentially quality deteriorating", [as the `--fast` arg suggests](https://github.com/comfyanonymous/ComfyUI/blob/1f1c7b7b5673fac3d3d38a1291ed1171f6cdc3eb/comfy/cli_args.py#L132).
Note that performance improvement only really applies to the 3090 or newer GPUs (i.e. 4000 series). Older cards will likely see no performance improvement.
---
For reference: …

Allow FP16 accumulation with `--fast`

---

comfy/k_diffusion/sampling.py
comfy/samplers.py

Continuation of #6462
This PR:
- Adds res_multistep_ancestral and res_multistep_ancestral_cfg_pp samplers. Since res_multistep is a modified version of DPM-Solver++, it's quite easy to make it ancestral.
- Fixes cfg_pp implementation in res_multistep sampler by replacing incorrect `denoised` with `uncond_denoised` and setting `old_denoised` to uncond prediction. This should decrease artifacts even more.
I've also removed some unused parts and simplified the code even more.

res_multistep: Fix cfgpp and add ancestral samplers

---

server.py

When opening a .webp image in a new tab, Chrome was downloading the file instead of displaying it. This happened because the MIME type for .webp was not registered, causing the server to return Content-Type: application/octet-stream instead of image/webp.
**Fix:**
- Added MIME type registration for .webp images.
- Also, I corrected the .js MIME type using mimetypes.add_type().
workflow with webp image:
[webp_preview.json](https://github.com/user-attachments/files/18722172/webp_preview.json)

Fix incorrect Content-Type for WebP images

---

comfy_extras/nodes_load_3d.py

remove two params from node panel and moved them to scene, this is BE change for https://github.com/Comfy-Org/ComfyUI_frontend/pull/2464

remove light_intensity and fov from load3d

---

comfy_extras/nodes_lumina2.py
nodes.py

We support CFG Renorm [official codes](https://github.com/Alpha-VLLM/Lumina-Image-2.0/blob/main/models/model.py#L806) and two system prompts (superior and alignment.) 
Meanwhile, we modify the workflow using our recommended settings.
1. The CFG Renorm is implemented through a new node, **RenormCFG**, in `comfy_extras/nodes_lumina2.py`. 
2. The system prompts are implemented through a new node, **CLIPTextEncodeLumina2**, in `comfy_extras/nodes_lumina2.py.`  This node is used to prevent users from deleting or forgetting system prompts.
3. We modify the workflow and you can drag the following image in ComfyUI to get it. This workflow uses the euler sampler, 50 steps, and shifting of 6.

support system prompt and cfg renorm in Lumina2

---

comfy/ldm/hunyuan_video/model.py
comfy/model_base.py
comfy/model_detection.py

https://huggingface.co/Skywork/SkyReels-V1-Hunyuan-I2V
Converted back to the original format from diffusers format, which didn't load natively:
https://huggingface.co/Kijai/SkyReels-V1-Hunyuan_comfy/blob/main/skyreels_hunyuan_i2v_bf16.safetensors
This finetune of HunyuanVideo has double the input channels for image2video, I did the minimum changes to allow loading and using it with the ip2p conditioning node, unsure if there should be additional node or not.
https://github.com/user-attachments/assets/d496fe39-43a3-41ee-8177-903694632abb

Support loading and using SkyReels-V1-Hunyuan-I2V

---

api_server/routes/internal/internal_routes.py
comfy/comfy_types/node_typing.py
nodes.py

Adds Load Image node with remote widget. When refreshed, it re-fetches the values from the given route (in this case, files from output folder). This node can test the features detailed in https://github.com/Comfy-Org/rfcs/pull/1 (lazy loading widget with remote source, changes to COMBO input spec). 
https://github.com/user-attachments/assets/e2e0f746-61c5-459c-9e26-260f7e85cff5
Frontend:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/2422 v1.9.7
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/2494 v1.9.13
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/2509 v1.9.13
[Test nodes](https://github.com/Comfy-Org/ComfyUI_devtools/blob/main/dev_nodes.py), [Unit tests](https://github.com/Comfy-Org/ComfyUI_frontend/blob/main/tests-ui/tests/composables/widgets/useRemoteWidget.test.ts …

Add Load Image Output node

---

requirements.txt

This PR fixes these issues.
https://github.com/comfyanonymous/ComfyUI/issues/6038#issuecomment-2661776795 https://github.com/comfyanonymous/ComfyUI/issues/5814#issue-2700816845

fixed: crash caused by outdated incompatible `aiohttp` dependency

---

comfy/comfy_types/node_typing.py

The current link is pointing to a path that does not exist any longer. I changed it to point to the currect correct path for custom nodes datatypes.

Fix link pointing to non-exisiting docs

---

tests-unit/utils/extra_config_test.py
utils/extra_config.py

Currently if you have this as your extra_model_paths.yaml, ComfyUI will try to add 
`/path/to/ComfyUI/custom_nodes/` to folder_paths, which is not differentiated from `/path/to/ComfyUI/custom_nodes` without the trailing `/`.
```
comfyui:
custom_nodes: custom_nodes/
base_path: /path/to/ComfyUI
```
This causes ComfyUI to import custom nodes twice.
```
Import times for custom nodes:
0.0 seconds: /Users/../Desktop/custom_nodes/aigodlike-comfyui-translation
0.0 seconds: /Users/../Desktop/custom_nodes/aigodlike-comfyui-translation
```
https://forum.comfy.org/t/when-installing-the-translation-plugin-through-manager-an-error-occurs-after-deleting-the-translation-plugin-it-can-be-opened/1549/6

Normalize extra_model_config.yaml paths to prevent duplicates.

---

README.md

Clean up and organize the getting started section.

Update installation documentation to include desktop + cli.

---

comfy/cli_args.py
comfy/model_management.py
comfy/ops.py

Follow-up on https://github.com/comfyanonymous/ComfyUI/commit/cf0b549d4828b6b9f6d98277c36784ab3c79ff6d
Replace the magic number range with a list args of performance features.
Example usage:
```
--fast # Enables all performance features
--fast fp16_accumulation # Enables fp16 accumulation feature
--fast fp16_accumulation fp8_optimization # Enables both fp16_accumulation and fp8_optimization
```

Use enum list for --fast options

---

app/frontend_management.py

improved: better installation guide
- change `pip` to `{sys.executable} -m pip` 
modified: To prevent the guide message from being obscured by a complex error message, apply `exit` instead of `raise`.

improved: better frontend package installation guide

---

app/frontend_management.py

suggest absolute full path to the `requirements.txt` instead of just `requirements.txt`
For users of the portable version, there are occasional instances where commands are misinterpreted.

Improve: Provide a better guide message for the missing frontend message.

---

comfy_extras/nodes_lt.py

This patch fixes a bug in LTXVCropGuides when the latent has no keyframes. Additionally, the first frame is always added as a keyframe.

fix: ltxv crop guides works with 0 keyframes

---

comfy/comfy_types/node_typing.py
comfy_extras/nodes_custom_sampler.py
nodes.py

Currently the frontend is assigning `control_after_generate` option for matching exactly `INT` input type and `seed` & `noise_seed` input name. 
There is currently no way to disable the linked control widget when the condition is met.
This PR explicitly add `control_after_generate` to node definitions to prepare us deprecate the logic in the frontend.

[NodeDef] Explicitly add control_after_generate to seed/noise_seed

---

comfy/cli_args.py

Improves handling of front-end-root launch argument. Several instances where users have set it and ComfyUI launches as normal and completely disregards the launch arg which doesn't make sense. Better to indicate to user that something is incorrect.
It is not like a user will use this argument by mistake either.

Better argument handling of front-end-root

---

comfy/model_patcher.py

When hook weights are cached after calculation, there is no need to revert all weights back to their backup values in ```hook_backup``` before switching to them. After they are swapped, ```hook_backup``` weights should only be restored for keys that weren't swapped to cached weights.
When both cached weights and backup weights are stored on the ```load_device```, there is a 1.07x uplift in performance when any is found.
When some of the cached weights/backup weights are forced to be offloaded to system memory, there is a 1.12x uplift in performance when any is found.
I didn't find any performance regressions, so it should be an overall improvement.

Weight Hooks Switching Optimization

---

app/frontend_management.py
main.py
tests-unit/app_test/frontend_manager_test.py

Ref: https://github.com/comfyanonymous/ComfyUI/pull/7021#issuecomment-2708302924
The desktop app is also affected as it is currently shipping the frontend package twice, increasing the oveall disk space consumption for users.
This PR bypass the import of built-in frontend package and frontend version check if the user launches with `--front-end-root` or `--front-end-version` argument to use alternative frontend implementation.

Only check frontend package if using default frontend

---

nodes.py

The frontend now annotates uploaded image filepaths if the `image_folder` option is set (https://github.com/Comfy-Org/ComfyUI_frontend/pull/2597). Annotating in this python class is now redundant and results in paths like `path/to/image.png [output] [output]`. Fixes https://github.com/comfyanonymous/ComfyUI/issues/7142.

Fix LoadImageOutput node

---

comfy/k_diffusion/sampling.py
comfy/samplers.py

Introduce a stochastic sampler, ER-SDE-Solver. It's mainly based on the Algorithm 5 in the arXiv paper (v3) except for the parts of numerical integration that adopt the method in the official code. This sampler is also used in the experiments of align your steps. 
The default noise scaler is ER SDE 4 (in arXiv v3), which is the customized noise scale function used in their experiments mostly.
Some grids with AYS 10 steps:
With AYS 30 steps:

Add ER-SDE sampler

---

execution.py

Currently if the frontend sets a list as widget value, it will be interpreted as a link between 2 nodes. This PR adds an unwrap mechanism to fix this issue. The frontend will wrap the widget value in a dict with reserved key `__value__`, e.g. `{"__value__": [1, 2, 3]}`, and the execution engine unwraps it to restore the internal content.

Add unwrap widget value support

---

comfy/comfy_types/node_typing.py

Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/2987
Adds documentation to multi_select combo input.
```python
class MultiSelectNode:
@classmethod
def INPUT_TYPES(cls):
return {
"required": {
"foo": (
"COMBO",
{
"options": ["A", "B", "C"],
"multi_select": {
"placeholder": "Choose foos",
"chip": True,
},
},
)
}
}
RETURN_TYPES = ("STRING",)
OUTPUT_IS_LIST = [True]
FUNCTION = "multi_select_node"
CATEGORY = "DevTools"
DESCRIPTION = "A node that outputs a multi select type"
def multi_select_node(self, foo: list[str]) -> list[str]:
return (foo,)
```

[NodeDef] Add documentation on multi_select input option

---

comfy/cli_args.py
comfy/ldm/modules/attention.py
comfy/model_management.py

This is useful on AMD systems, as FA builds are still 10% faster than Pytorch cross-attention. Without even using torch.compile, this can bring SDXL 1024x1024 from 5.5s to 5s.
(I did a bench over at https://www.reddit.com/r/buildapc/comments/1j2zfbv/9070_xt_vs_7900_xtx/mhkmv0x/ )

Add --use-flash-attention flag.

---

comfy/ldm/modules/attention.py

This can happen on Pytorch versions older than 2.4. Fixes the bug report from https://github.com/comfyanonymous/ComfyUI/pull/7223
The attribute error is reported at runtime and causes a fallthrough to Pytorch SDPA.

Tolerate missing `@torch.library.custom_op`

---

comfy/k_diffusion/sampling.py

If the noise scaler is something like identity function, it would lead to precision issues in the noise term.

Guard the noise term in er_sde

---

comfy/model_patcher.py

Addresses bug found in: https://github.com/comfyanonymous/ComfyUI/issues/7195
There are likely other edge cases with hooks when weights cannot be loaded fully at a model's usage time, but this at least resolves the issues encountered when a model is unloaded partially at any point before it is used again and fully loaded.

Call unpatch_hooks at the start of ModelPatcher.partially_unload

---

app/frontend_management.py

Format error strings to make them more readable to developers.

[nit] Format error strings

---

comfy/cli_args.py
comfy/model_management.py

Not sure why Diffusion model and VAE have an option for bfloat16 while TE doesn't.
Hence, adding that option.

Add option to store TE in bf16

---

app/app_settings.py

Ensure a 401 error is returned when payload comfy user does not exists
Unlocks change on [frontend](https://github.com/Comfy-Org/ComfyUI_frontend/pull/3289)
see https://github.com/comfyanonymous/ComfyUI/issues/7438

User missing

---

comfy/ldm/modules/attention.py

Currently, the TransformerBlocks inside the UNet only receive the flattened activations. This makes it impossible for them to know what the actual spatial dimensions of the activations that were passed to them were (because of downsampling, padding, etc. the aspect ratio of the activations is different in different layers, so it can't even be reliably inferred from the original latent shape).
For example, in [Cubiq's IPAdapter implementation](https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/CrossAttentionPatch.py#L209), an initial guess is made to the mask size/shape, but in some cases we have to give up and pad the mask with zeros, likely creating incorrect results.
Similarly, in the [official comfy code for SAG](https://github.com/comfyanonymous/ComfyUI/blob/master/comfy_extras/ …

Add activations_shape info in UNet models

---

nodes.py

This apparently breaks some custom nodes so I have moved this change to this pull request. 
Nodes that need to be fixed:
@ltdrdata ComfyUI manager
@rgthree rgthree-comfy
And probably some others.
If your custom node is a normal one that doesn't do anything weird with the sys.modules you should be good.
This is an important fix to prevent custom nodes from conflicting with python packages so it will be merged eventually.

Prevent custom nodes from accidentally overwriting global modules.

---

comfy/patcher_extension.py
comfy/sampler_helpers.py

Most likely starting 4 months ago with the memory management changes, memory usage expectation for context window-related sampling (such as with AnimateDiff-Evolved) is vastly overestimated. There doesn't seem to be anything 'wrong' with that code - ComfyUI is simply trying to account for things in memory estimation it wasn't before.
In practice, this at best decreases performance by >25% due to models being forced to be loaded partially with high total latent counts, and at worst causes new edge cases that may cause crashes on select workflows.
This PR adds a wrapper around the prepare_sampling function to allow custom nodes to provide a better estimate for noise_shape without the need for any monkey patching.
Related PR that will be merged into AnimateDiff-Evolved once this is merged: …

Add prepare_sampling wrapper to allow modifying noise_shape

---

server.py

New templates were added along with Hunyuan 3D-2 implementation release. However, some users reported that even after updating ComfyUI & frontend package, they did not see the new templates until a short while had passed ([example](https://discord.com/channels/1218270712402415686/1249784096712949772/1357008514144538904)), despite the blog post saying they should be there.
This PR ensures index file is never cached to prevent the issue from occurring during future model implementation releases.

Dont cache workflow templates index.json file

---

comfy/cli_args.py
comfy_execution/caching.py
execution.py
main.py

Adds a new node caching option that will offload a cached node once all of it's children have executed in order to reduce the amount of RAM/VRAM a workflow needs. The downside is that a workflow will fully execute each time, so for an end user, it will seem like there is no cache at all.
This caching option is enabled using a new --cache-none flag (the name was chosen as for users, it seems like no caching occurs at all).
I created this pull request due to the resources that the new video models use. see: https://github.com/comfyanonymous/ComfyUI/issues/7465

Dependency Aware Node Caching for low RAM/VRAM machines

---

nodes.py

Filter out non-images from the file selection list in LoadImage node, as there is starting to be more video and 3d model files in the input folder which can cause issues if accidentally selected (e.g., when using the arrow buttons on the combo widget).
LoadAudio node uses same filtering function for past 7 months (since https://github.com/comfyanonymous/ComfyUI/pull/4054) without reported bugs:
https://github.com/comfyanonymous/ComfyUI/blob/22ad513c72b891322f7baf6b459aa41858087b3b/comfy_extras/nodes_audio.py#L218

Only show image files in LoadImage file select combo

---

comfy/cli_args.py
comfy/ops.py

Adds support for [CublasOps](https://github.com/aredden/torch-cublas-hgemm), allowing for faster fp16 performance.
On my system with a RTX 3090, when running the included SDXL Simple workflow, this extension library provides an `it/s` bump from `4it/s` to `5it/s`.
Guarded behind `--fast` since this does affect generation output in a similar manner to https://github.com/comfyanonymous/ComfyUI/pull/6453.

Add CublasOps support

---

folder_paths.py
tests-unit/folder_paths_test/filter_by_content_types_test.py

Updates type, docstring, and unit tests for `filter_files_content_types` function of `folder_paths` module to support filtering 3d model files, as ComfyUI now supports 3D.
`fbx` is added to the mimetype cache manually, as .fbx (Filmbox) files aren't included in the standard MIME type databases on many systems, including Ubuntu. (FBX is a proprietary 3D model format developed by Autodesk.)

Update `filter_files_content_types` to support filtering 3d models

---

comfy/k_diffusion/sampling.py
comfy/samplers.py

[SEEDS](https://arxiv.org/abs/2305.14267) is a single-step SDE sampler whose stochastic part differs from the one in sde-dpm-solver (S). It proposes noise decomposition to construct the noise terms, which makes it not only use a single new noise at each stage, but also the noise from earlier stages.
The algorithm 2-4 are for the NP (noise prediction). This PR only provides DP (data prediction) mode because NP requires lots of steps to work.
The image grid in CFG=4.0 and karras for comparing other 2S stochastic samplers within the same number of model evaluations instead of scheduler steps. dpmpp_sde uses the default_noise_sampler for the proper comparison. Using lower CFG for SEEDS-3 will be better.

Add SEEDS (stage 2 & 3 DP) sampler

---

comfy_extras/nodes_load_3d.py

allow outputing camera state from load3d, and pass into preview3d
use in https://github.com/Comfy-Org/ComfyUI_frontend/pull/3421

add support to output camera state

---

nodes.py

This is mostly a small change that replaces the long if statement with a getattr where the common name (e.g. "wan") gets mapped to the enum (`CLIPType.WAN`) in the clip loader nodes.
The main benefit of this is assuring that the common name actually matches the enum, so that downstream nodes don't need to keep their own mapping for custom clip loader nodes. (ref: https://github.com/city96/ComfyUI-GGUF/issues/246#issuecomment-2797782580)
Test for the current values in the single / dual clip loader node. Only odd one out is SDXL which doesn't have an enum and instead uses "stabe_diffusion". The logic in the single clip loader node already defaults to `CLIPType.STABLE_DIFFUSION`, so I just extended this to the dual clip loader as well.
```py
test = lambda type: getattr(comfy.sd.CLIPType, …
```

Replace CLIPType if with getattr

---

comfy/sd.py
comfy/text_encoders/hidream.py
nodes.py

Reference issue: #7665 
Asked some community users. They would like this optimization.
Now, using dual clip may cause black output when passing KSampler in DualCLIPLoader. 
Here's some workflows that can test this PR.
CLIPLoader with Llama-3.1:
DualCLIPLoader with both T5 and Llama-3.1:
These both workflows tested successfully on Ubuntu with RTX 4090.

Hidream: Allow loading hidream text encoders in CLIPLoader and DualCLIPLoader

---

execution.py

Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3477
Node can access this token by specifying following input:
```python
@classmethod
def INPUT_TYPES(s):
return {
"hidden": { "auth_token": "AUTH_TOKEN_COMFY_ORG"}
}
def execute(self, auth_token: str):
print(f"Auth token: {auth_token}")
```

Populate AUTH_TOKEN_COMFY_ORG hidden input

---

comfy/comfy_types/node_typing.py

Adds type hint for new `socketless` node input option.
- Ref: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3548

Add node type hint for socketless option

---

comfy_extras/nodes_mask.py

Requested in https://github.com/Kosinkadink/rfcs/blob/main/rfcs/0000-corenodes.md#preview-nodes
and original implement from
https://github.com/cubiq/ComfyUI_essentials/blob/9d9f4bedfc9f0321c19faf71855e228c93bd0dc9/mask.py#L81
Demo is 
https://github.com/user-attachments/assets/f7544813-3b88-4141-86bd-3f920d4be3b8

upstream MaskPreview from ComfyUI_essentials

---

comfy/cli_args.py
comfy/model_management.py

Seems to break every model I have tried but worth testing?

Add option for using fp8_e8m0fnu for model weights.

---

comfy_extras/nodes_video.py
requirements.txt

This PR ~adds support for saving .webm outputs using codec svt-av1 and adds an options for using yuv420p10le pixel format~ switches aom-av1 codec for svt-av1 + yuv420p10le pixel format.
svt-av1 is significantly faster at encoding compared to libaom-av1 and yuv420p10le provides higher quality av1 output without size increase.
Note: av added support for libsvtav1 in v14.1.0, the requirements.txt are upped to reflect this.
Took **407s** to save an 81 frame wan webm using libaom-av1, crf 10.
1.8MB, VMAF 96.9885 vs an animated png output.
Took **1s** with libsvtav1 (preset 6, crf 10).
2.3MB, VMAF 97.23115 _(note pixel format provides better quality vs aom at yuv420)_
I've set preset 6 for svt-av1, would be straightforward to make this configurable (perhaps later).
* preset 1: 19.46s, VMAF …

Replace aom-av1 with svt-av1 for saving webm videos, use preset 6 + yuv420p10le pixel format

---

comfy/clip_vision.py

saves users having to explicitly discard the channel

throw away alpha channel in clip vision preprocessor

---

comfy/cli_args.py
comfy/model_management.py
comfy/ops.py

This should speed up the lowvram mode a bit. It currently is only enabled when --async-offload is used but it will be enabled by default in the future if there are no problems.

Add experimental --async-offload lowvram weight offloading.

---

comfy/model_sampling.py
comfy_extras/nodes_model_merging.py

This PR adds some extra keys related to V-Pred and ZSNR to the `save_checkpoint` function. The keys are consistent with the ones from `comfy.supported_models.SDXL.model_type`. This should simplify saving and loading checkpoints that are based upon NoobAI V-Pred models.

Save V-Pred ZSNR metadata in CheckpointSave

---

comfy_extras/nodes_lt.py

This commit overwrites the noise mask on the latent frame that is being conditioned with keyframe conditioning, setting it to one.

ltxv: overwrite existing mask on conditioned frame.

---

app/custom_node_manager.py

After researching the top 100 custom nodes on GitHub by star count, we discovered that only a small portion of custom nodes that provide example workflows follow our existing principle of placing example workflows in the "example_workflows" folder. 
The majority place them in other folders. Through statistical analysis, we found that 
- example
- examples 
- workflow
- workflows 
are the most common folder names. 
To better support example workflows provided by custom nodes in workflow templates, we should also include these four folders.

support more example folders

---

comfy_extras/nodes_post_processing.py
comfy_extras/nodes_webcam.py
pyproject.toml

This PR adds a basic linter rule which helps keep node function definitions consistent.
Ref: https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-method/

Lint node method's `self` argument

---

comfy_extras/nodes_custom_sampler.py

This PR adds a node that will extend the sigma values for a given sigma range. This is exactly identical functionality to https://github.com/comfyanonymous/ComfyUI/pull/7890 but now applicable to any sampler -- see that PR for more details.

Add node to extend sigmas

---

comfy_extras/nodes_preview_any.py
nodes.py

BE change for https://github.com/Comfy-Org/ComfyUI_frontend/pull/3640
Upstream PreviewAny from rgthree-comfy
original implement from https://github.com/rgthree/rgthree-comfy/blob/main/py/display_any.py under MIT
upstream requested in https://github.com/Kosinkadink/rfcs/blob/main/rfcs/0000-corenodes.md#preview-nodes
some differences from original implement:
1. change name from Display Any (rgthree) to Preview View
2. put it under utils category
3. replace some deprecated api in FE
tested with the following types:
1. STRING
2. INT
3. BOOLEAN
4. IMAGE
5. MASK
6. LATENT
7. Json
screenshot

upstream Preview Any from rgthree-comfy

---

comfy_api/input_impl/video_types.py
tests-unit/comfy_api_test/input_impl_test.py

Allows passing buffer as destination path when saving Comfy `VIDEO` types. Saving to bytes buffer is necessary for nodes that want to send videos to remote API via multipart/form-data requests.
Since buffer does not have a file extension to infer the output format from, there is additional logic to convert the format derived from container's format tag (e.g., 'mp4,mov,3gp') to the format expected by `av.open` (e.g., 'mp4').
To see the `format` tag of a container, you can use a command like
```
ffprobe -v error -show_entries format=format_name -of default=noprint_wrappers=1:nokey=1 your_file.mp4
```

Support saving Comfy `VIDEO`  type to buffer 

---

comfy_api/input_impl/video_types.py

It's possible to create `VIDEO` Comfy type by combining `AUDIO` and `IMAGE` Comfy types (e.g., using core `CreateVideo` node). When this process happens, the audio is encoded from (tensor) chunks. A bug can occur if the slicing creates non-c-contiguous chunks, as `av.AudioFrame.from_ndarray` expects contiguous array. Fix by making contiguous explicitly before converting to numpy array.
To reproduce issue:
1. Load and run [this workflow](https://github.com/user-attachments/files/20031107/test-audio-contiguous.json)
2. Assets used: [video](https://github.com/user-attachments/assets/33ce77de-ff73-4c99-a3c4-8bd9b7408889), [audio](https://github.com/user-attachments/assets/2c149368-d067-4742-96e3-4216659888b5) (`LoadAudio` node implicitly takes audio from video files)
After applying the fix, …

Fix: Error creating video when sliced audio tensor chunks are non-c-contiguous

---

comfy/ldm/ace/vae/music_dcae_pipeline.py
comfy/ldm/ace/vae/music_log_mel.py

Some platforms cant install it apparently so if it's not there it should only break models that actually use it.

Make torchaudio not a hard requirement.

---

comfy/ldm/ace/attention.py

Small change to use ComfyUI's normal attention implementation in ACE-Steps instead of hard-coding PyTorch attention. This doesn't seem to change the generation (if you were already using Torch SDP). Also enables stuff like SageAttention patches, though it actually does not seem to affect performance.

Use normal ComfyUI attention in ACE-Steps model

---

comfy/ops.py

_scaled_mm errors when an input is non contiguous.

Fix issue with fp8 ops on some models.

---

server.py

Add PromptServer method that can be called by nodes to send text progress to client UI like
```python
from server import PromptServer
class Node:
@classmethod
def INPUT_TYPES(cls):
return {
"hidden" : {
"unique_id": "UNIQUE_ID",
}
}
RETURN_TYPES = (,)
FUNCTION = "send_message"
def send_message(self, unique_id=None):
PromptServer.instance.send_progress_text("test message", unique_id)
return (,)
```
which can be used with LLM nodes or to show messages when a node is executing/executed

Add method to stream text to node UI

---

comfy_api_nodes/apinode_utils.py
comfy_api_nodes/apis/client.py
comfy_api_nodes/nodes_bfl.py
comfy_api_nodes/nodes_ideogram.py
comfy_api_nodes/nodes_kling.py
comfy_api_nodes/nodes_luma.py
comfy_api_nodes/nodes_minimax.py
comfy_api_nodes/nodes_openai.py
comfy_api_nodes/nodes_pika.py
comfy_api_nodes/nodes_pixverse.py
comfy_api_nodes/nodes_recraft.py
comfy_api_nodes/nodes_stability.py
comfy_api_nodes/nodes_veo2.py
execution.py
requirements.txt

Adds improvements, fixes, and localizations for API nodes, including the ability to use API nodes with a Comfy API key.
Allowing API key based authorization will allow a wider range of users to use API nodes, including:
- Users running ComfyUI headlessly or with an alternative frontend
- Users running ComfyUI with `--listen` or over LAN
- Users using ComfyUI through a cloud deployment service
- Websites embedding ComfyUI within their app
- Apps/services using ComfyUI as a serivce/API or engine
- Users running ComfyUI in a container or in the cloud
Changes:
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3801
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3815
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3836
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/3792
- …

Add support for Comfy API keys

---

comfy_api_nodes/nodes_kling.py

Kling has informed that `aspect_ratio` is not used in the I2V, which is also explicitly stated [in this section](https://app.klingai.com/global/dev/document-api/apiReference/model/imageToVideo) of their docs. We should remove the extraneous field from the request body to guard against potential future bugs.

Remove extraneous `aspect_ratio` field from Kling I2V

---

comfy/ldm/ace/vae/music_vocoder.py
comfy/ldm/audio/autoencoder.py

Drop support for torch versions below 2.2 on the audio VAEs.

Fix torch warning about deprecated function.

---

comfy_extras/nodes_string.py
nodes.py

String nodes, requested in RFC https://github.com/Kosinkadink/rfcs/blob/main/rfcs/0000-corenodes.md#string-nodes
Designed nodes:
1. Concatenate, and input is: 
- string_a, 
- string_b 
- separator
2. Substring, and input is:
- string
- start
- end
3. Length, and input is
- string
4. Case Converter, and input is
- string
- mode, with options are ["UPPERCASE", "lowercase", "Capitalize", "Title Case"]
5. Trim, and input is
- string
- mode, with options are ["BOTH", "LEFT", "RIGHT"]
6. Replace, and input is
- string
- find
- replace
7. Contains, and input is
- string
- substring
- case_sensitive
8. Compare, and input is
- string_a
- string_b
- mode, with options are ["StartsWith", "EndsWith", "Equal"]
- case_sensitive
9. Regex Match, and input is
- string
- regex_pattern
- case_insensitive
- …

Add nodes for basic string operations

---

script_examples/basic_api_example.py

Since https://github.com/comfyanonymous/ComfyUI/pull/8041, you can use API keys via the webserver API directly, without needing any particular frontend (or a frontend at all).
This means you can create workflows that combine (a) local OS models, (b) tools from the custom node community, and (c) popular paid models and => run everything together via the local Comfy webserver API, letting it handle all the orchestration.
This can benefit users who use Comfy as a backend service, run Comfy via the command line, have their own frontend, and so on.
Here is an example I did: running a workflow that contains the `BFL Flux 1.1[pro] Ultra T2I` (chosen randomly) in the terminal (via [`comfy-cli`](https://github.com/Comfy-Org/comfy-cli))  
You can see that the workflow embedded in the output is API …

Add comment in example script denoting how to use api keys without needing frontend

---

comfy/comfy_types/node_typing.py
comfy_api_nodes/apinode_utils.py
comfy_api_nodes/apis/client.py
comfy_api_nodes/nodes_bfl.py
comfy_api_nodes/nodes_ideogram.py
comfy_api_nodes/nodes_kling.py
comfy_api_nodes/nodes_luma.py
comfy_api_nodes/nodes_minimax.py
comfy_api_nodes/nodes_openai.py
comfy_api_nodes/nodes_pika.py
comfy_api_nodes/nodes_pixverse.py
comfy_api_nodes/nodes_recraft.py
comfy_api_nodes/nodes_veo2.py

For all API nodes that return a download URL, display the URL directly on the node as soon as it is available. This can benefit users who use an API node to generate something successfuly, but an error occurs before they can see the result in the queue sidebar or downstream save node. If the user does not have access to the logs for whatever reason, this may be their only recourse when encountering an error.
Examples:
See how it looks for all API nodes by opening [this zip]((https://github.com/user-attachments/files/20195923/api-node-print-progress-demo.zip)) which contains test results from running with all relevant API nodes.

Display progress and result URL directly on API nodes 

---

comfy_api/input/video_types.py
comfy_api/input_impl/video_types.py
tests-unit/comfy_api_test/video_types_test.py

Add `get_duration` to Comfy `VIDEO` type.
Can be used like:
```python
class ExampleNode:
@classmethod
def INPUT_TYPES(s):
return {
"required": { "video": (IO.VIDEO, {}) },
}
FUNCTION = f
def f(self, video):
duration = video.get_duration()
```
Can be useful to validate video inputs before sending to API nodes without having to decode (most APIs have duration constraints for video inputs).

Add `get_duration` method to Comfy VIDEO type

---

README.md

Desktop versioning does not follow core.

Remove Desktop versioning claim from README

---

comfy_extras/nodes_cond.py

Change it if you need to but it should at least have a category.

Add missing category for T5TokenizerOption

---

comfy_extras/nodes_string.py

This is strangely missing from the current default node, pretty much every custom node suite with a concatenate node has one. Without it, it makes structuring the words and such weirder and sometimes trickier when sending around some text nodes. Adds a simple delimiter functionality to the node.

Add delimiter to concatenate node

---

comfy_api/torch_helpers/__init__.py
comfy_api/torch_helpers/torch_compile.py
comfy_extras/nodes_torch_compile.py

Originally, torch.compile was implemented as an object_patch because there was no other built-in way to deal with changing an internal object to another without monkey patching.
However, this means the entirety of diffusion_model is changed to the OptimizedModel class as soon as the model begins to load, even before any weight patches are applied. The actual 'diffusion_model' is stored on the OptimizedModel's ._orig_mod parameter. So, anything relating to keys no longer applies, whether it be loras, hooks, or a simple get attr call.
This PR replaces the object_patch usage with a built-in wrapper that got added late last year as part of the hooks PR. It replaces diffusion_model with the torch.compile'd OptimizedModel object only when it gets to BaseModel.apply_model function, and replaces …

Make torch.compile LoRA/key-compatible

---

server.py

This PR addresses two issues in the ComfyUI server code:
1. Fixed parameter name in the get_embeddings route handler that would cause an unhandled exception
2. Remove the redundant `f.close()` from the `with open(...) as f:` block
1. Changed parameter name from self to request in the /embeddings route
2. Remove the redundant `f.close()` from the `with open(...) as f:` block
The with statement (context manager) is designed to ensure that resources (such as file handles) are properly freed at the end of a code block (e.g., by calling its __exit__ method, which for file objects would normally call close()). So f.close() is not necessary in this case
Verified that: 
1. The /embeddings endpoint works correctly after the fix
2. File resources are properly managed in image comparison operations …

Code Optimization and Issues Fixes in ComfyUI server

---

execution.py
main.py
server.py

Mitigates https://github.com/Comfy-Org/ComfyUI_frontend/issues/2435
ComfyUI's web app exhibits significant lag when a large number of prompts are queued. I verified what was found in the linked thread, pinpointing the slowdown to the specific call `api.getQueue()` as the number of prompts grows. Every time a prompt is submitted, the front-end synchronizes the entire queue state by making this call.
Profiling the back-end, I found most of the time is spent executing `copy.deepcopy` inside PromptQueue while a mutex is held.
This PR adds a new version of PromptQueue's `get_current_queue` method that performs `copy.copy` instead of `copy.deepcopy`. Allowing read-only shared access is safe as long as `PromptQueue` treats its queue items as immutable, which it does by returning deep copies in …

Improve performance with large number of queued prompts

---

comfy/ldm/chroma/model.py

This creates a tensor on device to avoid an unnecessary sync in the Chroma model forward pass. Part of a series of PRs I'm creating. Combined with #7152, another PR to make a CPU copy of sampler sigmas for use in control flow (since control flow needs these as python scalars to work), and optionally code to support computing latent previews/transferring them to CPU on a separate CUDA stream as I did [here](https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/2844) for webui forge (may be more complicated since comfyui doesn't seem to process previews in a separate thread from the main one), I am seeing a roughly 7% overall speed boost.

Remove blocking call from timestep embedding of Chroma

---

comfy/cli_args.py
comfy/model_management.py

This can be used to test if your current GPU/pytorch version supports fp8 matrix mult in combination with --fast or the fp8_e4m3fn_fast dtype.

Add argument to explicitly enable fp8 compute support.

---

comfy/conds.py
comfy/model_base.py
comfy/sampler_helpers.py
comfy/samplers.py

This makes it possible for the memory estimation to be based on specific conds for models instead of only the shape of the noise.
This for model_base.py:
self.memory_usage_factor_conds, which conds to use in the memory estimation.
def extra_conds_shapes(self, **kwargs), this function is the extra_conds function but returns shapes only.
memory_required now has a cond_shapes parameter.

Memory estimation code can now take into account conds.

---

comfy_api_nodes/apis/bfl_api.py
comfy_api_nodes/nodes_bfl.py

- Rename Kontext Pro and Kontext Max to [pro] and [max] to be consistent with the previous BFL API nodes
- Reduce code duplication; same endpoint logic, only change in proxy path and docstring
- Make default seed 1234; BFL Kontext API interprets 0 as 'choose a random seed'

Cleanup BFL API nodes for Kontext [pro] and [max]

---

comfy_extras/nodes_string.py

Add a RegexReplace node with behavior similar to Python's re.sub

Add node for regex replace(sub) operation

---

comfy_api_nodes/apis/client.py

When using API endpoints with paths starting with `/`, the `urljoin` function was incorrectly treating them as absolute paths, causing the base URL path to be stripped out.
**Example:**
- Base URL: `https://api.comfydeploy.com/api/comfy-org/`
- Path: `/proxy/stability/v2beta/stable-image/generate/ultra`
- **Before:** `https://api.comfydeploy.com/proxy/stability/v2beta/stable-image/generate/ultra` ❌
- **After:** `https://api.comfydeploy.com/api/comfy-org/proxy/stability/v2beta/stable-image/generate/ultra` ✅
Python's `urljoin()` follows RFC 3986 standards where paths starting with `/` are treated as absolute paths, replacing the entire path portion of the base URL instead of appending to it.
Modified the `ApiClient.request()` method to strip leading slashes from paths before passing them to …

fix: custom comfy-api-base works with subpath

---

comfy/ldm/chroma/layers.py

Micro-optimization for Chroma. Replaces ops with `addcmul` or `Tensor.addcmul_` where appropriate. Possibly less readable but these ops are mathematically equivalent to what existed prior. I don't know the full details of how addcmul gets lowered but it should be more numerically stable as well (fma has infinite precision intermediates). Intended to try to mimic some of the performance gains that torch.compile gets through pointwise fusion -- this isn't the area with the most gains for that (that honor seems to go to torch's awful RMSNorm implementation that does like a dozen separate kernel launches in a row) but nevertheless doing this does reduce the amount of pointwise ops by a fair bit so it's worth doing. Triton itself also isn't always very reliable about taking opportunities to …

use fused multiply-add pointwise ops in chroma

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/user-support.yml

Adds mandatory checkbox to bug report and user support templates requiring users to confirm they've tested with custom nodes disabled, helping reduce effort required when triaging.
Try creating a **Bug Report** on the frontend repo to see how it looks: https://github.com/Comfy-Org/ComfyUI_frontend/issues
The link points to this page: https://docs.comfy.org/troubleshooting/custom-node-issues#step-1%3A-test-with-all-custom-nodes-disabled

[feat] Add custom node testing requirement to issue templates

---

comfy_extras/nodes_images.py
nodes.py
tests-unit/comfy_extras_test/image_stitch_test.py

Simple node that returns width and height dimensions of input images. Displays dimensions on the node UI and provides width/height outputs for further processing.

[feat] Add GetImageSize node

---

server.py

ANTIALIAS was removed in Pillow 10.0.0

[Fix] Replace call to deprecated pillow API `Image.ANTIALIAS`

---

comfy_config/types.py
nodes.py
requirements.txt

Two changes here:
1. improve the logic of parsing pyproject license, as tested, some custom nodes, for example, https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/a0f451a5113cf9becb0847b92884cb10cbdec0ef/pyproject.toml#L5 using `license = "GPL-3.0 license"` format which is not allowed previously (has validation error).
2. Automatically register web folder from pyproject if web="xx" configured in pyproject.toml, which is requested by @robinjhuang 
It should have cli PR here https://github.com/Comfy-Org/comfy-cli/pull/284 merged at the same time
Tested with https://github.com/Comfy-Org/ComfyUI-React-Extension-Template/pull/12
Additonally, why do we still need this web folder read from pyproject after we have the logic of `hasattr(module, "WEB_DIRECTORY")` below? 
From my understanding, …

auto register web folder from pyproject

---

app/frontend_management.py

Allows frontend packages with standard semver suffixes (pre-release).
Has already been tested in the wild by users testing subgraph (by pulling the branch).

Allow specifying any frontend semver suffixes

---

comfy_config/types.py

due to some custom nodes have their own settings in pyproject.toml, we need to allow them, otherwise https://github.com/comfyanonymous/ComfyUI/issues/8514#issuecomment-2970202184

allow extra settings from pyproject.toml

---

main.py

While seeing the output on seconds is useful when they get longer ( which will start to happen more often since video models are here ) the total time gets a bit complicated to read on.
Specially for people leaving Comfy rendering overnight.
I hope this helps

Improve the log time function for 10 minute + renders

---

comfy/k_diffusion/sampling.py

Although this one isn't as straightforward as the others, it can still perform the adaptation. Since ancestral sampling operates on scaled sigmas in other model types, this adaptation simulates the scaled sigma scenario and applies alpha scaling within the algorithm.
Test with SD3.5 medium, sgm_uniform and CFG 3.

Singlestep DPM++ SDE for RF

---

.github/workflows/release-webhook.yml

Adds a new GitHub Action workflow that automatically calls the comfy-api webhook endpoint when releases are published.
- **Added** `release-webhook.yml` workflow
- **Triggers** on release `published` events
- **Calls** `POST /releases` endpoint in comfy-api
- **Includes** proper HMAC-SHA256 signature verification for security
- `RELEASE_GITHUB_WEBHOOK_URL` - Webhook endpoint URL
- `RELEASE_GITHUB_WEBHOOK_SECRET` - Secret for signature verification
This enables automated release note processing and other downstream release workflows.

[System Pop Up] Add GitHub Action for release webhook notifications

---

comfy/k_diffusion/sa_solver.py
comfy/k_diffusion/sampling.py
comfy/samplers.py
comfy_extras/nodes_custom_sampler.py

This is a remake of the previous #4454, introducing arbitrary-order, k-diffusion looping style, and logSNR computation. The previous PR simply adapted the official code to ComfyUI, while this one rewrites the computations to support arbitrary order (beyond 4), which is generally not useful, though. It's still submitted as a new PR.
By default, SA-Solver performs stochastic sampling (SDE) only in a limited interval (0.2 ≤ t ≤ 0.8), producing images with structure and composition that can be similar to ODE sampling.
PECE mode performs an additional evaluation per step to update the denoised output based on the corrected. Since the correction starts from step `i = 1`, NFE will be `2 * steps - 1`.
- SDXL sampler grid.
Both "ODE" and "full SDE" modes can be used by adjusting `eta` and the …

Add reconstructed SA-Solver sampler

---

comfy_extras/nodes_fresca.py

It now detects the number of `conds` and outputs them all, and skips the filter if `cond` or `uncond` is None.

Fix fresca's input and output

---

comfy_api/v3/io.py
comfy_api/v3/ui.py
comfy_extras/nodes_v3_test.py
comfy_extras/v3/nodes_images.py
comfy_extras/v3/nodes_mask.py
comfy_extras/v3/nodes_webcam.py

Schema changes:
- Make id optional on Output fields; autogenerated id's if not included, display on node will be io_type unless display_name is supplied.
- widgetType is never assigned a value by default unless MultiType is used
Small changes:
- Renamed 'node' on PreviewX classes to 'cls' to make it more clear what is intended to be passed in there
- Cleaned up ported v3 nodes to take advantage of automatic naming of inputs and unnecessary id's on outputs

V3 update - make id on Outputs optional, make widgetType only included with MultiType

---

comfy_api/v3/io.py
comfy_extras/v3/nodes_images.py

1. Removed unnecessary content_types field (not used in V1 nodes)
2. Switched to using the UploadType enum to specify the uploaded file type for COMBO inputs
Change **number 2** is required to port `audio` and `video` nodes to the V3

[V3] make generic upload parameters for io.Combo.Input

---

comfy_api/v3/io.py
comfy_extras/nodes_v3_test.py
execution.py

- Changed class cloning and locking to be less restrictive towards class references
- Renamed prepare_class_clone to PREPARE_CLASS_CLONE for usage consistency (internal only)
- Made a wrapper around execute so that the output received is always a NodeOutput
- Small typehint improvement by adding ComfyTypeI for types that only have Input but no Output class

V3 update - Changed class cloning/locking, renames/typehint improvements

---

requirements.txt

https://pypi.org/project/comfyui-workflow-templates/0.1.36/
**Template Updates & Fixes:**
- Fixed lotus template link issues (https://github.com/Comfy-Org/workflow_templates/pull/130)
- Updated model links across multiple templates (https://github.com/Comfy-Org/workflow_templates/pull/129)
- Updated image 2 image template (https://github.com/Comfy-Org/workflow_templates/pull/128)
- Replaced model links (https://github.com/Comfy-Org/workflow_templates/pull/127)
- Updated hunyuan 3d template links (https://github.com/Comfy-Org/workflow_templates/pull/126)
- Updated model links in the controlnet template (https://github.com/Comfy-Org/workflow_templates/pull/125)
- VACE  frame count issues (https://github.com/Comfy-Org/workflow_templates/pull/123)
- Correct the links in all VACE templates …

Upate template to 0.1.36

---

comfy_extras/nodes_mask.py

Fix code that is using the original `destination` input instead of the reshaped value.
If destination has 2 dimensions, then `MaskComposite` will throw
```
22:43:41.657 [Warning] [ComfyUI-0/STDERR]   File "G:\Apps\SwarmUI\dlbackend\comfy\ComfyUI\comfy_extras\nodes_mask.py", line 250, in combine
22:43:41.657 [Warning] [ComfyUI-0/STDERR]     destination_portion = destination[:, top:bottom, left:right]
22:43:41.658 [Warning] [ComfyUI-0/STDERR]                           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:43:41.659 [Warning] [ComfyUI-0/STDERR] IndexError: too many indices for tensor of dimension 2
22:43:41.660 [Warning] [ComfyUI-0/STDERR]
```
because, even though it reshapes the input, it accidentally uses the original input when computing the `destination_portion` to be affected by the …

Fix MaskComposite error when destination has 2 dimensions

---

comfy_api/internal/__init__.py
comfy_api/v3/io.py

- dynamicPrompts arg added to String.Input to match v1
- Added an as_dict_v3 method to Outputs, will be reworked into just 'as_dict' soon
- Added ComfyNodeInternal, to be renamed, that will be the basis of execution.py references soon
Ruff check fails due to whitespace, will merge anyways.

V3 update - dynamicPrompts, output serialization, start of internal

---

comfy_extras/nodes_custom_sampler.py

It's helpful to adjust `start_percent` or `end_percent` based on the corresponding sigma in the UI.
This node can also access the `sigma_max` and `sigma_min` from `model_sampling`.
Usage
1.  Check the sigma to see the active range during sampling.
2. Auto fill `sigma_max` and `sigma_min` in some nodes.

Add SamplingPercentToSigma node

---

comfy/model_management.py

Besides adding async offload for XPU, I also did the following:
- Cleaned up some xpu memory management and gated it by Pytorch version since it isn't clear what the minimum version of Pytorch ComfyUI actually enforces but I did see 2.3 used at the time of writing this so I went with that as kind of the minimum baseline for what needed a check and didn't.
- Changed the checks for BF16 and FP16 on XPU to be more precise using device properties that exist now which can be queried and again, gated by Pytorch version.
- Turned on non-blocking for XPU, this no longer freezes since around a year ago and speeds up stuff.
Again, works for my machine but ideally would get tested by others.

Add xpu version for async offload and some other things.

---

comfy_api/v3/ui.py
comfy_extras/v3/nodes_video.py
comfy_extras/v3/nodes_wan.py
nodes.py

1. Added `PreviewVideo` to `io`
2. All nodes were tested, all works nice
WAN nodes:

[V3] SaveVideo, LoadVideo, SaveWEBM, WAN nodes

---

comfy_api/internal/__init__.py
comfy_extras/nodes_v3_test.py
execution.py

The AI-generated shallow_clone_class did not set up the new_bases properly, hate to see it. Now another AI 'fixed' it, lovely.
Added some dummy classes to test it, will all be removed when v3 PR gets merged.

V3 update - fix super() not working within v3's execute classmethod

---

comfy/model_management.py

https://github.com/comfyanonymous/ComfyUI/issues/9024
Latest pytorch nightly xpu gives an error for mem_get_info, it seems this function is not implemented yet.

Fix xpu function not implemented.

---

comfy/model_management.py

https://github.com/comfyanonymous/ComfyUI/pull/9026

Fix xpu function not implemented p2.

---

comfy/k_diffusion/sampling.py

> This will change their behavior with the sampling `CONST` type. It also combines Euler CFG++ and Euler ancestral CFG++ into one main function.
The current Euler CFG++ can work on the `CONST` sampling type (RF), which matches the algorithm from the appendix of the paper, but the guidance scale must be very low (~0.1), and it’s unstable.
It tends to oversaturate when given more steps under the same guidance scales that seem to work with fewer steps.
Recently, the [official](https://github.com/CFGpp-diffusion/CFGpp/issues/12#issuecomment-3075778811) proposed a new approach for flow models, which separates denoised and noise estimation during sampling.
It changes the algorithm back to
```
eps_uncond = (x_s - alpha_s * uncond_denoised) / sigma_s
x_t = alpha_t * denoised_cfg + sigma_t * …
```

Separate denoised and noise estimation in Euler CFG++

---

comfy_api_nodes/README.md

This PR removes the removed anchor part after the hash in the link, which was found in https://github.com/Comfy-Org/docs/pull/287

Fix link from docs (due to document updates)

---

comfy_api/input/video_types.py
comfy_api/input_impl/video_types.py
comfy_api_nodes/nodes_moonvalley.py

Enable & update Moonvalley V2V node to comply with API specification requirements and validate on client before sending request, preventing users from wasting API calls.
- **Resolution validation**: Enforce exact supported resolutions (1920x1080, 1080x1920, 1152x1152, 1536x1152, 1152x1536)
- **Frame validation**: Update from divisible by 32 to divisible by 16
- **Format validation**: Add MP4 container format requirement
- **Parameter cleanup**: Remove `steps` and `guidance_scale` from V2V inference params (better to let server choose best default per model providers)
- **Duration handling**: Enforce 5-second video length with auto-trimming
- **API enhancement**: Add `get_container_format()` method to VideoInput classes for format detection
Tested with various video inputs to ensure:
- …

Add Moonvalley Marey V2V node with updated input validation

---

comfy/ldm/cosmos/cosmos_tokenizer/utils.py
comfy/ldm/modules/diffusionmodules/model.py

5b4e3127494674e9a3f2e668e8fb49b278e079a9 replaced `nonlinearity` with SiLU in `ResnetBlock`, but both `Encoder` and `Decoder` still have a call to `nonlinearity`. This PR also changes the `nonlinearity` in the old Cosmos vae.
Might be related to an old issue #1147.

Replace manual x * sigmoid(x) with torch silu in VAE nonlinearity

---

app/model_manager.py
app/user_manager.py

feat: add file creation time to model file metadata and user file info

API for Recently Used Items

---

requirements.txt

Added WAN2.2 FLF2V template
- Update some old video templates to use the save video node, which most users are more familiar with.
- Reduce package size 75MB => 65MB

Update template to 0.1.47

---

comfy_api_nodes/apinode_utils.py
comfy_api_nodes/apis/client.py
comfy_api_nodes/nodes_bfl.py
comfy_api_nodes/nodes_gemini.py
comfy_api_nodes/nodes_ideogram.py
comfy_api_nodes/nodes_kling.py
comfy_api_nodes/nodes_luma.py
comfy_api_nodes/nodes_minimax.py
comfy_api_nodes/nodes_moonvalley.py
comfy_api_nodes/nodes_openai.py
comfy_api_nodes/nodes_pika.py
comfy_api_nodes/nodes_pixverse.py
comfy_api_nodes/nodes_recraft.py
comfy_api_nodes/nodes_rodin.py
comfy_api_nodes/nodes_runway.py
comfy_api_nodes/nodes_stability.py
comfy_api_nodes/nodes_tripo.py
comfy_api_nodes/nodes_veo2.py

All converted nodes were tested, except for some `Tripo` - they are deactivated in the screenshot, because the nodes require the old `Tripo` model, and it is already deprecated in their API.
File operations were not converted to **async**, because it would require connecting the `aiofiles` library - I didn't want to complicate the review of this PR.
From what I tested, nodes are normally executed in parallel, only in UI it seems that `SaveImage` sometimes hangs - but **this is a deceptive impression**, UI simply does not change back what node is executed.
Example:
node A -> node B
node C -> node D
if node C is executed much longer than node A, then UI will display that node B has been executed after displaying - and will continue to show it as executed until node C finishes executing;
--- …

async API nodes 

---

execution.py

According to the documentation of [asyncio.run](https://docs.python.org/3.12/library/asyncio-runner.html#asyncio.run) - it does not use the current `event loop` at all.
Starting from the `Python 3.12` we can pass the desired event loop as _loop_factory_ argument, but if we do not pass it, **by default** the `asyncio.run` always create a new `event_loop`

remove creation of non-used asyncio_loop

---

comfy_api_nodes/nodes_kling.py

Currently, the `KlingImageGenerationNode` node always passes `image_type` to the Kling API, which **forces users to provide a reference image**, even though the Kling API supports generation from prompts alone and the reference image is optional.
Without this PR, the following error can occur when trying to generate an image:
Tested with this PR that fix are fine and does not break anything:
Since the `Kling-v1` model does not support image references, tests with it were skipped in some parts, as shown in the screenshot.

fix(Kling Image API Node): do not pass "image_type" when no image

---

comfy_api_nodes/nodes_moonvalley.py

- Changed default negative prompts to a more extensive list for both BaseMoonvalleyVideoNode and MoonvalleyVideo2VideoNode.
- Updated default guidance scale values for both nodes to enhance prompt adherence.
- Set a fixed default seed value for consistency in video generation.

Update default parameters for Moonvalley video nodes

---

comfy/ops.py

Turns out torch.compile has some gaps in context manager decorator syntax support. I've sent [patches to fix that in PyTorch](https://github.com/pytorch/pytorch/pull/160703), but it won't be available for all the folks running older versions of PyTorch, hence this trivial patch.

Avoid torch compile graphbreak for older pytorch versions

---

comfy_api_nodes/nodes_openai.py

Fixes: #9329
OpenAI images/edits rejects `application/octet-stream`. After switching to `aiohttp` our multipart builder defaulted to `octet-stream` for file parts, as `aiohttp` library does not have automated detection of mime-types from files names.
- OpenAIGPTImage1 node now adds files as `(filename, fileobj, "image/png")` for `image`, `image[]` and `mask`

fix(OpenAIGPTImage1): set correct MIME type for multipart uploads

---

comfy/ldm/flux/model.py
comfy/model_base.py
comfy_extras/nodes_flux.py

This node is only useful if someone trains the kontext model to properly use multiple reference images via the index method.
The default is the offset method which feeds the multiple images like if they were stitched together as one. This method works with the current flux kontext model.

Add FluxKontextMultiReferenceLatentMethod node.

---

comfy_extras/nodes_audio.py

BE changes for bounty task https://www.notion.so/drip-art/Audio-input-node-1706d73d365080eeb8e5e39790584dff?source=copy_link
and FE changes is here
- https://github.com/Comfy-Org/ComfyUI_frontend/pull/4289

record audio node

---

comfy_api_nodes/apis/__init__.py
comfy_api_nodes/nodes_kling.py

Kling API reference:
[https://app.klingai.com/global/dev/document-api/apiReference/model/skillsMap](https://app.klingai.com/global/dev/document-api/apiReference/model/skillsMap)
Currently, Text-to-Video is supported only by the **flagship** model, so I added only that one to the `KlingTextToVideoModelName` model.
I added both models to the `KlingVideoGenModelName` since both support Image-to-Video and produce very nice results.
Note: `kling-v2-1-master` does not have `std` or `pro` modes. For consistency, I labeled it as `pro` since this model outputs only `1080p` resolution videos, and in other Kling nodes such output resolution corresponds to `pro` mode.
Video showcasing the new models:
https://github.com/user-attachments/assets/ee55dabc-2ab2-4d3f-8394-32ad86333cb2

api_nodes: add kling-v2-1 and v2-1-master

---

app/user_manager.py

Closes #9434 
**Problem Summary**
Currently, when a user tries to save a workflow using a filename that contains characters forbidden by the operating system (e.g., a colon : on Windows), the save operation fails silently. The UI provides no warning or error message, leading the user to believe the workflow was saved successfully. This can result in the unintentional loss of work when the user later tries to load the non-existent file.
**Solution**
This PR addresses the issue by adding error handling to the backend post_userdata endpoint.
1. Added Exception Handling: The file-writing operation is now wrapped in a try...except OSError block.
2. Informative Error Response: If an OSError is caught (which occurs with invalid filenames), the server now returns a 400 Bad Request status code …

Fix: Handle invalid filenames during workflow save (#9434)

---

comfy_extras/nodes_ace.py
comfy_extras/nodes_advanced_samplers.py
comfy_extras/nodes_apg.py
comfy_extras/nodes_attention_multiply.py

PR covers next files: `nodes_ace.py`, `nodes_advanced_samplers.py`, `nodes_apg.py`, `nodes_attention_multiply.py`
All nodes in these files are not used in any other community nodes and can be safely converted.
Edited: 
1. Removed changes to the file `nodes_align_your_steps.py` as that changes will be covered by a separate PR.
2. Removed changes to the file `nodes_audio.py` as community uses that nodes with inheritance and it will be covered in a separate PR.

v3 nodes (part a)

---

comfy/ldm/modules/diffusionmodules/mmdit.py
comfy/ldm/qwen_image/model.py
comfy/ldm/wan/model.py

Enable some elementwise fusions to accelerate SD3.5, Qwen and WAN
| Model             | Off      | On       | Speedup |
|-------------------|----------|----------|---------|
| Qwen              | 18621.99 | 17923.49 | 104%    |
| SD3.5M            | 2967.57  | 2705.65  | 110%    |
| SD3.5L            | 7480.96  | 7432.2   | 101%    |
| SD3.5M Scaled FP8 | 2466.09  | 2194.93  | 112%    |

Add elementwise fusions

---

comfy_extras/nodes_easycache.py

EasyCache (and LazyCache) currently doesn't handle the condition where the latent size (or dtype or device) changes during sampling. For example, this might occur if the sampler is doing progressive upscaling during sampling (and ComfyUI actually has a built in node for that, though I don't think anyone uses it).
This pull just keeps track of the input tensor shape/dtype/device and calls the `.reset()` method if it ever changes. Lightly tested but seems to fix the problem for me and doesn't appear to break anything.

Fix EasyCache/LazyCache crash when tensor shape/dtype/device changes during sampling

---

comfy_api_nodes/apis/gemini_api.py
comfy_api_nodes/nodes_gemini.py
requirements.txt

Initial code for this PR was made by @bigcat88 , I finished the remainder required to work with the API endpoint.
Associated frontend PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5219

Adding Google Gemini Image API node

---

comfy/k_diffusion/sampling.py
comfy/samplers.py

Following up of #9444.
DPM++ 2M SDE with Heun solver type leads to the same formulation with RES, and this work adds `dpmpp_2m_sde_heun` sampler and removes `res_multistep_ancestral` that is not working on RF currently.
Checked that it produces the same results with fixed `res_multistep_ancestral` in #9444, with the last Euler step disabled and the noise sampler replaced to `BrownianTreeNoiseSampler`.
Example results from FLUX Krea:
before, `res_multistep_ancestral`  | #9444, `res_multistep_ancestral` |  [matched](https://gist.github.com/Balladie/089bb156cd6e24027216d5acb23a4ead), `res_multistep_ancestral` |   `dpmpp_2m_sde_heun` 
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:

Add DPM++ 2M SDE Heun (RES) sampler

---

comfy/k_diffusion/sampling.py

The current noise decomposition seems right for the default `r`, but not for other cases. For instance, setting `r=1` in SEEDS-2 will fully use a new noise, instead of depending on the noise from the first stage that already covers the current interval [s, t]. This seems not to match the claim that "overlapping time intervals need to be dependent."
Therefore, I tried to follow the existed derivation to obtain another result.
In this decomposition, when `r=1`, `z1` dominates the current interval. In SEEDS-2, this appears to produce relatively sharper results at low CFG and in the low NFE regime when `r > 0.5`.
Test with V-prediction ztsnr model and simple scheduler. 
- SEEDS-2 CFG 1
- SEEDS-2 CFG 3
- SEEDS-3 CFG 1
- Extract phi functions since they are commonly used in exponential-based …

SEEDS: update noise decomposition and refactor

---

comfy/cli_args.py
comfy/ops.py

This will test the Top10 algorithms returned by the cuDNN heuristic and select the fastest. On a 5090 I'm seeing
- 1.41x on SDXL
- 1.32x on SD15
- 1.21x on VAE Decoder (SDXL)
This does add a small overhead during the first inference -  in my case this was ~200ms.

Enable Convolution AutoTuning

---

server.py

If "prompt_id" is provided in the interrupt call, check first if it matches the currently running prompt. Ignore the interrupt if prompt id does not match. This prevents race conditions where the prompt that was intended to be interrupted had finished already.
If no prompt_id is provided, the behavior remains same as before.
Manual tests:
- Using curl, checked that
- providing no json body works (old behavior)
- wrong prompt_id does not interrupt executing job
- correct prompt_id does interrupt executing job
- Tested with latest frontend. Job cancellation works both using queue>right-click>delete, and clicking the red X button beside Run.

Accept prompt_id in interrupt handler

---

comfy_api_nodes/nodes_bytedance.py
nodes.py

This PR adds API nodes for [BytePlus](https://docs.byteplus.com/en/docs/ModelArk/1541523) models using the V3 Schema.
It implements only image-related nodes:
- `text2image`
- `img2img`
Currently only supported models are `seedream-3-0-t2i` for Text2Image and `seededit-3-0` for Image Editing.

feat(api-nodes): add ByteDance Image nodes

---

comfy_api_nodes/nodes_runway.py

The converted nodes have been tested and are working. Demo:
https://github.com/user-attachments/assets/ab2b901a-2f2d-44f1-9fa1-5a643b1b1949
Some refactoring was also done to remove code duplication and minor fixes were made with additional client-side validation, compliance queries (added aspect ratio checks on input images everywhere, etc.).

[V3] convert Runway API nodes to the V3 schema

---

comfy_extras/nodes_align_your_steps.py

This node is widely used by the community in these three ways:
```python
if scheduler.startswith('AYS'):
sigmas = nodes.NODE_CLASS_MAPPINGS['AlignYourStepsScheduler']().get_sigmas(scheduler[4:], steps, denoise=1.0)[0]
else:
sigmas = samplers.calculate_sigmas(model.get_model_object("model_sampling"), scheduler, steps)
```
```python
from comfy_extras.nodes_align_your_steps import AlignYourStepsScheduler
model_type = scheduler.split(' ')[1]
sigmas = AlignYourStepsScheduler().get_sigmas(model_type, steps, denoise)[0]
```
```python
sigmas = nodes_align_your_steps.AlignYourStepsScheduler.get_sigmas(self, model_type, steps, denoise)
sampler = comfy.samplers.sampler_object(sampler_name)
```
**All of these variants were tested with this PR.**
Why is `get_sigmas` not defined as follows in this PR: …

convert AlignYourStepsScheduler node to V3 schema

---

middleware/__init__.py
middleware/cache_middleware.py
server.py
tests-unit/server_test/test_cache_control.py

Fixes https://github.com/Comfy-Org/ComfyUI_frontend/issues/4438
Majority of discussion was in:
1. https://github.com/Comfy-Org/ComfyUI_frontend/issues/4438
2. https://github.com/Comfy-Org/ComfyUI_frontend/pull/5174 and 
TL;DR: Add cache controls to store images for 1 day and only try to resolve missing images every 1 hour.
1. [model_manager.py](https://github.com/comfyanonymous/ComfyUI/blob/5352abc6d389570455776c457738db54367cd6cb/app/model_manager.py#L52-L77) has an experimental preview endpoint to serve preview images from the filesystem.
2. [frontend code](https://github.com/Comfy-Org/ComfyUI_frontend/blob/8646ca416210acd12618d31bffe4cb042b1c6607/src/components/sidebar/tabs/modelLibrary/ModelTreeLeaf.vue#L46-L56) tries to fetch images these images, but there is no cache control on them …

fix: add cache headers for images 

---

comfy_api_nodes/nodes_bytedance.py

Frontend PR with prices: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5481

add new ByteDanceSeedream (4.0) node

---

comfy/text_encoders/hunyuan_image.py

Remove single quote pattern to avoid wrong text matches 
cc @comfyanonymous

HunyuanImage: Remove single quote pattern to avoid wrong text matches

---

comfy/k_diffusion/sampling.py
comfy/ldm/modules/attention.py

Currently it's not possible to run ComfyUI with `python -O` because asserts only run when optimization is disabled and there are a couple places where ComfyUI actually depends on assert raising an exception for correct handling.
It's possible there are places I missed when I looking through the source code for similar structures but with these changes I can verify that ACE-Steps, Chroma Radiance and SDXL work when the Python interpreter is running with optimization enabled.
In the process of fixing that problem, I also noticed that `BatchedBrownianTree` doesn't correctly handle the case where `w0` is passed in kwargs. I don't think this happens in practice anywhere but if `w0` does get passed, it'll be included in the kwargs passed to `torchsde.BrownianTree` which doesn't support that …

Fix python -O and BatchedBrownianTree w0 handling

---

comfy/ldm/flux/math.py
comfy/ldm/wan/model.py

This change reduces the peak VRAM usage of WAN and increases the maximum latent size in constrained VRAM conditions.
Example Test Conditions:
RTX3060
--novram mode
WAN2.2 I2V 14B Q4_K_S GGUF + lightx2v 4steps LoRA (based on video_wan2_2_14B_i2v template)
1024x1024x61frames video generation
Without this change, this VRAM OOMs:
```
...
File "/home/rattus/ComfyUI/comfy/ldm/wan/model.py", line 624, in _forward
return self.forward_orig(x, timestep, context, clip_fea=clip_fea, freqs=freqs, transformer_options=transformer_options, **kwargs)[:, :, :t, :h, :w]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/rattus/ComfyUI/comfy/ldm/wan/model.py", line 569, in forward_orig
x = block(x, e=e0, freqs=freqs, …
```

Reduce Peak WAN inference VRAM usage

---

comfy_extras/nodes_post_processing.py

I encountered an issue while applying sharpening to an image result from a workflow and got this error.
```RuntimeError: expected scalar type Half but found Float```
I fixed it by by making gaussian kernel of same type as image to avoid mismatch issues.

Fix image sharpen node

---

comfy_extras/nodes_differential_diffusion.py

There is a PR from almost year ago that was marked as good but never reviewed: https://github.com/comfyanonymous/ComfyUI/pull/5709
Still seems relevant in modern times, but it's apparently too old for me to be able to apply commits to that PR directly. So, I've cleaned up things in this PR instead and included the original commits.

[Reviving #5709] Add strength input to Differential Diffusion

---

comfy/ops.py
comfy/weight_adapter/loha.py
comfy/weight_adapter/lokr.py
comfy/weight_adapter/lora.py
comfy/weight_adapter/oft.py
comfy_extras/nodes_train.py

As title, this pr fix lora training with FP8 models.

Fix LoRA Trainer bugs with FP8 models.

---

comfy_api_nodes/apis/rodin_api.py
comfy_api_nodes/nodes_rodin.py

Add a new Rodin3D api-node: **[Rodin 3D Generate - Gen-2 Generate]**
Also, the parameters uploaded by nodes were modified:
`quality` -> `quality_override`: `quality_override` allows for more flexible control over the poly count of the generated models.

Rodin3D - add [Rodin3D Gen-2 generate] api-node

---

comfy_extras/nodes_audio.py

This adds some basic audio tensor manipulation nodes. I tried to choose unique names based on the node database.
TrimAudioDuration
- Selects a range from the audio based on start index and duration in seconds.
SplitAudioChannels
- Splits stereo audio to it's left and right channels
AudioConcat
- Concatenates two audio inputs into one
AudioMerge
- Merges two audio inputs into one stream
AudioAdjustVolume
- Adjusts audio volume by decibels
EmptyAudio
- Generates empty audio tensor, useful for InfiniteTalk etc. as encoded silence can be used to limit mouth movement

Add new audio nodes

---

comfy_extras/nodes_post_processing.py

The nodes were tested after conversion, trying to make only minimal changes to the file.

[V3] convert nodes_post_processing to V3 schema

---

comfy_extras/nodes_clip_sdxl.py

Some community nodes will require adjustments after this PR:
* https://github.com/SeargeDP/SeargeSDXL
* https://github.com/Beinsezii/bsz-cui-extras
* https://github.com/bash-j/mikey_nodes
* https://github.com/shiimizu/ComfyUI_smZNodes
* https://github.com/rgthree/rgthree-comfy
* https://github.com/LatentSpaceDirective/ComfyUI-Texturaizer

[V3] convert CLIPTextEncodeSDXL nodes to V3 schema

---

comfy_extras/nodes_pixart.py

[V3] convert nodes_pixart.py to V3 schema

---

comfy_extras/nodes_photomaker.py

[V3] convert nodes_photomaker.py to V3 schema

---

comfy_extras/nodes_qwen.py

One node of two was tested after conversion(_second node is almost the same_):
git diff:
```
index 1e7b5ce..5e3cb67 100644
@@ -26342,8 +26342,7 @@
"input": {
"required": {
"clip": [
-                    "CLIP",
+                    "CLIP"
],
"prompt": [
"STRING",
@@ -26355,12 +26354,10 @@
},
"optional": {
"vae": [
-                    "VAE",
+                    "VAE"
],
"image": [
-                    "IMAGE",
+                    "IMAGE"
]
}
},
@@ -26383,25 +26380,18 @@
"CONDITIONING"
],
-        ],
"name": "TextEncodeQwenImageEdit",
- …
```

[V3] convert nodes_qwen.py to V3 schema

---

comfy/ldm/flux/math.py
comfy/ldm/wan/model.py

This change further reduces the peak VRAM usage of WAN and increases the maximum latent size in constrained VRAM conditions, following on from my previous PR for the same (https://github.com/comfyanonymous/ComfyUI/pull/9898).
Example Test Conditions:
RTX3060
--novram mode
WAN2.2 I2V 14B Q4_K_S GGUF + lightx2v 4steps LoRA (based on video_wan2_2_14B_i2v template)
1024x1024x77f video generation
Without this change, this VRAM OOMs:
```
File "/home/rattus/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/rattus/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
return forward_call(*args, **kwargs) …
```

Reduce Peak WAN inference VRAM usage - part II

---

comfy_extras/nodes_hypertile.py

Gtt diff:
```
index eed16cf..9e298ca 100644
@@ -8212,8 +8212,7 @@
"input": {
"required": {
"model": [
-                    "MODEL",
+                    "MODEL"
],
"tile_size": [
"INT",
@@ -8265,18 +8264,12 @@
"MODEL"
],
-        ],
"name": "HyperTile",
+        "display_name": "HyperTile",
"python_module": "comfy_extras.nodes_hypertile",
"category": "model_patches/unet",
-        "api_node": false
+ …
```

[V3] convert nodes_hypertile.py to V3 schema

---

comfy_extras/nodes_mochi.py

Git diff:
```
index 34579ea..c2d91f9 100644
@@ -20735,18 +20735,12 @@
"LATENT"
],
-        ],
"name": "EmptyMochiLatentVideo",
+        "display_name": "EmptyMochiLatentVideo",
"python_module": "comfy_extras.nodes_mochi",
"category": "latent/video",
-        "api_node": false
+        "output_node": false
},
"SkipLayerGuidanceDiT": {
"input": {
```

[V3] convert nodes_mochi.py to V3 schema

---

comfy_extras/nodes_perpneg.py

Non-deprecated node was tested after conversion:
Git diff:
```
index 10aa85e..820d8c2 100644
@@ -10455,12 +10455,10 @@
"input": {
"required": {
"model": [
-                    "MODEL",
+                    "MODEL"
],
"empty_conditioning": [
-                    "CONDITIONING",
+                    "CONDITIONING"
],
"neg_scale": [
"FLOAT",
@@ -10489,37 +10487,28 @@
"MODEL"
],
-        ],
"name": "PerpNeg",
"display_name": "Perp-Neg (DEPRECATED by PerpNegGuider)",
"python_module": "comfy_extras.nodes_perpneg",
"category": "_for_testing", …
```

[V3] convert nodes_perpneg.py to V3 schema

---

requirements.txt

Bump frontend to 1.27.7
```
python main.py --front-end-version Comfy-Org/ComfyUI_frontend@1.27.7
```
- Diff: [v1.26.13...v1.27.7](<https://github.com/Comfy-Org/ComfyUI_frontend/compare/v1.26.13...v1.27.7>)
- PyPI Package: <https://pypi.org/project/comfyui-frontend-package/1.27.7/>
- npm Types: https://www.npmjs.com/package/@comfyorg/comfyui-frontend-types/v/1.27.7
- Adds a new subgraph publishing functionality
- Improves the Floating Selection Toolbox
- Reworks the theme menu
- Introduces a new adaptive lod threshold
- Adds new navigation settings for left click and scroll wheel
- Upgrades Tailwind to v4
- Enable mouse gestures over video previews
- Fix clicks near DOMWidgets being swallowed
- When converting single group to subgraph, also convert children
- Adds dynamic icon support for …

Bump frontend to 1.27.7

---

comfy_api/latest/_io.py
comfy_extras/nodes_audio_encoder.py

https://github.com/user-attachments/assets/1b5255bc-d008-4c82-a12a-8227ed7a4fd7
Git diff:
```
index 24e07cb..557d07e 100644
@@ -28026,11 +28026,7 @@
"input": {
"required": {
"audio_encoder_name": [
-                    "COMBO",
-                    {
-                        "multiselect": false,
-                        "options": []
-                    }
+                    []
]
}
},
@@ -28048,29 +28044,21 @@
"AUDIO_ENCODER"
],
-        ],
"name": "AudioEncoderLoader",
+        "display_name": "AudioEncoderLoader", …
```

[V3] convert nodes_audio_encoder.py to V3 schema

---

comfy_extras/nodes_gits.py

Affected community nodes:
* [cardenluo/ComfyUI-Apt_Preset](https://github.com/cardenluo/ComfyUI-Apt_Preset)
* [blepping/comfyui_jankdiffusehigh](https://github.com/blepping/comfyui_jankdiffusehigh)
* [Ly-scnu/ComfyUI_TinyTerraLyNodes](https://github.com/Ly-scnu/ComfyUI_TinyTerraLyNodes)
* [pamparamm/ComfyUI-ppm](https://github.com/pamparamm/ComfyUI-ppm)
* [ltdrdata/ComfyUI-Impact-Pack](https://github.com/ltdrdata/ComfyUI-Impact-Pack)
* [TinyTerra/ComfyUI_tinyterraNodes](https://github.com/TinyTerra/ComfyUI_tinyterraNodes)
* [LatentSpaceDirective/Comfyui-Texturaizer](https://github.com/LatentSpaceDirective/Comfyui-Texturaizer)

[V3] convert nodes_gits.py to V3 schema

---

comfy_extras/nodes_optimalsteps.py

Git diff:
```
index ed72c87..c2d91f9 100644
@@ -25822,15 +25822,11 @@
"input": {
"required": {
"model_type": [
-                    "COMBO",
-                    {
-                        "multiselect": false,
-                        "options": [
-                            "FLUX",
-                            "Wan",
-                            "Chroma"
-                        ]
-                    }
+                    [
+                        "FLUX",
+                        "Wan",
+                        "Chroma"
+                    ]
],
"steps": [
"INT",
@@ -25867,18 +25863,12 @@
"SIGMAS"
],
- …
```

[V3] convert nodes_optimalsteps.py to V3 schema

---

comfy_extras/nodes_pag.py

Git diff:
```
index 97902aa..820d8c2 100644
@@ -18262,8 +18262,7 @@
"input": {
"required": {
"model": [
-                    "MODEL",
+                    "MODEL"
],
"scale": [
"FLOAT",
@@ -18292,18 +18291,12 @@
"MODEL"
],
-        ],
"name": "PerturbedAttentionGuidance",
+        "display_name": "PerturbedAttentionGuidance",
"python_module": "comfy_extras.nodes_pag",
"category": "model_patches/unet",
- …
```

[V3] convert nodes_pag.py to V3 schema

---

comfy_extras/nodes_lt.py

The nodes were tested in 3 different workflows and the execution results were compared with the V1 versions to ensure that the conversion does not break the operation of the nodes.
Git diff:
```
index 4405bbe..7d998bd 100644
@@ -20986,37 +20986,27 @@
"LATENT"
],
-        ],
"name": "EmptyLTXVLatentVideo",
+        "display_name": "EmptyLTXVLatentVideo",
"python_module": "comfy_extras.nodes_lt",
"category": "latent/video/ltxv",
-        "api_node": false
+ …
```

[V3] convert nodes_lt.py to V3 schema

---

comfy_extras/nodes_eps.py
nodes.py

This PR introduces `Epsilon Scaling`, a new node that implements a powerful, inference-time technique to mitigate **exposure bias** in diffusion models. This method, based on the paper **[Elucidating the Exposure Bias in Diffusion Models](https://openreview.net/forum?id=xEJMoj1SpX)**, leads to noticeable improvements in detail, texture, and prompt adherence without requiring model retraining.
Diffusion models are trained to denoise images from a noisy distribution. However, during inference, they operate on their own progressively cleaner predictions. This mismatch between the training and inference processes, known as **exposure bias**, often manifests as a subtle loss of detail, muted textures, and reduced overall image quality.
This new method offers a more direct and effective …

feat: Add Epsilon Scaling node for exposure bias correction

---

comfy/sd.py

When the VAE catches this VRAM OOM, it launches the tiler fallback logic straight from the exception context.
Python however refs the entire call stack that caused the exception including any local variables for the sake of exception report and debugging. In the case of tensors, this can hold on the references to GBs of VRAM and inhibit the VRAM allocator from freeing them.
So dump the except context completely before going back to the VAE via the tiler by getting out of the except block with nothing but a flag.
The greatly increases the reliability of the tiler fallback, especially on low VRAM cards, as with the bug, if the leak randomly leaked more than the headroom needed for a single tile, the tiler fallback would OOM and fail the flow.
Test conditions:
768x768x13f WAN 2.1 VAE Encode …

sd: fix VAE tiled fallback VRAM leak

---

comfy/ldm/wan/vae.py

If this suffers an exception (such as a VRAM oom) it will leave the encode() and decode() methods which skips the cleanup of the WAN feature cache. The comfy node cache then ultimately keeps a reference this object which is in turn reffing large tensors from the failed execution.
The feature cache is currently setup at a class variable on the encoder/decoder however, the encode and decode functions always clear it on both entry and exit of normal execution.
Its likely the design intent is this is usable as a streaming encoder where the input comes in batches, however the functions as they are today don't support that.
So simplify by bringing the cache back to local variable, so that if it does VRAM OOM the cache itself is properly garbage collected when the encode()/decode() functions …

WAN VAE: Fix cache VRAM leak on error

---

comfy_api_nodes/apis/__init__.py
comfy_api_nodes/nodes_kling.py

https://github.com/user-attachments/assets/12373188-7662-4588-b27e-e5549fbf7645
PR with prices: https://github.com/Comfy-Org/ComfyUI_frontend/pull/5892

feat(api-nodes): add kling-2-5-turbo to txt2video and img2video nodes

---

.github/workflows/test-assets.yml
app/alembic_db/versions/0001_assets.py
app/database/models.py

This PR targets **dev** branch.
Additionally added forgotten `Index("uq_assets_hash", "hash", unique=True),` to `models.py` (found during test of previous PR with `alembic revision --autogenerate -m test` command)

[assets] drop PgSQL 14, unite migration for SQLite and PgSQL

---

comfy_api_nodes/nodes_recraft.py
pyproject.toml

Enable `bad-indentation` rule and fix found code

fix(api-nodes): bad indentation in Recraft API node function

---

comfy_extras/nodes_torch_compile.py

Node was tested after conversion(that it actually works):
```
Requested to load Lumina2
100%|██████████| 40/40 [00:11<00:00,  3.51it/s]
Requested to load Lumina2
100%|██████████| 40/40 [00:09<00:00,  4.12it/s]
```
Git diff:
```
index cb8306e..35fd591 100644
@@ -20801,18 +20801,13 @@
"input": {
"required": {
"model": [
-                    "MODEL",
+                    "MODEL"
],
"backend": [
-                    "COMBO",
-                    {
-                        "multiselect": false,
-                        "options": [
-                            "inductor",
-                            "cudagraphs"
-                        ]
- …
```

[V3] convert nodes_torch_compile.py to V3 schema

---

comfy/ldm/wan/model.py

Fixed incorrect type hint syntax in `MotionEncoder_tc.__init__()` parameter list.
- Line 647: Changed `num_heads=int` to `num_heads: int` 
- This corrects the parameter annotation from a default value assignment to proper type hint syntax
The parameter was using assignment syntax (`=`) instead of type annotation syntax (`:`), which would incorrectly set the default value to the `int` class itself rather than annotating the expected type.

Fix type annotation syntax in MotionEncoder_tc __init__

---

comfy_api_nodes/nodes_rodin.py

As usual nodes were tested after conversion:
Note: The git diff code in the web interface is a bit confusing because all these nodes use parent inheritance, which I've moved into separate functions. Local git diff using Visual Studio or PyCharm looks much better. I didn't change the logic or anything else - just converted it to V3 to reduce the likelihood of errors.
Object git diff:
```
index 2b7d3c6..e298a14 100644
@@ -38627,7 +38627,9 @@
"required": {
"Images": [
"IMAGE",
+                    {
+                        "forceInput": true
+                    }
]
},
"optional": {
@@ -38643,36 +38645,30 @@
"Material_Type": [
"COMBO",
{
- …
```

[V3] convert nodes_rodin.py to V3 schema

---

comfy_extras/nodes_stable3d.py

Two nodes(out of three) was tested after this simple conversion:
Objects git diff:
```
index 42058ad..9330acc 100644
@@ -10642,16 +10642,13 @@
"input": {
"required": {
"clip_vision": [
-                    "CLIP_VISION",
+                    "CLIP_VISION"
],
"init_image": [
-                    "IMAGE",
+                    "IMAGE"
],
"vae": [
-                    "VAE",
+                    "VAE"
],
"width": [
"INT",
@@ -10728,35 +10725,24 @@
"negative",
"latent"
],
-            null,
-            null,
-        ],
"name": "StableZero123_Conditioning",
- …
```

[V3] convert nodes_stable3d.py to V3 schema

---

comfy_api_nodes/nodes_pixverse.py

Following up with the bug found during the development of this PR: https://github.com/comfyanonymous/ComfyUI/pull/10177
Video with bug(after generation I press F5 and my workflow is a little bit broken as Frontend assigns the "Results" to the `negative_prompt` field which have `force_input=True` - _my assumption_):
https://github.com/user-attachments/assets/fef9a21f-7f92-4684-a587-73e5093c55dc
To quickly and easy fix it I suggest to remove `force_input=True` from the negative_prompt definition and additionally to allow it to be `multiline`.
To verify that this change wasn't breaking, I created a test workflow, and export it as usual and additionally in API format.
After that I switched to this PR and run both versions:
https://github.com/user-attachments/assets/d9bd30fd-2741-4af1-b00c-3037 …

fix(api-nodes): allow negative_prompt in PixVerse API nodes to be multiline

---

comfy_api_nodes/nodes_kling.py

The test workflow was saved in V1 nodes and loaded and tested in V3:
https://github.com/user-attachments/assets/e3660efb-64c7-4e5e-b2e8-43f8b574eaee
Note:
1. I was not able to get Camera Control working with most parameters in the V1 Nodes version. Error: `camera_control.config is not allowed for this type: right_turn_forward`.
2. Lip Sync Audio wasn’t tested either because it rejects MP3 and WAV inputs. Error: `"Audio format is invalid"`.
We can investigate these in a separate PR if needed, since this conversion PR does not change behavior or include fixes.
Objects git diff:
[object_info_difference.zip](https://github.com/user-attachments/files/22725544/object_info_difference.zip)

[V3] convert nodes_kling.py to V3 schema

---

comfy_api/latest/_io.py
comfy_api_nodes/nodes_bytedance.py
comfy_api_nodes/nodes_kling.py
comfy_api_nodes/nodes_luma.py
comfy_api_nodes/nodes_pika.py
comfy_api_nodes/nodes_pixverse.py
comfy_api_nodes/nodes_runway.py
comfy_api_nodes/nodes_stability.py
comfy_api_nodes/nodes_vidu.py

This PR adds a tiny normalization step so `Combo.Input` can take a Python `Enum` class directly as `options`. We expand the enum to its member `.value` list at construction time, which:
* eliminates repetitive `[m.value for m in MyEnum]` boilerplate
* ensures options stay in sync with the enum definition
The change is backward‑compatible (existing `list[str]` still works) and requires no frontend adjustments. Default handling remains unchanged.
_Also extended typing for `options` and `default` as they can receive `int`s and not only `str` which many API nodes passes to them._
Example of the simplification(in API nodes there is **around 30** such usages):
```python
comfy_io.Combo.Input(
"model",
options=Text2ImageModelName,  # old code: options=[model.value for model in …
```

feat(V3-io): allow Enum classes for Combo options
